### ISSUE TITLE
plugin.streaming: videobufferkf is implemented?

### ISSUE THREAD

**Issue by uasan** [meetecho/janus-gateway#1002]
Hello.

In our stream, key frames are transmitted, once every 3 seconds.
The configuration specified videobufferkf: yes.

But new connection see view video, only after ±3 seconds.
Param videobufferkf, implemented or not yet?

Thanks.

**Comment by lminiero** [comment]
videobufferkf is implemented, but it doesn't work as expected as browsers still don't don't render anything most of the times, I guess due to late differences it receives from the original keyframe. The best that happens at times is a frozen image until the next keyframe. As such, it's not a very useful feature for the moment.

Closing as not an issue.
