### ISSUE TITLE
After new Janus install with base config, error appear

### ISSUE THREAD

**Issue by 4i-helpynet** [meetecho/janus-gateway#1004]
[ERR] [plugins/janus_streaming.c:janus_streaming_relay_thread:4238] [gstreamer-sample] Error polling... 4 (Interrupted system call)

After I enable in the streamer.cfg the h264 test then:
[ERR] [plugins/janus_streaming.c:janus_streaming_relay_thread:4238] [h264-sample] Error polling... 4 (Interrupted system call)

**Comment by lminiero** [comment]
I've started seeing those too, which is weird, I'll look into it.

**Comment by lminiero** [comment]
Mh, according to `git bisect` the cause is this commit here: https://github.com/meetecho/janus-gateway/commit/c787cc1fd5500f93e54e1dcd9132a549f4d8acce
I tried removing the WebSockets transport, and it does indeed fix the `Interrupted system call` error on thye mountpoints, which stay alive! But it doesn't make sense... why would the WebSockets transport affect the Streaming plugin? I'll have to keep digging...

**Comment by lminiero** [comment]
I've fixed this by ignoring the EINTR error in the Streaming mountpoints poll requests: apparently the new WebSockets approach triggers some signal that causes poll to interrupt (maybe a SIGHUP somewhere?), which this new check I added should fix.
