### ISSUE TITLE
High 100% cpu usage without active connection

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#1046]
Hi

On my server janus use 100% cpu, without any active connection. One empty idle textroom opened.
Active Sessions 2.
1. session for idle textroom, and 1 idle session without handle for background runing api call request.

How to debug why using high cpu by janus gw? I try strace first with pid number:

```
Process 15448 attached
restart_syscall(<... resuming interrupted call ...>) = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
nanosleep({0, 250000000}, NULL)         = 0
```

thanks.

**Comment by lminiero** [comment]
You need to use `ps` to check which of the threads is eating CPU, e.g.:

    ps -To pcpu,tid,comm -C janus | sort -r -k1

**Comment by lminiero** [comment]
Any update?

**Comment by izemize** [comment]
Sorry but not reproduced now. I report when saw high cpu

**Comment by lminiero** [comment]
Ack, closing then as we can consider it an isolated incident. Should it happen again, the command I wrote above should give you more info on what's causing the issue.

**Comment by izemize** [comment]
Hi again. High cpu back!

root@segitunk:~# ps -To pcpu,tid,comm -C janus | sort -r -k1
%CPU   TID COMMAND
 1.3  9247 ws thread
 0.1  9237 SCTP timer
 0.0  9250 http watchdog
 0.0  9249 libmicrohttpd
 0.0  9248 libmicrohttpd
 0.0  9246 videoroom handl
 0.0  9245 videoroom watch
 0.0  9244 nosip handler
 0.0  9243 nosip watchdog
 0.0  9242 textroom handle
 0.0  9241 textroom watchd
 0.0  9240 janus events th
 0.0  9239 janus sampleevh
 0.0  9238 sessions watchd
 0.0  9232 SCTP iterator
 0.0  9231 handles watchdo
 0.0  9230 log
 0.0  9229 janus
 0.0 16357 libmicrohttpd
 0.0 16355 libmicrohttpd

**Comment by lminiero** [comment]
No high CPU in this log, maybe you executed the command when it had already
gone down?

Il 10 nov 2017 9:52 PM, "izemize" <notifications@github.com> ha scritto:

Hi again. High cpu back!

root@segitunk:~# ps -To pcpu,tid,comm -C janus | sort -r -k1
%CPU TID COMMAND
1.3 9247 ws thread
0.1 9237 SCTP timer
0.0 9250 http watchdog
0.0 9249 libmicrohttpd
0.0 9248 libmicrohttpd
0.0 9246 videoroom handl
0.0 9245 videoroom watch
0.0 9244 nosip handler
0.0 9243 nosip watchdog
0.0 9242 textroom handle
0.0 9241 textroom watchd
0.0 9240 janus events th
0.0 9239 janus sampleevh
0.0 9238 sessions watchd
0.0 9232 SCTP iterator
0.0 9231 handles watchdo
0.0 9230 log
0.0 9229 janus
0.0 16357 libmicrohttpd
0.0 16355 libmicrohttpd

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/meetecho/janus-gateway/issues/1046#issuecomment-343478714>,
or mute the thread

**Comment by izemize** [comment]
No. In TOP a saw janus uses 100+% cpu, server load load average: 1,40, 1,40, 1,38
Janus not killed, runing with high cpu usage.

**Comment by lminiero** [comment]
That's not what I see in the ps results. Try htop or something like that to
find the thread responsible for this.

Il 11 nov 2017 12:30 AM, "izemize" <notifications@github.com> ha scritto:

No. In TOP a saw janus uses 100+% cpu, server load load average: 1,40,
1,40, 1,38
Janus not killed, runing with high cpu usage.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/meetecho/janus-gateway/issues/1046#issuecomment-343520434>,
or mute the thread

**Comment by izemize** [comment]
Ok. I installed htop and it's display "ws thread" uses 100% cpu, about 5hours. When i killed this thread works normal. (i don't use ws connections now)

**Comment by izemize** [comment]
* janus exited after killed ws thread

**Comment by atoppi** [comment]
1) update janus
2) use perf to profile the process

**Comment by puterboy** [comment]
I am new to perf, can you suggest what arguments to run?

BTW, the current jason command line is:

nice $JANUS_DIR/bin/janus -o --stun-server=stun.l.google.com:19302 --configs-folder=$JANUS_DIR/etc/janus
