### ISSUE TITLE
SIP Plugin: Should we be more tolerant of ICMP errors ?  (I hope, yes)

### ISSUE THREAD

**Issue by mtbramo** [meetecho/janus-gateway#1095]
Lorenzo,
I get some problem (hangup response from Janus) as soon as I perform consultation call operation. Even before you get a Janus SIP message of the operation (RE-INVITE), media-path on remote device has changed so you get ICMP response on RTP packet sent.
I have looked at the POLLERR treatment and even for RTP fd, I think that we have to be more tolerant on error.

Thanks,
 Eric.

**Comment by lminiero** [comment]
That sounds like a good idea, but it really depends on what tolerance means in this case, that is how it should be implemented. Feedback welcome!

**Comment by mtbramo** [comment]
Lorenzo,

The problem according to me is that as soon as you perform a media path change and RTP packets are send commonly every 20ms, you get more unluck to have an ICMP message. 
I doesn't understand that you use two different sets of balances concerning RTP and RTCP even if of course you want to keep the media. 

RTP and RTCP must be seen as a set, perhaps it will be possible to hangup the call only if we get ICMP from both fds (ICMP on RTP fd, check if RTCP fd is already close).

It's also possible to operate as soon as we doesn't get any RTCP packets (SR, RR) from distant.

**Comment by lminiero** [comment]
The rationale for different behaviour for RTP and RTCP is actually quite simple. We've seen several scenarios where the SIP peer would not open a port for RTCP, either because it didn't support it, or because it didn't care. As such, sending the RTCP packet to the peer would fail, but that doesn't need to cause the session to fail, as RTP is still working in that case. For RTP the approach was different, and we assumed that if there isn't anyone listening, then it probably means the peer went away. I'm all for making this more tolerant, but I'm interested in knowing how. We can't just ignore those errors, as they caused 100% CPU spikes and were the main reason we enforced this behaviour in the first place.

**Comment by lminiero** [comment]
Changed the code to only hangup when we get about 100 ICMP errors on RTP sockets in a row. Can probably be improved, but it does mean we're more tolerant of ICMP errors now. Errors on RTCP still result in the RTCP socket being closed right away.
