### ISSUE TITLE
[ice.c:janus_ice_setup_local:2919] Error getting list of interfaces...

### ISSUE THREAD

**Issue by zhengshengh** [meetecho/janus-gateway#1117]
Hello.
I am using videoroom.
But when there are about 50 users, Janus will crash after a few munites.
Just like the log below: 
![1](https://user-images.githubusercontent.com/6629532/34337301-39dc45ba-e999-11e7-95f8-5c595cd7b51b.png)

I have tried to do a search but there is no result at all.
What should I do?
Thanks.

**Comment by lminiero** [comment]
There's nothing we can do with screenshots.
Please do some proper [debugging](https://janus.conf.meetecho.com/docs/debug) instead and share the results via gist/pastebin/ix or others.

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Closing for lack of feedback and because we can't replicate. Feel free to reopen if it's still an issue with the latest code and you can provide info to replicate.

**Comment by Ben-Mark** [comment]
Reopening this issue since it occurred in several janus instances 
details:
- janus server was running on AWS EC2 c5.large instance
- janus had an average of 200 streams "load"

log - [](https://pastebin.com/d4Hkjvtz)

The error:
`[Mon Jan 14 15:07:12 2019] [31m[ERR][0m [ice.c:janus_ice_setup_local:3026] [7761206425404772] Error getting list of interfaces...`

out janus.cfg relevant fields are configured with the default:

ice_enforce_list = 172.16.20.25 ;  <- aws private machine's ip
ice_ignore_list = vmnet <- would be great to elaborate on this

Is this error happening due to my configurations?

Thanks in advance!

**Comment by lminiero** [comment]
We're not going to reopen an issue from more than a year ago: Janus is completely different. If you can replicate and have data to provide, open a new issue instead.
