### ISSUE TITLE
Janus crash on session destruction 

### ISSUE THREAD

**Issue by Computician** [meetecho/janus-gateway#117]
I believe this is when my rest connection disconnects from the API. 

[Here is the gdb printout](http://pastebin.com/JpUTtq9S). I am working on getting to happen again but with some janus debug outputs as well so that the issue can be narrowed. 

Possibly a session is timing out at the same time as the session is requesting to end?

**Comment by Computician** [comment]
There are definite issues with frees but I do not run into the issue if the publisher closes the page when the room is destroyed. There are issues specifically in janus_session_destroy(getting invalid reads during the ice destroy process). I will do a pastebin of the valgrind output.

**Comment by lminiero** [comment]
There may be some concurrent destroy attempts there, and may be related to some issues I noticed with the SIP plugin today. Specifically, it may be caused when a plugin asks for a PeerConnection to be closed, instead of having the user do so. That said, your valgrind dump seems to indicate that there's an attempt to destroy an ICE handle that was already destroyed before, when closing the session (e.g., user closed the page) and so it may indeed be a race condition. I'll try to reproduce this myself as well following the guide you wrote a few days ago, unless you have any more up-to-date steps I can follow to more or less reliably reproduce it?

**Comment by Computician** [comment]
Nothing new. Just have a room destroyed with individuals streaming to it and have ONE individual stay in the room and react how the videoroom example does and the other close the browser at the same time. This is the EXACT situation in which this occurred. 

Again, this SEEMS to effect those who stay in the room and handle the destruction in the same manner as the videoroom example page.

**Comment by lminiero** [comment]
Are you still able to replicate this issue, or was this fixed? My guess is that this was caused by a ```close_pc``` call where the plugin asked the core to tear a PeerConnection down: in some related issues this could cause Janus to crash, but this was made more robust in recent revisions.

**Comment by Computician** [comment]
I have not really tested it for some time as my focuses have been else where: dynamically combining room recordings into a single file, load balancing janus, creating an API wrapper/forwarder for SignalR.

I could test this later this week into next, however. Just will be some time :)

**Comment by lminiero** [comment]
Has it happened again in the meanwhile, in particular on recent Janus versions?

**Comment by Computician** [comment]
I have not ran into this again with the recent builds.
