### ISSUE TITLE
webrtc channel establishment fails most of the times when using dynamic turn credentials

### ISSUE THREAD

**Issue by mzanetti** [meetecho/janus-gateway#1200]
In our attempt to switch our setup to twilio as TURN provider we've switched to the dynamic TURN credentials mechanism given twilio only supports that.

While I did see connections coming up with that setup, it seems to be only a matter of luck. In most cases, it fails to establish the connection. I have the impression it is probably a race condition somewhere and the round trip time for fetching turn credentials and logging in to the turn server before proposing the candidate route on that server is taking too long and something times out along the way.

I have tried to speed it up by caching the dynamic credentials locally and configuring janus to request them on localhost from my cache but it still didn't really help.

An interesting observation is that if I use some working turn setup in the static config, everything works fine, but if I provide the exact same credentials using the dynamic TURN credentials api, it fails.

**Comment by mzanetti** [comment]
As far as I understand this situation, I believe instead of fetching the dynamic turn credentials on the fly whenever a connection is established, janus should fetch them directly after startup, do the test log-in and whatever needs to be done and cache them for the "ttl" value in the credentials. And refresh everything shortly before the ttl expires.

**Comment by lminiero** [comment]
Not sure what you mean by startup, here. Short-term credentials only make sense when we're trying to setup a specific PeerConnection, and so we obviously only request them when we know a new one is about to take place. Preloading them (how many?) out of context (when?) doesn't seem like a good idea to me.

I'm not sure it's the time it takes that makes it fail. How much can the delay be, 1-2 seconds? If an allocation using dynamically allocated credentials fails because we took 1-2 seconds more than expected to use them, the service is flawed (and would always fail for browsers with longer RTTs). Short term credentials usually have an expiry period that is way longer than that.

**Comment by mzanetti** [comment]
Ok, after quite some more debugging I have found a combination of issues and I have a working setup again:

1) The connecting client used a different turn server setup. I am not sure what exactly goes wrong, but it seems to not work most of the times if there are different TURN servers configured on janus and the client. Aligning them both on the old or new setup gets around this.

2) I am pretty convinced that there is indeed a timing issue in janus when it comes to dynamic TURN credentials. After resolving the above issue I have a 100% success rate now when I do pre-fetch and cache the turn credentials and supply them to janus instantly through localhost caching. In order to verify it's not an activation issue of the newly created credentials I precached the credentials but added a sleep timer before supplying the cached credentials to janus. with a 5 secs delay I have a pretty much 100% fail rate, with a 1 second delay I have a ~80% success rate and without delay at all it worked for 100% of the attempts so far.

If you are interested in the logs of those test runs, please let me know.

**Comment by lminiero** [comment]
If so, sounds like a libnice issue. You may want to use the latest master and see if it's still a problem.

**Comment by lminiero** [comment]
Any update on this? Have you tried libnice master?

Anyway, one thing I was thinking about is that we might add a new request in the Janus API to specify the TURN server and credentials to use for a handle, for all PeerConnections that will follow. This way, as soon as a PeerConnection is needed, that info can be used instead of whatever was configured statically in `janus.cfg`. The idea is that this would be dynamic, meaning you can change server and credentials multiple times during the lifetime of a handle (but they wouldn't have any effect until a new PeerConnection is created: i.e., won't have any effect if you change them *during* a call). Does this make sense, and would it elp with your prefetch scenario?

**Comment by lminiero** [comment]
@mzanetti ping :wink:

**Comment by lminiero** [comment]
I'll just assume that either the issue was fixed, or you don't care anymore. Closing.

**Comment by mzanetti** [comment]
Hey @lminiero 

I am sorry for the late reply... This is just one of my tasks and I have to cycle between them a bit, also I was on holidays.

Right now our setup is still running with the local cache. That seems to work rather well. Your proposal to supply the credentials through the api sounds good too. Seems cleaner than the current webserver providing credentials on localhost in plaintext.

On the other issue. After another debug session I traced it down to an IPv4 & IPv6 issue. I noticed things would go wrong more often if more IPv6 candidates are offered by the client. Enabling IPv6 support in Janus helped there (which I could do now given your fixes from earlier reports - Thanks for those btw :)

**Comment by ledaiduongvnth123456** [comment]
I have the same issue!
I was able to use twilio ICE server for janus by using TURN REST API to get info on one or more TURN services dynamically in janus.jcfg config file.
But when I apply the same ICE server for web client, it didn't work. I think it is a really big problem, because the ICE server affects hugely to the media quality. Any help please!
