### ISSUE TITLE
Can't turn off camera until after one connects

### ISSUE THREAD

**Issue by jidanni** [meetecho/janus-gateway#1203]
https://janus.conf.meetecho.com/echotest.html has same problem as
https://github.com/jitsi/jitsi-meet/issues/2737 .

**Comment by lminiero** [comment]
Not sure what the problem is. This demo is supposed to act as an echotest, and so assumes you'll want to use both microphone and webcam. If you don't like this in your own application, you can just remove the webcam consent request, or add some sort of checkbox/prompt to ask the user what they want to share before accessing it. All things that are very well possible with Janus: not sure why we should do it in demos that are just meant as examples of how to use other capabilities instead.
