### ISSUE TITLE
No statistics summary when session is terminated (handle detached)

### ISSUE THREAD

**Issue by PaddyOl** [meetecho/janus-gateway#1257]
This is a request for a Janus enhancement.

Statistics / counters (packet-received, packet-sent ...) for an active session (e.g. audio) are sent by event (event type 32 => JANUS_EVENT_TYPE_MEDIA).

It is possible to adapt the periodicity of these events ( stats_period in janus.conf), 
but today, there is no way to get statistics / counters summary for terminated session (detached handler).

When plugin (audio, video ...) got detached, an event should be sent containing the statistics summary for the terminating conversation.

I am not sure what is the best implementation:
- send a JANUS_EVENT_TYPE_MEDIA event containing the statistics summary ?
- send the statistics inside the plugin detached event ?
- make and send a new event type for statistics summary ?

**Comment by lminiero** [comment]
I was just about to answer you on the group, as a final delivery of those stats before hanging up turned out to be easier than I expected: https://github.com/meetecho/janus-gateway/commit/238d585a3e28909a4e30d693dffec67a6a2b34c5
This looks exactly as the other stats messages, so no change needed in receivers.
