### ISSUE TITLE
audiobridge heap-use-after-free when destroying session (in slightly older commit)

### ISSUE THREAD

**Issue by peffis** [meetecho/janus-gateway#1266]
I'm running some load tests on audiobridge and, when heavily loaded, it crashes with a heap-use-after-free issue reported with libasan: https://pastebin.com/bRyYiSHv

It seems to be that the encoding thread could still be processing some packets after the opus encoder has been destroyed when tearing down the session.  

Unfortunately, the libasan output, is from a now older commit of Janus (2cd0a26f89758c2d45a464e68bc20bb02b434b65) and the line numbers are unfortunately off even more because of some inserted debugging code but janus_audiobridge.c:4268 (where it is using the opus encoder) in the asan output would correspond to (now in current master) line: https://github.com/meetecho/janus-gateway/blob/bbaf37256aaf3bee5b502b797b699efc41af077d/plugins/janus_audiobridge.c#L4340 

and the line janus_audiobridge.c:2925 (where it is destroying the encoder) would correspond to: https://github.com/meetecho/janus-gateway/blob/bbaf37256aaf3bee5b502b797b699efc41af077d/plugins/janus_audiobridge.c#L2992

I apologize for bringing up an issue found in a commit from end of March, but from looking at the code in current master there is no obvious (to me at least) change that solves this issue - particularly something related to stopping the thread processing the audio chunks for the session when destroying the session or using some lock to protect the encoder. I also did not see any older issues discussing this (except for a dead-lock issue which is rather the opposite than the race condition seen here) but correct me if I'm wrong and it would be wise to try and upgrade this failing node rather than trying to solve the issue.

**Comment by lminiero** [comment]
Since more than two months passed (and as you may have noticed we tend to commit a lot of stuff :smile: ), please try with master and provide a trace from there if it still crashes.

**Comment by peffis** [comment]
Yes, I'll do that. You may close this issue and I'll come back with a new issue based on latest master instead. 

But from looking at the latest code in latest master it seems like the logic for destroying the encoder while it is being used is the same: 
https://github.com/meetecho/janus-gateway/blob/bbaf37256aaf3bee5b502b797b699efc41af077d/plugins/janus_audiobridge.c#L2983-L2990

And then
 https://github.com/meetecho/janus-gateway/blob/bbaf37256aaf3bee5b502b797b699efc41af077d/plugins/janus_audiobridge.c#L4337-L4341

From my understanding the code above will NOT always prevent destroying the encoder if the thread using it will (just after the check for participant->working) set participant->working to TRUE and start using the encoder. There is an interaction also with the flag "participant->active" which is set to FALSE before tearing it down (and also checked for in the participant thread) but my feeling is that, with enough load, there could still be the same race condition in the new code as with the old code because the logic for preventing it is the same.

**Comment by lminiero** [comment]
No need to close the issue, we can update this one, especially if it turns out to be still there.

**Comment by lminiero** [comment]
Can you try adding an `&& session->started` to the check before `opus_encode`?

    if(participant->active && participant->encoder && session->started) {

It shouldn't be needed as it's in the check in the line before that, but if it's a race condition due to a overloaded server it's a safer check to make again, since we set `session->started = FALSE` much sooner than we do `participant->active = FALSE`.

I'm still thinking of better ways to address this in a more proper way. I thought of joining the participant thread, but that's not an option, as the thread lives until the handle is gone: this means that if you create a PeerConnection, tear it down, and then create it again for the same plugin session, the same thread is re-used. Locking is something I'd rather avoid as well.

**Comment by peffis** [comment]
I will try this and get back to you. I did something similar - basically moved out the participant->working = TRUE, participant->working = FALSE interval to cover the whole loop of the participant thread. This seems to have decreased the likelyhood for this crash a bit. Instead it crashed in the opus decoder at even higher cpu usage - for the same reason. It is protected in a very similar manner with a check for participant->working == TRUE and so on. So I think you can, by checking the flags like this, move the likelyhood of the race condition slightly, but it is not a true fix for the issue. 

I thought of joining or locking as well but, as you say, the former is not an option and the latter would decrease performance. Perhaps there is some scheme where you can set these flags in a different order to avoid the race, or perhaps have a dedicated flag for when the session is being destroyed which would tell the participant thread to shut down and then continue when it has done so. 

But I'll try your suggestion...

**Comment by lminiero** [comment]
@peffis can you let me know if the above commit fixes things for you? It changes some properties by turning them atomic, so that we can make atomic changes and checks on them. For the specific case that was breaking for you, for instance, it checks if the atomic change from 0 to 1 succeeds: considering both encoding and destroying the encoder do the same thing (try to pass from 0 to 1, and finally set to 0), it basically acts as a "lightweight" lock (hopefully, at least).

I couldn't replicate the issue before so I can't check if this fixes things for good or not. Looking forward to your feedback on that: feel free to close if you believe this fixes it.

**Comment by peffis** [comment]
I'll try that and get back with results...

**Comment by peffis** [comment]
I've been running it now for some time under heavy load and I have, with this patch, not yet been able to reproduce the race condition. This is of course not a guarantee that the race condition is truly gone - perhaps we have just pushed the likelihood of a race outside the scope of what my test can produce - but I'll close this for anyway. Thanks!
