### ISSUE TITLE
Libwebsocket 3.0.0 error

### ISSUE THREAD

**Issue by vahidov** [meetecho/janus-gateway#1267]
If I'm using libwebsockets release 3.0.0 - don't work websockets. (Trying last libwebsocket master - the same)

On client ` VM97185:164 WebSocket connection to 'wss://**:8989/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET`

In log only 
```
[WSS-0x71fdba2bb7b0] 71 ((null))
[WSS-0x71de86f3b7b0] 71 ((null))
```

Enviropment
Janus in docker with `network_mode: "host". `
```
debian:jessie

ENV LIBWEBSOCKETS_VERSION=3.0.0
ENV JANUS_VERSION=0.4.1
ENV USRSCTP_VERSION=0.9.3.0
ENV LIBSRTP_VERSION=2.2.0

git clone https://github.com/warmcat/libwebsockets.git -b v${LIBWEBSOCKETS_VERSION} /usr/local/src/libwebsockets \
    && cd /usr/local/src/libwebsockets \
    && mkdir /usr/local/src/libwebsockets/build \
    && cd /usr/local/src/libwebsockets/build \
    && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" .. \
    && make \
    && make install \
```

P.S. With libwebsockets release 2.4.2 work as expected - fully normal.

**Comment by lminiero** [comment]
I don't know if they changed API in 3.x: my Fedora still ships 2.3.x. Anyway, @atoppi told me 3.x is working for him. I noticed you mentioned port 8989, which means you're probbly trying the secure websockets server: have you tried if it works as expected with plain websockets instead? If so, it might be related to WSS, rather than an incompatibility with the new version itself.

**Comment by vahidov** [comment]
Yes, I'm trying plain ws - didn't work with the same behavior.

FYI: Host machine on CentOS 7.3.1611.

**Comment by lminiero** [comment]
Then you should try and enable libwebsockets debugging, and see if you can spot anything weird. Nothing I can help you on, I'm afraid, since as anticipated I have never used that version of the library. Looking at the [changelog](https://github.com/warmcat/libwebsockets/blob/v3.0.0/changelog) I can't see anything obvious that might cause it.

**Comment by vahidov** [comment]
@lminiero its surprisingly, but same docker-image works fine on Amazon ami and didn't work on CentOS.
I will make same test on others hardware and make report

**Comment by lminiero** [comment]
This seems to suggest there's no compatibility problem between Janus and libwebsockets 3, but most likely an issue with CentOS.

**Comment by lminiero** [comment]
Closing as it seems to be working for us.

**Comment by jswirl** [comment]
@vahidov Hi, did you manage to find out what was going on? Ran into the exact same issue on CentOS today, and I'm running Janus from a Docker Alpine image.
