### ISSUE TITLE
videoroom plugin: no video recording when renegotiating from audio to video call

### ISSUE THREAD

**Issue by marcino1** [meetecho/janus-gateway#1281]
I join the room with audio only and then renegotiate call to add video, after that only audio is recorded, the video file isn't even created. Everything works correctly when I join the room with video and then start renegotiating to audio only and back to video.

**Comment by lminiero** [comment]
Sounds like a thing we fixed several weeks ago. Are you on master?

**Comment by lminiero** [comment]
Oh, you meant recording, not the video support itself. In that case you're probably right: you need to start recording for video yourself, the code doesn't do it automatically when you upgrade the session.

**Comment by marcino1** [comment]
Ok. So how can I start recording myself? I tried to send `record:  true` in `configure` request from publisher when renegotiating, but it didn't help.

**Comment by lminiero** [comment]
Yeah, looking back at the code we set a global property when starting and stopping recordings, and we only do something when there's a transition. In your case, since recording was marked as active the first time, when you call it the same time with a `record:TRUE` it's ignored as the property was true already.

I'll have to think about how to modify the code so that it can be more aware of individual stream recording as well.

**Comment by lminiero** [comment]
One easier solution might be to automatically enable the recording of video if video is added later on and audio is already being recorded (and same thing if it's the other way around for instance). I'll think about it.

**Comment by lminiero** [comment]
The above commit fixes it for me: it automatically starts recording media added after a renegotiation, so video in your case. Let me know if that's still not working as expected for you.
