### ISSUE TITLE
RTP Input for Audiobridges (Enhancement)

### ISSUE THREAD

**Issue by austinmarkus** [meetecho/janus-gateway#1360]
It would be really useful for me to have the ability to input RTP  to an audiobridge in a similar manner to how there is RTP output via the  forwarder. The basic request is to have the ability to send an Opus encoded RTP stream from a non-browser such that it could be heard the members of the bridge. 

If there is already a way to accomplish this that I have overlooked I'm open to suggestion.

Thank you for your amazing project.

**Comment by lminiero** [comment]
This is currently unsupported in the AudioBridge. I can add it to the TODO list, but I honestly don't know when I'd be able to work on that (busy times!). PRs always welcome, of course!

An easier way to accomplish the same thing with what's available today would be by taking advantage of the Streaming plugin: create an audio-only Streaming mountpoint, have your users create a PeerConnection with that (e.g., just for receiving announcements), and anytime you have external RTP to send you send it there. Suboptimal, of course (you need two PC instead of one) but solves your requirement without touching the code.

**Comment by lminiero** [comment]
FYI, we recently added support for playing static Opus files in the AudioBridge in #2088, so that should already help with that you need. Actual support for incoming RTP streaming will take longer, as it's quite low in our priority list right now.

**Comment by lminiero** [comment]
@austinmarkus please see #2464.

**Comment by austinmarkus** [comment]
Thank you!
