### ISSUE TITLE
Atomic reference counter for data structures

### ISSUE THREAD

**Issue by Computician** [meetecho/janus-gateway#141]
This is not an "issue" but I have noticed that race conditions with things being destructed too early is pretty common in this project. An atomic variable to signify destruction is already in the system but there should also probably be an atomic reference counter so that objects are not destructed while they are in use. Over use of mutex locks will slow down the system and using the delayed clean that is used now seems to only mitigate the issue but is reliant on the CPU being responsive enough for all the threads to run before destruction is done and uses a static "magic" destruction delay time.

These are just some ideas. Before I started writing on it, I wanted to see if this is a road we would want to go down or if it is work that is already being done.

**Comment by lminiero** [comment]
Those are very good points, and I agree some improvements with respect to that would help. This is made harder by the very nature of WebRTC, which is very dynamic and unpredictable in terms of how soon things can be considered ready or not (just see ICE and DTLS). That's why sometimes locking is unavoidable, for instance, or why I eventually chose to use threads in some parts to avoid locking being counterproductive (see, outgoing data thread).

We're currently focusing on solving some other key issues within the platform and have our hands full, so if you have any idea on how to refactor some of the parts you mentioned, feel free to draft something (e.g., for one of the features) and I'll join to help you on that as soon as I can.

Thanks!

**Comment by Computician** [comment]
The direction I was thinking, was to have a "janus_object" (similar to GObject, though not as fully formed as I don't think Janus needs all those features) that each of the objects that need to be MT safe will "inherit". Thus being able to utilize the underlying reference counter and provide a destruction function pointer so that when reference count hits 0, the destruction function will be called.

**Comment by lminiero** [comment]
I'm not very familiar with GObject so I don't know if it actually is too _bloated_ for our purposes or not. I guess a reference counter might indeed help, although I'll have to check whether there are some use cases where this might not be enough. Keep me posted on this!

**Comment by Computician** [comment]
Well, honestly, since janus is already linking against Glib, just using GObjects may make the most sense. I have been poking around for candidates for the rework but a good first step would be utilizing references to assure existence of libnice agents.

**Comment by lminiero** [comment]
Started working on this in #403 so check that for updates.

**Comment by lminiero** [comment]
Closing as we have the PR as a reference (no pun intended!) for that.
