### ISSUE TITLE
Wrong parameter name for api key in TURN server REST API handling

### ISSUE THREAD

**Issue by pdragozov** [meetecho/janus-gateway#1416]
According to the proposed spec at https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00 the API should expect 3 parameters: **service**, **username** and **key**.
The _janus_turnrest_request_ function in **turnrest.c** seems to be sending the key as **api** instead of **key**.

**Comment by lminiero** [comment]
That draft is only an indication, there is no mandate for the API to look exactly like that (especially considering that draft has expired a long time ago). Since there are people that may be using this in production right now, I won't rename the property: what I can do, though (if reallly needed), is send them both.

**Comment by lminiero** [comment]
Sending them both now as anticipated.

**Comment by joe-average-user** [comment]
Well, still something missing:

Jun 04 12:12:26 host janus[126161]: [5205084005522600] Setting ICE locally: got OFFER (1 audios, 1 videos)
Jun 04 12:12:26 host janus[126161]: [5205084005522600] Creating ICE agent (ICE Full mode, controlled)
Jun 04 12:12:26 host janus[126161]: Sending request: http://127.0.0.1:8081/?service=turn&api=<apikey>&key=<apikey>
Jun 04 12:12:26 host janus[126161]: Got 24 bytes from the TURN REST API server
Jun 04 12:12:26 host janus[126161]: Must supply a username.

with debug=7. It seems the request contains no "username". Is this a config problem or where should the usename come from?
