### ISSUE TITLE
Support higher sampling rate in Audiobridge plugin

### ISSUE THREAD

**Issue by willbarrett** [meetecho/janus-gateway#143]
We're finding that the audio quality in the Audiobridge plugin leaves something to be desired, even at the highest complexity setting. This is noticeable when compared with the audio quality in the videoroom plugin. Would it be possible to add support for higher audio sampling rates?

**Comment by lminiero** [comment]
The videoroom plugin does no processing/transcoding, and so what you get there is what the browser originated in the first place (I think 48kHz, not sure though). The AudioBridge mixes and decodes/encodes, and the higher the sampling rate, the higher the CPU requirements will be per room, as you'll need 48kHz mixing which is much more intensive; the same applies to encoding such streams, even though at a lower extent as complexity plays a higher role there.

This is why we came to such a compromise when we first started working on the plugin: a trade-off between computational requirements and a reasonable quality (16kHz=wideband).

I guess that working on higher mixes is doable, I'm just not sure whether it will make the plugin scalable when such a profile is used and numbers increase. I'll have a look at the code we have now to estimate the effort needed for such an enhancement.

**Comment by tommoor** [comment]
Hey @lminiero totally understood, I think for us we'd like to have the *option* to go higher quality as wideband still sounds muffled to my ears - at this point lower number of people per server is fine if it makes the experience awesome :smile:

**Comment by lminiero** [comment]
Makes sense, I'm looking into what we can re-use and make configurable to switch from 16kHz to one of the other options (even 8kHz for those who love the 90s :-) )

**Comment by lminiero** [comment]
The referenced commit adds support for all the missing sampling rates: the default if you omit it when creating a room (either via config or API) is still 16000, but 8000, 12000, 24000 and 48000 are now supported as well. I've tested successfully the 48kHz missing, didn't have the time to look into the others so you may want to do that yourself if needed.

Just a heads-up, though. The ```changeroom``` request also addresses potentially differing sampling rates when moving from one room to another, and recreated the Opus encoder/decoder accordingly, but since the previous PeerConnection is re-used, the browser may take into account the ```maxplaybackrate``` value it got via SDP previously. So, if you were in a 16kHz room and got a ```maxplaybackrate:16000```, the same SDP feedback will still apply for the browser even when you switch to a 48kHz room and update your encoder accordingly, which means the browser _may_ send (or keep on sending) 16kHz audio because it assumes the peer won't be able to reproduce anything that goes beyond that. That said, all Opus-related SDP fields are assumed to be suggestions rather than mandatory stuff, and I did notice different audio quality when switching from one room to another and vicecersa, so this may be a false problem. You may want to play with this as well just to be sure it's ok.

Let me know if this works for you and I'll close the issue.

**Comment by willbarrett** [comment]
Hey Lorenzo,

So far so good. We're going to keep testing it, but we can re-open the issue if there are further problems. Thanks for making this work for us!
