### ISSUE TITLE
Segfault in janus_flags_is_set

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#1495]
The segfault happened at
https://github.com/meetecho/janus-gateway/blob/4f2093bbda27528a17c20d1693de9a1d6c221799/utils.c#L115
Here is [the backtrace](https://gist.github.com/uxmaster/04deb3123d097e6a92fe551211865c13) and [the log](https://gist.github.com/uxmaster/725f31444c0098bccbb307b0a34ced88).

**Comment by uxmaster** [comment]
I'll try to run it with libasan.

**Comment by lminiero** [comment]
@uxmaster any update on libasan?

**Comment by uxmaster** [comment]
Not yet. The crash didn't happen again.

**Comment by lminiero** [comment]
Mh, looking at the backtrace again, looks like it originates in a `janus_rtc_mixer_thread` that is definitely not ours. Probably something broken in your code? Closing, feel free to reopen if you can replicate in existing plugins.

**Comment by uxmaster** [comment]
It rather looks like something broken in the core, since plugins (mine as well) do not touch flags.

**Comment by lminiero** [comment]
My guess is that you're pushing RTP with `relay_rtp` after the handle was destroyed and the PeerConnection torn down, so after a `hangup_media` and probably a `destroy_session` too.

Since we don't have access to your code and we don't debug third party plugins, I can't help unless you can replicate on one of the existing plugins or find libasan info.
