### ISSUE TITLE
"Not a recording session, can't update" in Firefox 65

### ISSUE THREAD

**Issue by renagaev** [meetecho/janus-gateway#1513]
Hi. I'm trying recordplay demo (https://janus.conf.meetecho.com/recordplaytest.html) in Mozilla 65.0.
First video records successfully but when I try to record the second video it fails with "Not a recording session, can't update".

How to fix it?

**Comment by renagaev** [comment]
@lminiero, could you help with this?

**Comment by lminiero** [comment]
Probably the PeerConnection was not closed, and so the "play" is trying to reuse the same PeerConnection as before instead of creating a new one: since that one was recvonly and used for recording, though, it can't be updated and you get the error.

Not sure why the PeerConnection is not being closed in your case, but it might be easy enough to force a hangup from the web page when the recording stops (I can't remember if the plugin tries to force one, I'll have to check).

**Comment by lminiero** [comment]
Should be fixed now: it works as expected for me in Firefox 65.
