### ISSUE TITLE
Headers on MacOS in Janus.useDefaultDependencies (janus.js)

### ISSUE THREAD

**Issue by dimidiam** [meetecho/janus-gateway#1532]
The Janus.useDefaultDependencies headers in the janus.js are not working with safari.

working (with safari and chrome) code below:
Janus.useDefaultDependencies = function (deps) {
.
.
.

httpAPICall: function(url, options) {
			// var fetchOptions = {
				// method: options.verb,
				// headers: {
					// 'Accept': 'application/json, text/plain, */*'
				// },
				// cache: 'no-cache'
			// };
			var fetchOptions = {method: options.verb, cache: 'no-cache'};
			// if(options.verb === "POST") {
				// fetchOptions.headers['Content-Type'] = 'application/json';
			// }

.
.
.
return fetching;
		}
	}
};

**Comment by lminiero** [comment]
I don't see how that's supposed to work, since you're basically dropping the `Accept` and `Content-Type` headers. I'm not aware of any issue with Safari (IIRC we tested recently with success) so it looks more like an issue in your setup. If you can investigate more on why using fetch with Safari causes you issues happy to help, but I'm not going to apply the fix you suggested as it is, sorry.

**Comment by lminiero** [comment]
Maybe something CORS related?

**Comment by dimidiam** [comment]
I have to say that I am still on 0.52 version but I dont think the janus.js changed since then.
I dont know about the server implementation though.
On an older janus.js I have checked there arent any headers specified.

The strange thing is that it occurs not allways in the first, but in one of the first 3 posts of the session.
So some posts get through.
The error in the janus logs is unspecified.
On safari I am getting a connection lost error,

**Comment by lminiero** [comment]
You may want to check under what circumstances Safari decides to drop an outgoing request, especially when it contains a `Content-Type` or `Accept` header. From the very brief search I did it could be related to CORS settings, but I didn't dig deeper than that. If you investigate the possible issues (I don't have a Safari instance to play with myself) it might help us figure out a solution, otherwise nothing I can do, sorry.

**Comment by lminiero** [comment]
You may also want to open a post on our group, just to see if any other Janus user ever encountered the same issue, and if so how they solved it: https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by lminiero** [comment]
Any update on your research?

**Comment by dimidiam** [comment]
No nothing yet.Still looking.
    On Monday, April 1, 2019, 12:06:11 PM GMT+3, Lorenzo Miniero <notifications@github.com> wrote:  
 
 
Any update on your research?

**Comment by lminiero** [comment]
I assume we can consider this a non-issue. Closing.
