### ISSUE TITLE
Crash on switch from "empty" handle

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#1541]
If feed leave but handle not destroyed on client side. If you try to do switch request Janus crash.
https://pastebin.com/WHW0CNUF

**Comment by lminiero** [comment]
Is this master of unified-plan? Looking at the snippet it looks like it's the latter.

Please, don't forget to reference the unified-plan when you create issues for that, otherwise it's very hard for me to track things and map them properly.

Doing it now for you: #1459

**Comment by lminiero** [comment]
Any chance you can get a libasan dump of when it crashes?

**Comment by amnonbb** [comment]
#1459 
This? :-|
https://pastebin.com/atQtGUFf

**Comment by lminiero** [comment]
No need to reference the PR again, once is enough :smile: 

Yep, that's the libasan trace, even though it doesn't seem to provide any useful information. Do you have some quick steps that I can follow to replicate consistently? I'm out of office today, but I'll have a look tomorrow. Thanks!

**Comment by amnonbb** [comment]
> No need to reference the PR again, once is enough 😄

Sorry, im not hard git worker :smile:

> Yep, that's the libasan trace, even though it doesn't seem to provide any useful information. Do you have some quick steps that I can follow to replicate consistently? I'm out of office today, but I'll have a look tomorrow. Thanks!

We start from at least 2 subscribers
attach 1st
switch on 2nd
2nd leave
switch 1st - here :boom:

**Comment by lminiero** [comment]
It should be fixed in the above commit, or at least I can't replicate it any more: the patch also solves a couple of other problems and crashes that were uncovered as part of the same tests. Notice that the fix now means that, although `switch` almost always does not trigger a renegotiation, it might in some cases, and your scenario is one of them: in fact, switching an stream inactive stream to a new source needs a new offer/answer to turn that inactive to sendonly again.
