### ISSUE TITLE
Plugin configuration.

### ISSUE THREAD

**Issue by gatecrasher777** [meetecho/janus-gateway#160]
Not an issue, but maybe an enhancement.  It would be very nice if one could specify in the janus.cfg file which plugins to load at start up.  

On a clean installation one can specify which plugins to compile (i.e. with a rather verbose ./configure command line). Alternatively, one can compile all and remove plugins from the lib/plugins installed location. Except that they will reappear if you git pull and remake. 

So it seems to me the cleanest solution would be a mechanism for enabling/disabling them in the janus.cfg.

**Comment by lminiero** [comment]
Good point, I'll add this to the todo list.

**Comment by voordev** [comment]
Could we have an option to also specify only what plugins to start?
Also,

Since you have to specify the exact filename you get issues on local development and production server since if environments are different ( for example osx on dev and unbuntu on production) you can a different extension.

Something like:
```
disable = all
enable  = recordplay
```
Would be great
