### ISSUE TITLE
RTSP regressesions for video streaming

### ISSUE THREAD

**Issue by Ext3h** [meetecho/janus-gateway#1629]
Per-stream attributes parsed from SDP / SETUP response got mixed up in a couple of locations since f2d6ae900cf6ba6d37147425ed4fccaed79cc845 (unified plan):

In `janus_streaming_create_rtp_source`:

> `stream->codecs.rtpmap = source->rtsp_vcodecs.rtpmap ? g_strdup(source->rtsp_vcodecs.rtpmap) : g_strdup(artpmap);`

> `stream->codecs.fmtp = source->rtsp_vcodecs.fmtp ? g_strdup(source->rtsp_vcodecs.fmtp) : g_strdup(afmtp);`

Stream attributes parsed for audio from SDP are also applied to video. Bug is masked if configuration specifies an override.

Packing the two sets of local variables in a struct would probably be appropriate with regard to preparing the code for multi-stream support / preventing future mix-ups / #1621.

> `janus_streaming_rtsp_latch(stream->fd[0], source->rtsp_ahost, stream->remote_port, &remote);`

Audio remote host is wrongly used for all streams. Remote host for latching should be a per stream attribute (member of `janus_streaming_rtp_source_stream`, instead of `janus_streaming_rtp_source`).

**Comment by lminiero** [comment]
Thanks for spotting these! Adding an explicit reference to #1459 so that it appears there. I just pushed a commit that fixes both things. I haven't changed anything in the code, just fixed the inconsistencies you highlighted: what you suggest will probably only happen after we merge the `unified-plan` branch, as other enhancements: right now my focus is on the main refactoring of everything else.
