### ISSUE TITLE
janus-pp-rec audio yields an opus file with (incorrect) exceptionally long length

### ISSUE THREAD

**Issue by evictor** [meetecho/janus-gateway#1696]
This is built from janus-gateway 0.6.2. Most janus-pp-rec use cases are working for us but found an oddball that generated an opus file that yields an abnormally long apparent duration when probing with ffprobe or ffmpeg (i.e. duration > 1 day long!). The audio mjr is only ~90 kB and when limiting muxing with associated mp4 video to the video's length, the audio track is actually fine

I am not familiar with opus protocol but maybe the length of the stream is written incorrectly or something in this weird case?

Please LMK what other info I can provide to help track down the cause.

**Comment by lminiero** [comment]
Please try with Janus master, we don't debug older versions. That said, this can happen when there are out of order packets at the very beginning or anomalies like that. The post-processor has flags to skip some of them, or other things, so that's what you need to play with. Closing as not a code issue.
