### ISSUE TITLE
None of the demos are working.

### ISSUE THREAD

**Issue by plasmashadow** [meetecho/janus-gateway#173]
http://janus.conf.meetecho.com/ i went to above link to check out the demos but none of the demos are working.

**Comment by lminiero** [comment]
Please report such issues on the meetecho-janus Google group instead of opening an issue here, as it's not an issue with the code.

The demos are working for me: I guess your issue is related to connectivity problems, as we don't have a TURN server configured for the demos which means they may not work in particularly problematic environments.
