### ISSUE TITLE
Janus v0.7.3 segfaults in g_mutex_lock/janus_videoroom_setup_media

### ISSUE THREAD

**Issue by samnf** [meetecho/janus-gateway#1745]
Hi,
We're getting regular segfaults, on average one per janus host per day, but sometimes a host will crash a few times within half an hour. 
https://pastebin.com/rfiAL9gg 
We're using the v0.7.3 janus release, libsrtp 2.2.0, libwebsockets 3.1.0, libnice 0.1.16, on ubuntu 16.04

There's nothing i've noticed indicating an imminent crash in the logs. Any ideas on what else I could check? Thanks!

**Comment by samnf** [comment]
I discovered the nice_debug flag in the config, i enabled it and caught this shortly after: 
https://pastebin.com/WnR6LdBV

**Comment by samnf** [comment]
I've deployed a couple of canary janus hosts that are running on Ubuntu 18.04 (upgraded from 16.04) and using the 'master' branch of libnice after reading a few other tickets. 
libnice requires glib >= 2.54, hence the upgrade to Ubuntu 18.04 (been meaning to do that anyway).

**Comment by samnf** [comment]
Unfortunately I just hit a segfault again on one of the updated hosts, looks like the same issue. 
https://pastebin.com/J9Rp41CS

**Comment by atoppi** [comment]
Hi @samnf,
the commit [30dcef96debde7c8f9a8f4f193c27b421345d0b0](https://github.com/meetecho/janus-gateway/commit/30dcef96debde7c8f9a8f4f193c27b421345d0b0) should fix this.
Please test the changes and let us know if everything works as expected now.

**Comment by samnf** [comment]
Awesome, thanks! I've cherry picked that into v0.7.3 and am building and testing now.
Based on your commit, we're somehow getting into a state where (participant->room) is false. Any thoughts on what that means or why/how we're getting into that state? Will the janus_videoroom_setup_media call fail?

**Comment by atoppi** [comment]
This happens when a race condition occurs between `janus_videoroom_setup_media` and `g_clear_pointer` in either:
- [janus_videoroom_destroy_session](https://github.com/meetecho/janus-gateway/blob/30dcef96debde7c8f9a8f4f193c27b421345d0b0/plugins/janus_videoroom.c#L2422) 
or 
- [Janus is requested to destroy a room](https://github.com/meetecho/janus-gateway/blob/30dcef96debde7c8f9a8f4f193c27b421345d0b0/plugins/janus_videoroom.c#L3185)

In practice the root of the issue is a user session teardown or room destruction while a participant session is being created.

The call to `janus_setup_media` will not fail, the fix will just avoid to notify the other room participants of a new user joining.

**Comment by lminiero** [comment]
Can this be closed then?

**Comment by samnf** [comment]
Yep! We've been running it in prod for over a week now, no segfaults! Many thanks @atoppi
