### ISSUE TITLE
Oops: Still cleaning a previous session

### ISSUE THREAD

**Issue by MauricioNoguera** [meetecho/janus-gateway#1800]
Hi All,
Janus (WebRTC Server) v0.7.5
Making WebRTC to SIP call.
Sip Server: CISCO UCM v 10.5
I am facing a problem on the Janus server. When an incoming call is missed or rejected subsequent incoming calls result in "busy here" and subsequent outgoing calls result in "Opos: Still cleaning a previous session" and the call doesn't go out.
Enabling the log to debug level 7, the error can be found at:

[7294649613380871] There's a message for JANUS SIP plugin
[7294649613380871] Still cleaning up from a previous media session, let's wait a bit...

I have founf that this happens after the second missed call, If  I miss one call and dial out, works, but from the second missed call the problem appears.

I have waited for minutes after the problem but the result is the same.
I have seen on a SIP trace that INVITEs from SIP Server don't have SDP, SDP comes with 200OK, I dont know if that bothers Janus logic.

Please find the Janus log attached:
And the client javascript log attached:

Any help will be appreciated
Regards, 
Mauricio Noguera
[ErrJanus.log](https://github.com/meetecho/janus-gateway/files/3682123/ErrJanus.log)
[LogCTiControl 20191002.txt](https://github.com/meetecho/janus-gateway/files/3682126/LogCTiControl.20191002.txt)

**Comment by lminiero** [comment]
I'm pretty sure it's caused by the offerless INVITEs, as we fixed a scenario like this last summer for regular calls, and it's been tested extensively. We'll try to replicate the issue on our end. In the meanwhile, can you share the content of an Admin API query to the affected handle, especially the plugin-specific details? They'll contain info like some internal flags we use for tracking the call state, and so may tell us if one of those is in the wrong state.

**Comment by lminiero** [comment]
@MauricioNoguera can you try adding these lines:

```
	janus_flags_clear(&handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_NEW_DATACHAN_SDP);
	janus_flags_clear(&handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_READY);
	janus_flags_clear(&handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_CLEANING);
	janus_flags_clear(&handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_HAS_AGENT);
```

before this line here:

https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1369

and recompiling Janus to try again? My guess is that the SIP plugin is calling `close_pc` to close a PeerConnection, but since the PeerConnection never started (`agent_started` is `FALSE`), we set the `cleaning` flag in the core, but never clear it. This is what causes your problem, as the "still cleaning" log line you see is a core thing.

**Comment by lminiero** [comment]
@MauricioNoguera any update on my question above?

**Comment by MauricioNoguera** [comment]
Hi Lorenzo,
I have recompiled the code adding the lines you suggested. However I am yet unable to test it on my lab due to I have to use a Cisco Sandbox and I am limited to use the interface as stated on the Issue Operation not permitted on vpn network (#1797).
I think I have to get rid of that issue before atempting to test the fix.

**Comment by lminiero** [comment]
I applied the fix I suggested, as I believe that was the cause of the issue. Feel free to reopen if you can get your testbed running again and can still replicate the problem.
