### ISSUE TITLE
Runtime error with call to Janus constructor() in file janus.js

### ISSUE THREAD

**Issue by TekuConcept** [meetecho/janus-gateway#1912]
/html/janus.js: `function Janus(gatewayCallbacks)`

Line 432 to 435, the developer checks if `gatewayCallbacks` is defined and that success, error, and destroyed are valid child function callbacks. However, these checks are performed _after_ the error callback is invoked on lines 424 and 428.

(Also, line 431 is always going to be true because of the conditional check on line 423.)

**Comment by lminiero** [comment]
Not at the office so can't check. I'll have a look tomorrow.

**Comment by lminiero** [comment]
The above commit should fix it, thanks for spotting the problem! As to the log line with `Janus.initDone` always being `true` at that point, I think the idea at the time was that `initDone` might have been something different (e.g., a timestamp), rather than a boolean: even if it is only a boolean now, I don't see any harm in keeping the log line as it is.
