### ISSUE TITLE
a deadlock when janus_videoroom_destroy_session

### ISSUE THREAD

**Issue by mivuDing** [meetecho/janus-gateway#1982]
Hi, I found a possible deadlock when "publisher A" enter janus_videoroom_destroy_session, and "subscriber B" subscribe "publisher A" at the same time. The detail step can be seen by the attach.
![videoroom_deadlock](https://user-images.githubusercontent.com/50724784/76203910-61fbcc00-6232-11ea-8fcd-5b64a4f93911.png)
How to solve the problem?I want to unlock the sessions_mutex before destroy publisher, is it OK?
![modify](https://user-images.githubusercontent.com/50724784/76204365-3af1ca00-6233-11ea-9b43-37e82a90fa6a.png)
Could you do me a favor? Thanks very much!

**Comment by lminiero** [comment]
Good catch, that's indeed a nasty deadlock that could happen under rare circumstances, due to the fact that the mutexes may be locked in different order there. Your proposed fix sounds reasonable to me, since the main purpose of `sessions_mutex` is protecting the `sessions` hashtable, and other resources should be protected by other locks after that. If you found an easy way to replicate the issue, you can check if you notice any regression there.

Of course, a pull request with this fix would be welcome, especially since it would give you proper credit for the patch! If you want me to do the commit instead, please let me know.

**Comment by mivuDing** [comment]
Thanks for your reply and suggestions!  It is very hard to replicate the issue! The janus server is running nearly one month, and the deadlock only occurred twice. 

I will take my proposed method and observe it for a period of time. I would tell you the result if it really take effect and has no side effect.

Of course if you get a good ideas, it is my great pleasure if you let me know, thank you very much!

**Comment by mp16** [comment]
It can explain my problem described here https://github.com/meetecho/janus-gateway/issues/1974#issuecomment-595707859 few days ago, where Janus is still accepting connection, but no more data are send.

Since Janus run with gdb, and since I had this bug few minutes ago, you gave me the idea to dump all threads: https://pastebin.com/xTgfkRjA (built from commit 9386afb8f812aa6864b82aea64a8fb1c7ccadcfa)

47 threads are stuck in janus_videoroom_hangup_media: https://github.com/meetecho/janus-gateway/blob/9386afb8f812aa6864b82aea64a8fb1c7ccadcfa/plugins/janus_videoroom.c#L5138

6 threads are stuck in janus_videoroom_slow_link: https://github.com/meetecho/janus-gateway/blob/9386afb8f812aa6864b82aea64a8fb1c7ccadcfa/plugins/janus_videoroom.c#L4990

1 thread is stuck in janus_videoroom_handler: https://github.com/meetecho/janus-gateway/blob/9386afb8f812aa6864b82aea64a8fb1c7ccadcfa/plugins/janus_videoroom.c#L5633

1 thread is stuck in janus_videoroom_create_session: https://github.com/meetecho/janus-gateway/blob/9386afb8f812aa6864b82aea64a8fb1c7ccadcfa/plugins/janus_videoroom.c#L2405

I think it's related to this issue because it's also in the videoroom plugin, and related to the session mutex.

So, a fix is more than welcome because I had the issue friday, I have it also today... it starts to be anoying. I hope that you will push soon.

**Comment by lminiero** [comment]
@mp16 a fix has already been suggested by @mivuDing (check his last image), so you can try to apply it manually in your environment to check if you notice any issues/regressions.

**Comment by mp16** [comment]
I have seen that image, but since I don't really know the code, it's better for me to have a diff. So, here one: https://github.com/mp16/janus-gateway/commit/c41fa14ebe5b6b08d5e0b27cbc5635396e52335b

I have added a "else" in order to not unlock twice the mutex. Is it ok ?

**Comment by lminiero** [comment]
No, that's not correct. I'll prepare a PR.

**Comment by mp16** [comment]
Sorry, I misread it. I think I get it this time: https://github.com/meetecho/janus-gateway/compare/master...mp16:fix_1982?expand=1

**Comment by mp16** [comment]
Thanks.

**Comment by lminiero** [comment]
I created a PR with the fix, so please test that to see if it works as expected for you.

**Comment by mp16** [comment]
I will, thanks.

**Comment by mivuDing** [comment]
@mp16 Maybe, I think the same fix should be done in janus_videoroom_setup_media and janus_videoroom_hangup_media, please see the follow attach. I hope it can works for you.
[videoroom.zip](https://github.com/meetecho/janus-gateway/files/4310120/videoroom.zip)
@lminiero Can you help me to check the diff of the attach? Is it OK? Thanks very much!

**Comment by mivuDing** [comment]
@mp16 Maybe, I think the same fix should be done in janus_videoroom_setup_media and janus_videoroom_hangup_media, please see the follow attach. I hope it can works for you.
[videoroom_update.zip](https://github.com/meetecho/janus-gateway/files/4310725/videoroom_update.zip)

@lminiero Can you help me to check the diff patch of the attach? Is it OK? Thanks very much!

**Comment by lminiero** [comment]
@mivuDing sorry but I won't open a zip file. Please share a diff, or open a pull request with the proposed changes.

**Comment by mp16** [comment]
Deadlock again this morning https://pastebin.com/EJK6Fas9 after like 12 hours of execution.

Stuck again in janus_videoroom_hangup_media, janus_videoroom_slow_link and janus_videoroom_hangup_subscriber.

@mivuDing I agree, I think there is deadlock in others functions too. I have created a pull request by using your zip file. I will try your fix after the review by @lminiero

**Comment by mivuDing** [comment]
@mp16 Thanks for the PR. If the fix work for you or didn't work, please let me know.
@lminiero Please help to review the PR, which mp16 had been pushed. Thanks a lot!

**Comment by lminiero** [comment]
@mivuDing as @atoppi said, this looks fine, but we'll need some more testing before we can merge. About that, please sign our [CLA](https://cla.conf.meetecho.com/janus/), since even if someone else created the PR for you, the contribution was actually yours, and there are credits to you in the commit.

**Comment by mivuDing** [comment]
@lminiero I have signed the CLA, thanks very much!
