### ISSUE TITLE
Audioconf is lagging people in calls > 3 people

### ISSUE THREAD

**Issue by mattvv** [meetecho/janus-gateway#206]
Hey guys,

Tried out the audioconf plugin and for myself it works fine, but for people on limited internet connections in any call with >3 people they are noticing a lot of lag.

I followed the audio conference example and it does only produce one stream on the website which is played. Is there anything else that could be causing this lag? These users are reporting no lag on calls with 2-3 people.

**Comment by lminiero** [comment]
I'm not aware of this issue, I recall testing this with several participants some time ago and it worked fine. If the problem is for users on limited connectivity, they might simply be getting a lot of retransmissions and so old audio: you can check this by looking at the admin API for their handles.

**Comment by mattvv** [comment]
Thanks @lminiero for pointing me in the right direction, I'll observe this tonight.

**Comment by mattvv** [comment]
Keeping this issue open, I had some basic tests but couldn't see any extra handles, although the user did complain of minimal lag. Going to update this when I get a larger test call going with user in question.

**Comment by mattvv** [comment]
Clsoing this. The lag i'm getting is unrelated to multiple streams, I'm opening a new issue after further testing.
