### ISSUE TITLE
Handling renegotiation with external stream

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2076]
Hey,
I'm having in issue when trying to renegotiate an external stream with Janus. I only get the message, that the track couldn't be added because it already exists on the sender. When I use the internal media parameters (f.e. <code>{video:true, audio:true}</code> everything works fine. After investigating, I found out that I had to remove  <code>config.streamExternal</code> from the following line:

https://github.com/meetecho/janus-gateway/blob/fe0d9f89057d4cfb8b5f80632fc9c576c52e5a2e/html/janus.js#L1643

Just wondering if this is correct and may be an issue with the code?

This is my camera switch function which works after changing the code above:

```
    async switchCamera() {





        cameraHelper.switchCamera(); // Changes facingMode variable
        this.localStream = await cameraHelper.requestMedia(); // Request media

        this.videoCall.createOffer({

            media: {
                replaceVideo: true,
                replaceAudio: true
            },
            stream: this.localStream,

            success: (jsep) => {
                this.videoCall.send({message: {request: "set"}, "jsep": jsep});
            }
        });



    }
```

**Comment by lminiero** [comment]
Good chances are janus.js is broken when trying to renegotiate with externally provided streams, since we never use that, but I think your approach will cause issues. To be honest, it's pretty low on our priority list and we're awfully busy as it is, so I have no idea if and when we'll have time to look into that. Should you experiment with that and want to contribute a pull request, we'll have a look.

**Comment by dnish** [comment]
Hey,
great, I'll test it some time and then create a PR to check if I notice any issue. So far I only noticed some page crashes on iOS Safari after 10-15 video calls but can't say if they were related to the code change.

**Comment by josefzamrzla** [comment]
@dnish Hi, have you solved this issue somehow? I'm dealing with the same problem - I want to use "external" stream to be able to eg. mute webcam stream using `track.stop()` instead of just enabling/disabling I have no idea how to replace the stream with the new one, it seems that janus.js still uses the first (stopped) one

**Comment by lminiero** [comment]
There's a patch for this in #2604, even though it needs to be updated. Please refer to updates there.

**Comment by lminiero** [comment]
Closing as the PR was merged.
