### ISSUE TITLE
Segfault in SIP plugin

### ISSUE THREAD

**Issue by zaltar** [meetecho/janus-gateway#2188]
We're running into a use after free bug in the SIP plugin that seems to randomly happen when a user has multiple incoming calls and abruptly closes their browser window destroying the session.

GDB backtrace: https://pastebin.com/UTG2FbJe
AddressSanitizer output: https://pastebin.com/4D4ADzmT

These were produced on the latest master, commit 7514b78e36a8bfb97d9474d4d0182cd307c906d2. Let me know if there's any more info I can provide.

Thanks!

**Comment by lminiero** [comment]
Sounds like a refcount error. The session has been already freed (refcount=0) even though the Sofia SIP loop thread is still alive, and that has a reference of its own. Try uncommenting the `#define REFCOUNT_DEBUG` in `refcount.h` and recompile: it will add A LOT of additional log lines (make sure you have room for those), but if it crashes again it will give us more info to track the life cycle of the session that went away.

**Comment by zaltar** [comment]
From latest master commit 0bb11f33d6c143d05ffae79796e46962019f5621
Here is the log from the crash with `RECOUNT_DEBUG` defined: https://pastebin.com/nTryNTUX
GDB backtrace: https://pastebin.com/w4Uf6AjM

From what I can tell, the helper `janus_sip_session` is being freed when it's removed from the master, before the Sofia SIP loop ends.  If an event happens to come in on the `nua_helper_t` that the helper `janus_sip_session` was bound to it crashes since it was already freed.

**Comment by lminiero** [comment]
Thanks, I'll look into this later to see if I can spot anything.

On a general note, it's normal for helper sessions to go away before the loop ends: the loop belongs to the master session, and stays up for as long as it needs, while helpers can come and go. As such, it can indeed happen that a helper session is still used by the loop somehow and cause that issue. I'll have to check if there's an event in the Sofia SIP stack we can use as an indication that the session is "free" to go: even in that case, though, there may be the risk of leaks, because if we interrupt the master goes away and the loop is closed, the event to get rid of a helper may never be fired/handled. I'll have to think about this.

**Comment by lminiero** [comment]
See the PR above: as I wrote there, I don't have time to test this, so please make sure that 1. it doesn't crash anymore, 2. there's no new memory leaks.

**Comment by lminiero** [comment]
Merged the fix, so I'll close.
