### ISSUE TITLE
Segfault in SIP

### ISSUE THREAD

**Issue by tfernandesp** [meetecho/janus-gateway#2191]
We're also running into a use bug in the SIP plugin that randomly crash but we cannot identified what is causing this failure yet 

AddressSanitizer output: https://pastebin.com/mBWKgtFN

These were produced on the commit 4f171c2. 

Let me know if there's any more info I can provide

**Comment by lminiero** [comment]
Please provide the whole commit ID, this one can't be resolved. If you didn't test master, do that first.

**Comment by tfernandesp** [comment]
This is the commit ID ea819175b34df157702996c04df79b9764f171c2. We are living with this problem for a long time, even updating to the master

**Comment by lminiero** [comment]
Then please provide a dump from master.

**Comment by ayty-adrianomartins** [comment]
This problem is the same of issue #2188. I am having the same issue as well, and the log post by @zaltar in comment below appears to indicate the problem:

https://github.com/meetecho/janus-gateway/issues/2188#issuecomment-637876987

**Comment by lminiero** [comment]
I see a notification about a message from @ayty-adrianomartins saying it's a duplicate of #2188, but I can't see it here: not sure if it's Github acting weird, or if the comment was since removed. Anyway, I'll close this issue then and mark it as a duplicate. Please refer to the other issue for updates.
