### ISSUE TITLE
Watch button in streaming demo needs to be clicked twice on mobile

### ISSUE THREAD

**Issue by willamowius** [meetecho/janus-gateway#2220]
The "Watch or Listen" button in the streaming demo needs to be clicked twice to work after you change the stream when you use it on mobile (tested Chrome on Android and Safari on iOS). On Desktop browsers it works the first time.

On mobile if you pick a  channel, then click (tap) "Watch or Listen" nothing happens. If you change the channel again, the next click won't work either, so its probably the updateStreamsList() function in streamingtest.js, but even after experimenting with it quite a while I have no clue, why.

**Comment by lminiero** [comment]
To be perfectly honest, I have zero time (and interest) to debug this :slightly_smiling_face: 
If you can find out the cause, happy to hear what it is.

**Comment by vincentfretin** [comment]
Generally speaking, on touch devices, if you need two touches to click on an element and on desktop only one click, it usually means the first touch is for the hover behavior, the second if for the real click. You may look at if there is a hover behavior with css or js on this button.

**Comment by lminiero** [comment]
I know it's silly to come back to an issue two years after it was opened, but I finally found out what the problem was :hand_over_mouth: 
Apparently, the cause was an item with class `dropdown-backdrop` not being removed after we selected a stream from the list: this item was intercepting the click, and that's why you needed to click twice. As a test while debugging Firefox mobile, I've added code to remove that element when we select a stream, and the problem was fixed, so I'll push it shortly on both `master` and `0.x`.
