### ISSUE TITLE
not-an-issue: welcome to alpine

### ISSUE THREAD

**Issue by uu** [meetecho/janus-gateway#2221]
Hello and thank you for this great project.

I've wrapped up fresh 0.10.1 version.

https://github.com/alpinelinux/aports/tree/master/testing/janus-gateway

Now you can put in the readme.md:

...
On Alpine:
`apk add janus-gateway`
...

Cheers!:)

**Comment by lminiero** [comment]
Thanks! What's the link I can put in the [resources](https://janus.conf.meetecho.com/docs/resources#repos) documentation page?

**Comment by gjovanov** [comment]
I just wonder if you have benchmarked Janus Alpine version vs. Debian based
Janus?

I'm asking because, initially we were using a very lean Alpine Janus Docker
Image (135MB):
https://github.com/gjovanov/docker/blob/master/janus/janus-alpine/Dockerfile


However, when load testing the video room with 24 active publishers (low
res and 128kbit/s cap), we noticed that there is considerable CPU usage
difference on one of our servers: 56% vs 39% on the same server using same
settings but on a Debian based Janus Docker image:

https://github.com/gjovanov/docker/tree/master/janus/janus-slim (170MB)

This led us to learn about the other similar performance degradation in
Alpine based Images because of:

MUSL vs GLIB

Even though, as you can see in the Dockerfile, we are installing GLIB
explicitly for compiling Janus, it still shows considerable CPU
difference:  56% vs 39%

So not sure why this was the case, so we ended up switching to the Debian
based image.


I wonder if you did some benchmarking and encountered similar results?

**Comment by uu** [comment]
> Thanks! What's the link I can put in the [resources](https://janus.conf.meetecho.com/docs/resources#repos) documentation page?

I really dunno:) It's in the official (edge) repo now. If it's needed, you can use the first mirror link or the [master one](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/janus-gateway).
whatever:)

**Comment by uu** [comment]
> I just wonder if you have benchmarked Janus Alpine version vs. Debian based Janus? 

No, I did not, but may be later I'll do some benchs. For now I'm really happy with current performance.
