### ISSUE TITLE
Static configuration of SRTP forwarding doesn't work in audiobridge plugin

### ISSUE THREAD

**Issue by willamowius** [meetecho/janus-gateway#2258]
The config file switches rtp_forward_srtp_suite and rtp_forward_srtp_crypto are never read in the source code and SRTP is not enabled.

When dynamically enabling forwarding through the API, SRTP parameters (srtp_suite and srtp_crypto) are used.

**Comment by lminiero** [comment]
Mh, looks like a typo due to some copy paste: the code to read and use them is indeed there, see
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L1894

but it's reading `srtp_suite` and `srtp_crypto` (which is what the API expects) rather than `rtp_forward_srtp_suite` and `rtp_forward_srtp_crypto` (which is what we'd expect in the configuration file). Should be an easy fix, thanks for spotting it :+1:

**Comment by willamowius** [comment]
The patch causes the "listforwarders" command to show the forwarder as using SRTP, but Janus can't decrypt the resulting media stream, even so both sides use the same suit and crypto string.

**Comment by lminiero** [comment]
You may want to check if it does work when doing SRTP forwarding from the VideoRoom instead.

**Comment by lminiero** [comment]
Another thing you can try is changing `ssrc_any_inbound` to `ssrc_any_outbound` in the AudioBridge code, since the SRTP forwarder will just send media and never receive any.

**Comment by lminiero** [comment]
Actually, turns out there's no `srtp_protect` call in the plugin at all... no surprise it doesn't work in the AudioBridge! It works as expected in the VideoRoom instead, where we do make use of the SRTP code. I'll try and put it in there later today.

**Comment by lminiero** [comment]
Ok, should be fixed now.

**Comment by willamowius** [comment]
Looks good, thanks!
