### ISSUE TITLE
No candidates not gathered yet for stream??

### ISSUE THREAD

**Issue by neilyoung** [meetecho/janus-gateway#2322]
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.

Well, I signed-up for the group and sent the "request membership" mail. No response so far, therefore my question here:

I'm using the `echotest` plugin. Literally each connection is showing this trace:

```
[Sat Aug 15 07:06:37 2020] [ERR] [ice.c:janus_ice_outgoing_traffic_handle:4202] [6388966281031467] No candidates not gathered yet for stream??
```

What exactly does that mean? I can see Janus and my device exchanging ICE candidates and the connection is perfectly established. However, this message (which I not even understand) appears all the time.

**Comment by neilyoung** [comment]
OK, got the invitation to the group. Will ask there.

**Comment by ds21194** [comment]
I have the same error on the Janus server (Did you solve it?), with the warning-
'Failed to add some remote candidates (added 0, expected 1)'
The server shows this error only when I configure 'full_trickle' to true, and he's showing the warning regardless.

When I set 'full_trickle' to false, I have another warning saying:
'[WARN] [3631177690243597] Waiting for candidates-done callback... (slow gathering, are you using STUN or TURN for Janus too, instead of just for users? Consider enabling full-trickle instead)'

On the client side, the connection is perfectly established, and I even get a message with status "started" about the video, while I can't see any video on the web. 

Maybe it's related to the issue (not sure) - before I get the 'starting' and 'started' status message, I can the log 'End of candidates.' and after that - 'Synchronous transaction successful' 

Please let me know if you think it's better to open a new issue instead of continue this one.

Thanks a lot for the help.

**Comment by abuzarshabab** [comment]
I have same issue

**Comment by Light995837** [comment]
hii @ds21194  have you found the solution of that error

**Comment by abhishek150-rt** [comment]
hii @ds21194 have you found the solutuon of that error
