### ISSUE TITLE
enhancing h265 I frame checking 

### ISSUE THREAD

**Issue by lm123** [meetecho/janus-gateway#2323]
In order to support all NAL types of I frame in h265, the following line (line 847) in utils.c had better be modified:

if(type == 32 || type == 33) {
==>
if(type == 32 || type == 33 || type == 34 || type == 16 || type == 17 ||  type == 18 || type == 19 || type == 20 || type == 21) {

**Comment by lminiero** [comment]
Not sure I care much, honestly. H265 is only supported by an experimental version of Safari, for which our checks work.

**Comment by lminiero** [comment]
I think Safari is still the only browser that does H.265, and still behind a flag, which makes it a codec pretty much no-one uses, but just to accomodate those that may rely on it, I'll push the suggested fix: in case it turns out it causes issues, we'll hopefully be told and we'll fine tune it accordingly.
