### ISSUE TITLE
Receiving unpublished event twice

### ISSUE THREAD

**Issue by neilyoung** [meetecho/janus-gateway#2334]
I'm in a the 1234 video room with two publishers. Once the A browser unpublishes the B instance receives the `unpublished` event twice.

Is this by design?

![image](https://user-images.githubusercontent.com/731020/91063902-d682c580-e62e-11ea-96ae-7b97119ca9a7.png)

The decode messages are identical.

Message 1

```
{
   "janus": "event",
   "session_id": 3116374720068149,
   "sender": 8041693836001917,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "event",
         "room": 1234,
         "unpublished": 1143968836642153
      }
   }
}
```

Message 2

```
{
   "janus": "event",
   "session_id": 3116374720068149,
   "sender": 8041693836001917,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "event",
         "room": 1234,
         "unpublished": 1143968836642153
      }
   }
}

```

**Comment by atoppi** [comment]
@neilyoung how are you un-publishing the user?
In case you are sending just the `unpublish` message, you should receive the event once.
I can see a `detach` and also a  `hangup` caused by DTLS alert (`pc.close` on client side) so I think that you are unpublishing the user in mutiple and concurrent ways. 
Said this, consider that there are some scenarios where a double `unpublished` is by design (IIRC just issuing `detach` will trigger a double event).

**Comment by neilyoung** [comment]
So seems, detach is the trigger...

**Comment by neilyoung** [comment]
Well, no. The "unpublished" message is also sent twice, if A doesn't send a "detach" at all... Very strange...

**Comment by atoppi** [comment]
@neilyoung I've reproduced this case.
The first event is triggered by the `unpublish` request, while the second one is caused by the DTLS alert sent by the publisher.
We are executing twice the method `videoroom_hangup_media_internal`, that in turn will issue `janus_videoroom_leave_or_unpublish` and finally `janus_videoroom_notify_participants` (responsible of sending the events).

**Comment by neilyoung** [comment]
Ok, not optimal but I can live with it. Thanks for the explanation
