### ISSUE TITLE
Grid-view offer feature (enhancement)

### ISSUE THREAD

**Issue by bilo1967** [meetecho/janus-gateway#2408]
On a browser I can combine several incoming video streams by drawing them in a grid on a canvas element and then share that canvas as a single video stream (say we have 12 incoming streams: I draw them on 4x3 grid on a canvas and then I get back a MediaStream via captureStream).

Would it be possible to implement something like this directly in the videoroom plugin as an automatic "grid-view" offer feature provided by the room? Each publisher could decide if their video stream should be added or not to this "collage". Listeners could save band subscribing to this single video stream instead of many.

**Comment by lminiero** [comment]
What you're talking about is called MCU, and requires decoding streams, composing them programmatically and re-encode the stream: it's something the VideoRoom cannot do, since it's an SFU (you can learn more about the differences in [this presentation](https://www.slideshare.net/LorenzoMiniero/can-sfus-and-mcus-be-friends-iitrtc-2020) I made a few days ago). It would require a new dedicated plugin, that would do for video what the AudioBridge does for audio, but we don't plan to write and release a new plugin for that, as: 1. it's not a trivial task, and 2. an MCU is a very CPU intensive component, which is something we typically try to keep Janus out of.
 
We have a custom videomixer we use for our own needs, that can be used with Janus thanks to RTP forwarders, so we're covered on that requirement when we need it, but it's proprietary.

Closing as out of scope here. For more discussion please refer to the [group](https://groups.google.com/forum/?pli=1#!forum/discuss-webrtc).
