### ISSUE TITLE
Weird behaviour when passing unneeded parameters as null instead of ommitting

### ISSUE THREAD

**Issue by laurensramandt** [meetecho/janus-gateway#2490]
When attaching to a plugin, the session is not found if we pass optional parameters as null when creating the session and/or attaching to a plugin.

I created a gist with an example of passing optional parameters as null and an example of not passing them at all. 
In the first example, the created session is not found when attaching to the plugin.

https://gist.github.com/laurensramandt/ddc71d635335eac9e5feb8ca75e92493

**Comment by lminiero** [comment]
Mh that's weird: in the "attach" example, I'd expect the error to be 459 (handle not found), as it may be trying to get handle `null` and not finding it, and not 458, as the session ID is there in the request. I'll try to replicate the issue, to see if I can spot where it is.

**Comment by lminiero** [comment]
As I thought, the "handle=null" case is where the error is returned, but it's returning `JANUS_ERROR_SESSION_NOT_FOUND` instead of `JANUS_ERROR_HANDLE_NOT_FOUND`, which is a mistake. I'll fix this right away. So this confirms that's where the problem originates.

Another issue is that the check doesn't account for the attribute being `null`: we have a `json_is_integer` check before, but it's not used to reset the variable if it isn't, so it's still treating it as if we had a handle to process. I'll fix that too.

**Comment by lminiero** [comment]
This should fix it.
