### ISSUE TITLE
Why reinjecting libnice discovered remote candidates back in libnice ?

### ISSUE THREAD

**Issue by fbellet** [meetecho/janus-gateway#2491]
Hi!

I'm wondering if there's a reason to add remote candidates learned from libnice back in libnice via janus_sdp_process(). From libnice point-of-view, such remote candidates added this way will certainly now be discarded (they duplicate an existing remote candidate anyway), because they are not supposed to be exchanged in an sdp.

https://github.com/meetecho/janus-gateway/blob/e82a06b37e9f1a829808b54de39f719d571a7806/ice.c#L2242

See https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/176 for a discussion on dropping such remote candidates when received from nice_agent_set_remote_candidates().

**Comment by lminiero** [comment]
The reason is to start connectivity checks if no candidates were exchanged in the SDP. It's explained in detail here: https://gitlab.freedesktop.org/libnice/libnice/-/issues/69

**Comment by lminiero** [comment]
Unless you didn't mean prflx candidates we discover?

**Comment by lminiero** [comment]
Just checked and it's as I said: we only re-inject prflx candidates we're made aware of, not all candidates. We do that because, unless you do an explicit `nice_agent_set_remote_candidates()` call, libnice won't start its own connectivity checks, and so if the peer didn't advertise any candidate (or advertised unresolvable mDNS candidates), then prflx candidates found at runtime are the only ones we know and we have to reinject them in that way.

**Comment by fbellet** [comment]
I see. This is a workaround for force libnice to call conn_check_schedule_next() and start the conncheck. I'll try to reproduce the problem locally.

**Comment by fbellet** [comment]
Normally, the call to ``nice_agent_set_remote_credentials()`` should start the conncheck as well, even with the lack of remote candidates. Except if there's a relatively long delay, **after** remote credentials have been set, and **before** a first inbound stun request is received.

When the conncheck timer is started, if the conncheck list remains empty for 5 seconds, the timer stops, and the conncheck is declared completed.

Could it be what happens in that case?

**Comment by lminiero** [comment]
From what Olivier said, `nice_agent_set_remote_credentials` only started connectivity checks recently. We made this workaround a long time ago, when this feature was likely not there yet, and as such our approach was the only way to solve things.

About your other question, I guess it depends on the flow. What happens if the peer sends an offer, and we send an answer much later (e.g., because it's the SIP plugin and the SIP endpoint sends its 200 OK after a while)? In this case, more than 5s after `nice_agent_set_remote_credentials` could indeed pass. Since we only start gathering when a response is available, in this scenario, no checks would be sent anyway, but how does libnice behave here? Will the 5s count only start from when the gathering starts?

**Comment by fbellet** [comment]
> About your other question, I guess it depends on the flow. What happens if the peer sends an offer, and we send an answer much later (e.g., because it's the SIP plugin and the SIP endpoint sends its 200 OK after a while)? In this case, more than 5s after `nice_agent_set_remote_credentials` could indeed pass. Since we only start gathering when a response is available, in this scenario, no checks would be sent anyway, but how does libnice behave here? Will the 5s count only start from when the gathering starts?

Currently, this 5s delay begins while the conncheck timer is running, when there's no more checks to process, and when the conncheck list can no more evolve alone. Then the conncheck timer is stopped after 5s of such "inactivity". This grace delay was initially thought as a mechanism to handle the termination of the conncheck, to avoid bouncing between state connected and ready, just upon late inbound stun requests. But it proved to have other consequences on the beginning of the conncheck too...

Since the conncheck timer is now started basically only from `nice_agent_set_remote_candidates` and `nice_agent_set_remote_credentials` by function `conn_check_schedule_next`,  I'd say that gathering  will not restart the timer in that case, if 5s have passed since the call to `nice_agent_set_remote_credentials`

I proposed a merge request in libnice to [change that behaviour](https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/182), and to make start the conncheck timer only when we are sure that there is work to be done. This should hopefully fix this case of unexpected timer start and stop.

**Comment by lminiero** [comment]
Closing as this was mostly a discussion, rather than a bug report. I'll keep track of the work you mentioned, thanks!
