### ISSUE TITLE
[VideoRoom] Starting participant video keeps on recording after recording has stopped

### ISSUE THREAD

**Issue by lainlx** [meetecho/janus-gateway#2550]
I'm experiencing the following issue, whenever I have a recording going on in videoroom and a publisher turns on his video, then when the recording stops, participant's video keeps on recording (file keeps on getting larger). This seems to be 100% repro whenever the video starts after the recording has begun.

Steps to repro:
- Start recording for all
- New publisher joins, recording auto starts
- Stop recording for all
- New publisher recording keeps going

I've come up with the following patch that seems like solution, but I would like to know your opinion on the matter, if it makes sense or not.

```
--- plugins/janus_videoroom.c	2021-01-21 23:30:26.000000000 +0000
+++ plugins/janus_videoroom_new.c	2021-01-21 23:30:01.000000000 +0000
@@ -7316,6 +7316,7 @@
 				janus_mutex_lock(&participant->rec_mutex);
 				if(videoroom->record || participant->recording_active) {
 					janus_videoroom_recorder_create(participant, participant->audio, participant->video, participant->data);
+					participant->recording_active = videoroom->record;
 				}
 				janus_mutex_unlock(&participant->rec_mutex);
 				/* Generate an SDP string we can offer subscribers later on */
```

**Comment by lminiero** [comment]
I think you found the root cause of the issue: stopping the recording via `enable_recording` set to `FALSE` does indeed traverse participants to see if their `recording_active` was set to `TRUE`. Since we're not initializing it to `TRUE` for the new participant, nothing is done when the recording is stopped and it keeps on going. I'll push the fix you suggested.
