### ISSUE TITLE
WebRTC error... "Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video send codecs.."

### ISSUE THREAD

**Issue by pyshpa** [meetecho/janus-gateway#256]
I'm trying to g-stream video from my board to Janus. I'm able to stream the video when trying in firefox browser. But in chrome it is producing error "WebRTC error... "Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video send codecs.."".

g-streaming video format is H264 payload=126

In Configuration file 'janus.plugin.streaming.cfg' content as below
[h264-sample]
type = rtp
id = 10
description = H.264 live stream coming from gstreamer
audio = no
video = yes
videoport = 5004
videopt = 126
videortpmap = H264/90000
videofmtp = profile-level-id=42e01f\;packetization-mode=1

It would be a great pleasure if anyone can help me out from this.

**Comment by lminiero** [comment]
Chrome doesn't support H.264 yet.

**Comment by pyshpa** [comment]
May I know which video formats does chrome support.

**Comment by lminiero** [comment]
Chrome only supports VP8 and VP9.

**Comment by ignacioavellino** [comment]
Hi! I have the same need, and I'm using gstreamer. Does anyone know how to stream in VP8 using gstreamer? So far in order to stream in h264 (from a raspberry pi camera) to Janus I'm doing:

$ raspivid --verbose --nopreview -hf -vf --width 640 --height 480 --framerate 15 --bitrate 1000000 --profile baseline --timeout 0 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=8004

**Comment by Computician** [comment]
@ignacioavellino you may want to go to the [google group](https://groups.google.com/forum/#!forum/meetecho-janus) for this type of question. There may be answers there that will give you what you need. That place would also be better for this type of question(as it is not a bug).

**Comment by ignacioavellino** [comment]
Yes, thank you, sorry about that :)
