### ISSUE TITLE
AudioBridge: Permanent RTP_Forward

### ISSUE THREAD

**Issue by maxboehm** [meetecho/janus-gateway#2570]
We configure our AudioBridge to forward via RTP.

Our settings are permanent, so in case something goes wrong (restart janus), every setting made will be immediately available to our application.

Right now, the rtp_fowarding_*-settings are not written to the config file if the room was created with "permanent=true". 

The required changes seem rather obvious: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L2726

Would you accept a PR for that or is there any reason one cannot or must not do this?

Thank you, cheers,
Max

**Comment by lminiero** [comment]
RTP forward settings are not saved to file because they're not part of the "create" request. The only way to create a forwarder dynamically, at the moment, is via a "rtp_forward" request. As such, it's not just a matter of saving info to file, but also to add new code to allow creating a default RTP forwarder right away when you "create" the room. I'm not against that, as long as it doesn't mean too much replication of existing code.

**Comment by maxboehm** [comment]
Ok. It's not that straight-forward because the current config-definiton also does not allow multiple rtp_forwarder.

I close this issue with this comment. As soon (Not sure when :-) ) we have a PR i'll reference it.
