### ISSUE TITLE
overflow in the reported stats

### ISSUE THREAD

**Issue by mirkobrankovic** [meetecho/janus-gateway#2579]
In very lossy networks the number of nacks sent in an interval could exceed the number of packets sent. In those cases the ratio nacks/sent exceeds 1, thus leading to an overflow in the reported stat.

As it can be seen in log:
https://pastebin.com/WSsX9GUh
` "out-link-quality": 4294967222
`
Version: 0.10.10

**Comment by lminiero** [comment]
We'll have to figure out the best way to handle this. A simple fix might be capping the number of nacks in that calculation, so that it never exceeds the number of sent packets, but that may be a bit of a hack; taking into account when a NACK is actually sent more than once may be tricky, and may "pollute" that value as well (multiple retransmissions of the same packet may be indications of trouble too).

**Comment by lminiero** [comment]
Went for the easy fix :slightly_smiling_face:

**Comment by mirkobrankovic** [comment]
thanks :)
