### ISSUE TITLE
Incorrect flexfec formation in SDP since WebRTC M89

### ISSUE THREAD

**Issue by UGeneF** [meetecho/janus-gateway#2639]
Hello!
We have encountered an issue with the videocall plugin and WebRTC 89: Janus produces an SDP with the incorrect formation of the flexfex section - it hasn`t an ssrc group as stated at [RFC](https://tools.ietf.org/html/draft-ietf-payload-flexible-fec-scheme-20#section-7.1), so the SDP cannot be parsed.
The bug reproduces only in the case of a one-way video call with the WebRTC version M89 or newer.
Detailed steps to reproduce the problem (along with a dump containing SDP at line 2351) are described at [this WebRTC issue.](https://bugs.chromium.org/p/webrtc/issues/detail?id=12685)
Can you fix the bug, please, or point out a mistake from our side?

**Comment by lminiero** [comment]
We don't support flexfec. I haven't seen what the SDPs look like, but I'll drop it from the SDP entirely, maybe later today.

**Comment by lminiero** [comment]
Just checked the SDP. FEC has nothing to do with it: the ssrc-group that's missing is the one for rtx, not FEC (and in fact Chrome doesn't set an ssrc-group for that either). The ssrc-group for rtx is missing because the rirection of media in the answer is `recvonly`, but in that case we're incorrectly adding the additional SSRC for rtx (which will be unused), so that will need to be fixed. That said, I'm going to drop support for flexfec from the negotiation entirely, because otherwise things are just going to not work otherwise.

**Comment by fippo** [comment]
but flexfec was added in M89 while the other behaviour has been around for ages? Either way, two bugs with one report :+1:

**Comment by lminiero** [comment]
Yes, I guess no one tried sendonly with VideoCall/SIP/NoSIP before :wink:

**Comment by lminiero** [comment]
I didn't get a `setRemoteDescription` failure in `91.0.4469.4` when doing a sendonly VideoCall to a recvonly user (it worked), but I fixed the SDP behaviour anyway. Flexfec is also rejected now, even though I don't see it in any offer (maybe it's still hidden behind a flag?). Closing.

**Comment by fippo** [comment]
flexfec is activated recv-only -- the send part isn't... quite good yet.

**Comment by lminiero** [comment]
I didn't see any flexfec line in my SDPs, though, when trying to replicate with VideoCall. Maybe Linux is left behind as usual :hand_over_mouth:

**Comment by UGeneF** [comment]
Thanks a lot for the instant reaction!
