### ISSUE TITLE
Update Jquery & remove usage of depricated .live() method

### ISSUE THREAD

**Issue by mitre-mgarber** [meetecho/janus-gateway#2648]
We ran into this trying to leverage some of the existing Janus javascript client libraries from the demo implementations (specifically the T140 flavor of the SIP plugin) as a proof of concept in our SIP client application - the .live() method referenced in siptest.js has been deprecated (along with the bind and delegate methods) in favor of .on(), and we weren't able to use the older version of JQuery due to a version conflict with the minimum version of JQuery Bootstrap 4 required, which we were using for styling.

I don't know that this is necessarily the most common use case, but it would help with exploratory implementations to update to at least JQuery 1.7. We tried this with JQuery 1.9.1 and were successful for this one module, though there may be other complications elsewhere. Using the 3.0.0-compat version would likely also work, though we haven't tested it (and would loop in promises support, if that's of any interest).

**Comment by lminiero** [comment]
> the .live() method referenced in siptest.js has been deprecated

I don't even remember why I used `live()` there, since the PR is almost 2 years old; we definitely don't use it anywhere else. If `on()` is the one to use, I'll fix that. For the rest, we already ask for jQuery 1.9.1 in all demo pages: if the T.140 branch still asks for an older one, it's because we haven't aligned in a while I guess.
