### ISSUE TITLE
SVC and sequence number of reordered (or retransmitted) packets

### ISSUE THREAD

**Issue by arseny30** [meetecho/janus-gateway#2694]
When SVC is used, some packets are dropped because of too high temporal or spatial level
`v_base_seq` is incremented by 1, so all later packets will have seq decreased by 1 when relaying
https://github.com/meetecho/janus-gateway/blob/2d5f2be38b9c19d7affa45a929d7b7e5596dc6aa/plugins/janus_videoroom.c#L7942
https://github.com/meetecho/janus-gateway/blob/2d5f2be38b9c19d7affa45a929d7b7e5596dc6aa/rtp.c#L631

But what if we receive some older, reordered or retransmitted packets?
If we decide to relay one of them, it will have incorrectly decreased `seq`.
If we drop one of them, we will incorrectly decrease `seq` of later packets.

An example:
(for simplicity `context->v_base_seq == context->v_base_seq_prev`)
Say we receive a packet with `seq=100` and drop it. `v_base_seq` is incremented by one
Then receive a packet with `seq=101`. Relay it with `seq=100`
Then receive a packet with `seq=99` and drop it. `v_base_seq` is incremented by one
Then receive a packet with `seq=102. Relay it with `seq=100`.
So two packets will be relayed with the same sequence number. And the receiver will have to ignore one of them. 

Is it an actual problem in real world, or am I missing something?

**Comment by lminiero** [comment]
> Is it an actual problem in real world, or am I missing something?

It's not a problem in the real world, because no one uses this in the real world right now :slightly_smiling_face:  SVC is only available for VP9, and VP9-SVC is hidden behind an experimental flag in Chrome (even though that may have changed, not sure).

Jokes apart, I didn't give it much thought at the time, so not sure if this could indeed be an issue. That said, I think the receiver would not get the packet with the same sequence number twice, because the RTP header rewriting would result in pretty much the same header as the packet we sent before, and so it would be stopped by the SRTP encryption process. Of course, even if for different reasons, it does still mean that retransmitted packet would never get to the receiver.

Not sure how this could be addressed, and at the moment it's a bit of a low priority for me honestly. If you can confirm this is indeed an issue (e.g., via simulations) and there are any suggestions (or PRs) on how to improve the behaviour, they'd of course be welcome.

**Comment by lminiero** [comment]
Closing for now as we never received an issue on this happening, so I guess we can start worrying if/when SVC becomes more widespread.
