### ISSUE TITLE
sip: Registering... but not really

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#274]
Hi!

I wanted to share the ideas I have for the patch I'm working on, in case someone (I'm looking at you @lminiero :smile: ) has feedback.

What I really need is the ability to make multiple calls with the SIP plugin from the same account. Now, the plugin seems to be designed around the idea of "one plugin handle -> one SIP account -> one call", and adding multiple sessions support looks messy, so I came up with the following workaround:

* An application would have a couple (or more) plugin handles for a given account, so calls can be received over them.
* The same application would create new plugin handles for each outgoing call, but **not** send a REGISTER over them, just use the "register" command to store the credentials and then make the outgoing call.

In order to achieve this I plan to add a boolean attribute to the "register" command, in order to skip the registration process.

**Comment by lminiero** [comment]
When I first conceived Janus and the SIP plugin, my idea was to completely abstract the SIP stuff, and allow WebRTC users to basically share a single SIP account in the background. This would have allowed, for instance, the same user to open several tabs/pages all connected to the same SIP account, so that an outgoing call on one tab would make the others busy, and incoming calls would ring on all tabs and only be answered on one. As a use case, think about a social network where you can call and be called by your friends: it's not unusual to have multiple pages open on the same social network, and ideally you'd want to be reachable and potentially active on them all. I eventually gave up and chose a simpler approach as it looked dangerously close to forking and stuff like that, all things that can indeed be handled at a SIP level without having to worry about that at the plugin/user level.

Being able to somehow "share" an account across different handles would indeed be really interesting, as it would basically tackle the use case I thought of at the time. I'm not sure about how you're planning to implement this, though: is the idea that you only actually register once on a single handle to receive calls (which means you can only receive calls on that specific handle), while you reply to challenges on unregistered accounts on the other handles when you want to send an INVITE? What's wrong in actually registering on all the handles you're interested in? Is it because you want to limit the number of endpoints that can answer a call, but not those who can start one?

**Comment by saghul** [comment]
> Being able to somehow "share" an account across different handles would indeed be really interesting, as it would basically tackle the use case I thought of at the time. I'm not sure about how you're planning to implement this, though: is the idea that you only actually register once on a single handle to receive calls (which means you can only receive calls on that specific handle), while you reply to challenges on unregistered accounts on the other handles when you want to send an INVITE? What's wrong in actually registering on all the handles you're interested in? Is it because you want to limit the number of endpoints that can answer a call, but not those who can start one?

Ideally I'd like to share the account, but at a first glance I think that change would need a lot of rewriting, so I took a different approach. The plan is indeed to use "disposable" handles that don't register. You'd create one, call, destroy it. The reasons to not have them register are:

* some proxys limit the number of registrations you can have
* some PBXs only allow a single registration
* there is no real need (as per the SIP standard) to be registered in order to send an INVITE
* if the handle is going to be disposed after the call ends, registering is not really necessary

**Comment by lminiero** [comment]
Makes absolute sense, then. I can also see why re-using the "guest" approach we have wouldn't work (no storing of any credential, there). Do you need any help by me on this new feature, or have you it already planned out?

**Comment by saghul** [comment]
Thanks! I've already planned it (hopefully I got it right!) I hope to PR my changes later today / tomorrow.
