### ISSUE TITLE
Newly created RTSP streams are stuck forever in retry loop if the corresponding mount point is not destroyed explicitly 

### ISSUE THREAD

**Issue by mykola-mokhnach** [meetecho/janus-gateway#2760]
Steps to reproduce:
1. Deploy Janus with streaming plugin and REST API enabled and session timeout set to 60 seconds in the main config
2. Start an RTSP server
3. Create a Janus mount point to this RTSP server via `create` API request. Make sure the mount point is NOT permanent
4. Start the RTSP stream playback in the browser
5. Shutdown the RTSP source and close the browser without explicitly sending the `destroy` request.

Actual result:
I can observe that Janus is stuck in an endless reconnection loop to the RTSP stream and never stops it even after 60-seconds timeout expires. Constantly repeating blocks like this could be observed in logs:

```
* Connection timed out after 5000 milliseconds
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
*   Trying 10.108.48.207...
* TCP_NODELAY set
* connect to 10.108.48.207 port 8554 failed: Connection refused
* Failed to connect to 10.108.48.207 port 8554: Connection refused
* Closing connection 0
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:6425] Couldn't send DESCRIBE request: Couldn't connect to server
[WARN] [mp-8565725846422928] Reconnection of the RTSP stream failed, trying again in a few seconds...
[WARN] [mp-8667237968754348] 5s passed with no media, trying to reconnect the RTSP stream
```

Expected result:
Janus should stop retrying connections to the dead RTSP endpoint and remove the mount point after the session timeout expires

**Comment by atoppi** [comment]
>Expected result:
Janus should stop retrying connections to the dead RTSP endpoint and remove the mount point after the session timeout expires

That is not the expected behavior.
Janus will always try to reconnect to a RTSP endpoint when the connection drops, according to the RTSP mp `create` settings:
`rtsp_reconnect_delay`
`rtsp_session_timeout`
`rtsp_timeout`
`rtsp_conn_timeout`

As of the `permanent` parameter, it has nothing to do with the removal of a mountpoint if the RTSP endpoint is being disconnected. It will only make the mountpoint survive a Janus restart.
