### ISSUE TITLE
[0.x] Janus crashes (heap-use-after-free)

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2867]
**What version of Janus is this happening on?**
0.11.8

**Have you tested a more recent version of Janus too?**
Master of Git

**Was this working before?**
We couldn't detect the issue on version 0.11.6. The regularly crashing started with version 0.11.7.

**Is there a gdb or libasan trace of the issue?**
https://pastebin.com/NMbpKEj7

**Comment by lminiero** [comment]
Please do use the template we've added, instead of just removing it: it's there for a reason.

**Comment by dnish** [comment]
Updated

**Comment by lminiero** [comment]
As @tmatth pointed out in https://github.com/meetecho/janus-gateway/issues/2840#issuecomment-1026129348, it's a race condition. I'll have to think about how to address that, since using the same handle mutex there seems overkill to me (relay_rtp is called very often), and has risks of deadlocks (even though that shouldn't be the case, IIRC we never invoke a plugin callback with the mutex locked, and so there shouldn't be something that can cause us to go back to the core and lock again). Doing a `g_strdup` on the mid sounds a bit overkill as well.

Another option may be moving the whole RTP extension update logic to the loop, which would then avoid conflicts, since webrtc_free is always called from there. This would mean queueing the packet as we received it, and when we process it for delivery (`janus_ice_outgoing_traffic_handle`) doing the RTP extension dance before that. This would add to the work the loop thread would have to perform, since right now we mess with extensions from the thread the plugin is responsible for, but that may be the right thing to do anyway, since we probably don't want to keep the plugin thread too busy anyway (allocating and queueing should be enough).

**Comment by lminiero** [comment]
Please test the PR above.

**Comment by dnish** [comment]
@lminiero I've added the PR to our production server. Now we get another error:

https://pastebin.com/kXZZqALM

**Comment by tmatth** [comment]
> @lminiero I've added the PR to our production server. Now we get another error:
> 
> https://pastebin.com/kXZZqALM

@atoppi fixed this in cba15bb8557f4e5caddb6c5eef8e83af32bd37c7, if @lminiero rebases #2869 it should avoid this.

**Comment by lminiero** [comment]
Please discuss the patch on the PR, not here. That said, I've just rebased.
