### ISSUE TITLE
[0.x] Register with  SIP Pulgin fails 

### ISSUE THREAD

**Issue by tijmenNL** [meetecho/janus-gateway#2868]
**What version of Janus is this happening on?**
0.11.7

**Was this working before?**
Yes

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
Upgrading to Janus 0.11.7 from 0.11.6 on Debian unstable makes registering fail with the following message:

`janus[660887]: nta outgoing create: no transport protocol`

We don't use force_tcp or force_udp and don't have sips set in the register API call. We do have `"proxy": "sip:x.x.x.x;transport=tcp"`

Sofia 1.12.11+20110422.1-2.1+b1 is installed

**Comment by lminiero** [comment]
Very likely a consequence of the fix to #2683, see https://github.com/meetecho/janus-gateway/issues/2683#issuecomment-1009917112 and https://github.com/meetecho/janus-gateway/commit/c3c84d22dd292cacc5d9cf78e012e6c77d759028#commitcomment-64578000 for some more context.

Since you're forcing tcp as a transport for the proxy, my guess is you need to force tcp when registering as well, as due to that fix we now only bind to either udp (default) or tcp, not both.

**Comment by tijmenNL** [comment]
I see, but shouldn't transport=tcp in the proxy url already imply force_tcp internally?

I can probably set it based on the proxy url contents, but what will happen if for instance you use force_tcp with a url with transport=udp? Which will be used force_tcp or transport=udp?

**Comment by lminiero** [comment]
What you set in proxy is not evaluated by the plugin: it's passed as it is to `NUTAG_REGISTRAR`.

**Comment by tijmenNL** [comment]
Ok, so for now I should just set force_tcp if the proxy url contains transport=tcp.

Do I also need to force_tcp if it contains `sips:x.x.x.x:transport=tls`

**Comment by lminiero** [comment]
I think so, since otherwise the default will be to bind to UDP _and_ create a SIPS endpoint as well, which was one of the main causes of things breaking when using more recent versions of Sofia. But since you're using an older one, it may not be necessary (better test it, though).

**Comment by tijmenNL** [comment]
Setting force_tcp with transport=tcp works.

I am testing with tls to see if it is also needed. However it does not seem to make any difference. I get:
`nta outgoing create: no secure transport`

And the result the API call:
`416 Unsupported URI Scheme`

As proxy url I use: sips:IP:PORT, I also configured the certs (agent/cafile)

**Comment by lminiero** [comment]
Can't help, sorry, I don't know much about the internals of the library, especially when it comes to sips. Maybe you can try changing the line that says

    NUTAG_URL(sip_url),

with

    TAG_IF(!session->account.sips, NUTAG_URL(sip_url),

so that only a sips tag is passed to the stack when enabled, rather than the plain TCP one as well. But again, this is just me guessing, since I don't know what the library expects in that case.

**Comment by lminiero** [comment]
As I said in the discussion here https://github.com/meetecho/janus-gateway/commit/c3c84d22dd292cacc5d9cf78e012e6c77d759028#commitcomment-64578000, if you find a way to programmatically check if the Sofia in use is the old one or the new one, we can implement different behaviours (like using the old one if it's the older version). Otherwise I have to make the code work for both of them and nothing I can do about it.

**Comment by lminiero** [comment]
Thanks for the feedback! Does this mean the issue can be closed then?

**Comment by tijmenNL** [comment]
Sure, I will close it.
