### ISSUE TITLE
play the webrtc stream with gstreamer

### ISSUE THREAD

**Issue by deedos** [meetecho/janus-gateway#287]
Hi.
Is it possible to grab one or many streams from a MCU session , for example, and play them with a gstreamer pipeline ?

thanks in advance

**Comment by lminiero** [comment]
Yes, just look at the RTP forwarding functionality the amazing @Computician added in #255.

**Comment by Computician** [comment]
@deedos if you have specific questions about what pipelines I typically utilize or anything like that, please go to the google group. I have had great success utilizing gstreamer for live media analysis, playback and recording(directly to a merged AVI of all the streams in the MCU instead of simply copying the rtp packets to a file like the mjr recorder).

**Comment by deedos** [comment]
Hi @Computician and @lminiero . thanks you both. I did join the group, now I wait for approval. I could not realize how to work with the rtp_listen feature. (do I nedd to curl with the JSON to enable the forwarding ?) I 'm a newby around webrtc, I apprecciate more detailed info on that and if possible, the pipelines, as well. (My goal is forwarding clean feed from MCU to a video mixer, for tv production!) 
Thanks again for such great and lively project

**Comment by Computician** [comment]
@deedos, I will be looking at the group for your question. I will answer all that I can :)
