### ISSUE TITLE
[1.x] Streaming plugin recording capability has mutex issues

### ISSUE THREAD

**Issue by evplatt** [meetecho/janus-gateway#2902]
**What version of Janus is this happening on?**
1.0.0

**Have you tested a more recent version of Janus too?**
N/A

**Was this working before?**
Unknown - first usage

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**

For streaming recording **start** requests with 'media' key (not the "old method"), mountpoints_mutex is never unlocked after starting the recording.  Suspect it should be unlocked prior to 'goto prepare_response'

For streaming recording **stop** requests with 'media' key (not the "old method"):
- source->rec_mutex attempts to lock twice, once before if(media) and once after, causing a lockup
- mountpoints_mutex is never unlocked after stopping the recording.  Suspect it should be unlocked prior to 'goto prepare_response'

**Comment by atoppi** [comment]
Thanks for reporting @evplatt.

When starting recording it seems that both a `mp` ref decrease and `mountpoints_mutex` unlock are missing in this block
https://github.com/meetecho/janus-gateway/blob/2009325fb3ac0911929563cd3008090080c89784/src/plugins/janus_streaming.c#L4680-L4685

When stopping I can confirm the double `source->rec_mutex` locking 

https://github.com/meetecho/janus-gateway/blob/2009325fb3ac0911929563cd3008090080c89784/src/plugins/janus_streaming.c#L4782-L4785

and also the missing unlock / unref 

https://github.com/meetecho/janus-gateway/blob/2009325fb3ac0911929563cd3008090080c89784/src/plugins/janus_streaming.c#L4811-L4816

we'll work on a fix.

**Comment by lminiero** [comment]
Related to this, I fixed a couple of additional issues:

* there was still a crash when stopping a recording, and that was due to a dereference of `stream->rc` that could be `NULL` (not all streams may be recording, when we choose to stop it)
* there was also a problem when _starting_ recording using the legacy API, as the code was not really using the `video` and `data` properties when provided.

Both should be fixed in the commit above.
