### ISSUE TITLE
[1.x]  Documentation of streaming plugin recording stop request structure does not match implementation

### ISSUE THREAD

**Issue by evplatt** [meetecho/janus-gateway#2903]
**What version of Janus is this happening on?**
1.0.0

**Have you tested a more recent version of Janus too?**
N/A

**Was this working before?**
Unknown - first usage

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**

According to the documentation, the following request structure is to be used:
```
{
	"request" : "recording",
	"action" : "stop",
	"id" : <unique ID of the mountpoint to manipulate; mandatory>,
	"media" : [		// Drill-down recording controls
		{
			"mid" : "<mid of the stream to stop recording>"
		},
		{
			// Recording controls for other streams, if provided
		}
	]
}
```

But the implemented structure seems to be:

```
{
	"request" : "recording",
	"action" : "stop",
	"id" : <unique ID of the mountpoint to manipulate; mandatory>,
	"media" : [
		<array of mids to stop recording>
	]
}
```

**Comment by lminiero** [comment]
Good catch! I think the implementation should be fixed, rather than the docs, since this would ensure consistency in the format expected in both `start` and `stop`. Besides, in the future we may want to add/modify properties by which we can index what we want to stop, and using an object would allow that. I'll work on a fix shortly.
