### ISSUE TITLE
Duplicated mid elements in janus subscription offer

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2917]
It´s not really an error but looks kind of seldom to me.
I have duplicated mid elements when i have an offer for a videroom subscription.

If you need a full sdp let me know. Here just a piece showing one audio and video section.

v=0
o=- 1646747970996154 6 IN IP4 10.20.3.220
s=VideoRoom R_b296a3e4fc164e8987041bf360ccb75b
t=0 0
a=group:BUNDLE 0 1 2 3
a=ice-options:trickle
a=fingerprint:sha-256 BD:D6:4A:F2:C7:FE:3E:9F:AB:3C:6C:BF:67:CE:B1:BD:FF:2F:E4:B6:28:70:DE:A5:99:C6:90:41:AA:9D:C6:2C
a=extmap-allow-mixed
a=msid-semantic: WMS janus
a=ice-lite
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 10.20.3.220
a=sendonly
**a=mid:0**
a=rtcp-mux
a=ice-ufrag:rUnC
a=ice-pwd:NgRqhL4BT5gezHsU96tNBi
a=ice-options:trickle
a=setup:actpass
**a=mid:0**
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:111 useinbandfec=1;stereo=1
a=msid:janus janus0
a=ssrc:3771923514 cname:janus
a=candidate:1 1 udp 2015363327 10.20.3.220 20083 typ host
a=candidate:2 1 tcp 1015021823 10.20.3.220 0 typ host tcptype active
a=candidate:3 1 tcp 1010827519 10.20.3.220 20066 typ host tcptype passive
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 10.20.3.220
a=sendonly
**a=mid:1**
a=rtcp-mux
a=ice-ufrag:rUnC
a=ice-pwd:NgRqhL4BT5gezHsU96tNBi
a=ice-options:trickle
a=setup:actpass
**a=mid:1**
...

**Comment by lminiero** [comment]
Good catch! I suspect it may be because there's two different places where we create the "mid" attribute:

https://github.com/meetecho/janus-gateway/blob/master/src/sdp-utils.c#L1675 (`janus_sdp_generate_offer_mline`)
https://github.com/meetecho/janus-gateway/blob/master/src/sdp.c#L1465 (`janus_sdp_merge`)

Simply removing one of the two is not an option: the former is needed to allow plugins to specify a `mid` for tracks themselves, for instance (so that the core is then aware of it), while the latter is needed in general as it's where the core adds the `mid` attribute to the SDP that will be sent to users via Janus API. The second is definitely needed because plugins may not specify a `mid` themselves (only some plugins do), and I guess is the reason why you see it twice (both plugins and core add the attribute).

I'll think about how the duplicate can be avoided in the core: one option may be to have the core strip that attribute when it receives it from a plugin SDP (it's sufficient for the core to parse it, so that it's aware if there's a new mid to take into account). At any rate, it shouldn't be a breaking bug, since it's always the same `mid` value anyway, so I'll just mark this issue as an enhancement request.

**Comment by JanFellner** [comment]
Yeah i would also not have seen this as a bug if the mid is is showing same value in the same segment.
However if you look at the sdp you are kind of a bit irritated ;]

**Comment by JanFellner** [comment]
✔ checked with #48c90574 looks good .)
