### ISSUE TITLE
[1.x] I'm writing a js client for video room plugin, I want subscriber to request `join` without specifying the `streams` field.

### ISSUE THREAD

**Issue by lileiseven** [meetecho/janus-gateway#2932]
**What version of Janus is this happening on?**
1.0.0

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
No

**Additional context**

I'm writing a JS client for video room plugin.

When a subscriber makes a `join` request, if the `streams` field is not specified, I get an error.

```
send: 
{
  request: 'join',
  room: 1000,
  ptype: 'subscriber',
}

received: Error: (429) Missing mandatory element (feed)
```

I want subscriber to request `join` without specifying the `streams` field. Because I will specify in the `subscribe` request.

```
{
  request: "subscribe",
  streams: [...]
}
```

**Comment by lminiero** [comment]
You can't, a join must always be done. Closing as not a code issue.

**Comment by ollerenius** [comment]
Correct me if I'm wrong, but should it not be possible to set up an incoming peer connection even if there are no other publishers in a room? My use case is a conference room where users can join whenever they want. I would like to set up both peer connections immediately when joining a room, regardless of if anyone else is currently there, and then add streams using the `subscribe` request when someone else joins. Janus currently does not allow this, since the `join` request cannot take an empty list of streams.

Unless it is technically impossible to set up the incoming peer connection when there are no other publishers, I think this would be a nice feature.

To clarify: I mean "incoming" and "outgoing" from the client's perspective.

**Comment by lminiero** [comment]
That's currently not possible in the VideoRoom plugin. While this may change in the future, we don't know if/when that will happen. As such, creating a subscription at the moment requires at least someone to subscribe to.
