### ISSUE TITLE
Missing .nfo files

### ISSUE THREAD

**Issue by JiaxianFeng** [meetecho/janus-gateway#2933]
I'm using the videoroom plugin, and the audio and video recordings are created in the appropriate directory, but there are no .nfo files.How to play VideoRoom recording?

**Comment by raviprakash007** [comment]
The same problem I m facing when more than 25 parallel recordings are there. The recording is there but .nfo files are not there

**Comment by lminiero** [comment]
Only the Record&Play plugin generates `.nfo` files. If you want `.nfo` files for `.mjr` recordings generated by other plugins, it's up to you to create them, and then let the Record&Play plugin be aware of them.

That said, that's not what you use for recordings like that, especially when you have a lot of parallel recordins (e.g., because they were part of a conference). You'll want to [convert](https://janus.conf.meetecho.com/docs/recordings) those recordings to a playable format instead, and then maybe mix them together using an external tool.

All this is out of scope here, please check the [group](https://groups.google.com/g/meetecho-janus) for more info or help on that.
