### ISSUE TITLE
[0.x] - Janus SIP Plugin does not respect the expire time defined by the SIP registrar server when using TCP transport.

### ISSUE THREAD

**Issue by abreualexandre** [meetecho/janus-gateway#2950]
When using UDP transport (force_tcp=false) the SIP Register handshake works as expected, that means, the client learns and respect the expire value defined by the SIP server.

However, if force_tcp=true, the above does not happen, the client keep sending the re-register at a fixed interval of 3600 secs and ignores the server value. So, if the server defines a lower expire time, the client will lost its register/contact.

Tested on v0.12.0 with sofia-sip 1.12.11. 

Easily reproducible with Asterisk and a PJSIP endpoint with options:

maximum_expiration=60
default_expiration=60
minimum_expiration=60

A quick review on the latest 1.13.X release and nothing related to that was fixed.

**Comment by lminiero** [comment]
If that's how the library behaves, I'm afraid there's not much we can do in Janus itself.

**Comment by abreualexandre** [comment]
I went ahead and tested against FreeSwitch v1.10~64bit and it worked. The gateway register on top of TCP respect the server side expiration time. The test was done on the same Asterisk endpoint that I tested with Janus (60secs).

**Comment by lminiero** [comment]
Have you checked which version of Sofia that FS uses, and if you're using the same one in Janus? Not sure if they use NTA instead of NUA (as we do), since with NUA it's the library itself that takes care of most of the heavy lifting: I'd expect the NUA to deal with updating the timers internally, rather than us having to do something (not sure what) in `nua_r_register`.

**Comment by abreualexandre** [comment]
I would bet 1.12.X for FS. It does not seem to have much activity on the tag v1.10.0 that I was using to test. The last commits are pretty old. Besides that, I make another test: I built the latest Janus (v0.12.0) linked to Sofia SIP 1.13.7 and the issue is still reproducible. 

Starting the debug mode, FS uses NTA to create and control the transaction but it seems that the expire value is done by nua_dialog()

[...]
nta.c:3304 agent_recv_response() nta: received 200 OK for REGISTER (50690105)
nta.c:3371 agent_recv_response() nta: 200 OK is going to a transaction
nta.c:9584 outgoing_estimate_delay() nta_outgoing: RTT is 2.039 ms
tport.c:4240 tport_release() tport_release(0x7f3d40016f90): 0x7f3d4001a080 by 0x7f3d4001b370 with 0x7f3d40010660
**nua_dialog.c:564 nua_dialog_usage_set_refresh_range() nua(): refresh register after 45 seconds (in [15..45])**
nua_stack.c:271 nua_stack_event() nua(0x7f3d5000ada0): event r_register 200 OK
nta.c:8733 outgoing_free() nta: outgoing_free(0x7f3d4001b370)
tport.c:2304 tport_set_secondary_timer() tport(0x7f3d40016f90): reset timer
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:366 nua_handle_magic() nua: nua_handle_magic: entering
[...]

**Comment by lminiero** [comment]
Just tested with an Asterisk endpoint configured with a much shorter Expored and it works just fine for me, on TCP too: using Wireshark I can see the session being refreshed regularly (about every 25s, with a 60s Expires value). My Fedora ships Sofia SIP 1.13.4, not sure if that counts.

**Comment by abreualexandre** [comment]
Hmm, weird. Did you configure a lower registration_ttl in janus.plugin.sip.jcfg? Or it's the default value? I'll setup Fedora enviroment here.

**Comment by lminiero** [comment]
No, I left the default registration timer in the SIP plugin (3600) and specified a lower one in Asterisk instead, as you suggested. I had then users register using both UDP and TCP (at different times), and in both cases a registration refresh was sent every 25s or so, rather than after an hour. As such, I don't think there's an issue in Janus, since it seems to be something the Sofia SIP stack should be doing automatically, and it looks like more recent implementations (like the one I have installed) do.

Closing this issue as a consequence, but feel free to provide more information if you still think there's something we should do in Janus instead.
