### ISSUE TITLE
[1.x] Suggestion: add the feed IDS for the subscriber's data stream

### ISSUE THREAD

**Issue by jamken** [meetecho/janus-gateway#2967]
**What version of Janus is this happening on?**
1.0.1

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
From the janus_videoroom_subscriber_streams_summary()

```
		json_t *m = json_object();
		json_object_set_new(m, "type", json_string(janus_videoroom_media_str(stream->type)));
		json_object_set_new(m, "active", (ps || stream->type == JANUS_VIDEOROOM_MEDIA_DATA) ? json_true() : json_false());
		json_object_set_new(m, "mindex", json_integer(stream->mindex));
		json_object_set_new(m, "mid", json_string(stream->mid));
		json_object_set_new(m, "ready", g_atomic_int_get(&stream->ready) ? json_true() : json_false());
		json_object_set_new(m, "send", stream->send ? json_true() : json_false());
		if(ps && stream->type == JANUS_VIDEOROOM_MEDIA_DATA) {
			json_object_set_new(m, "sources", json_integer(g_slist_length(stream->publisher_streams)));
		} else if(ps && stream->type != JANUS_VIDEOROOM_MEDIA_DATA) {
			if(ps->publisher) {
               .......
```

The current code only give the number of feed on the subscriber data stream, which is very hard for the client to know and maintain who give his data packet to this subscriber and it's a important infomation for the applicawtion.

Suggest: sources field maintain a feed ID list instead of a number.

**Comment by lminiero** [comment]
I don't think the user will have problems figuring out who sent them a packet, since the label will be the participant ID, and they should know the participant IDs from all the notifications the plugin sends (otherwise they wouldn't have subscribed in the first place). That said, I agree that having an explicit list of IDs in the data subscription might help: it will need to be a separate property, though, since I'm not going to just change the type of an existing one as that would cause a breaking change.

I'll add this to the TODO list, but I'm not sure when I'll have time to work on that.

**Comment by jamken** [comment]
That's OK, Actually, if there is an explicit list of IDs in the data subscription, it would be easy for me to implement Janus-cloud(https://github.com/OpenSight/janus-cloud).
Thank you for your quickly reply
