### ISSUE TITLE
Unable to identify multiple subscriptions to the same feed

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#3024]
I am posting it here as i see this kind of a lack in the current subscription implementation.

Context:
- In a meeting scenario (videoroom) i have differnt styles of streams.
- In a side bar is see small streams (simulcast low substream)
- In the center area i see larger streams (simulcast m/h substream)

In certain scenarios both streams may show the same feed.

As subscription updates may come async i have no context if a change is related to a subscribe / unsubscribe operation.
So i need to be able to identify the subscribed streams in the updated event by other parameters.

The issue in this context is that i cannot differ the streams as they have no own unique identifier.

Solution to solve it would be to have an option to add an opaque_id to the subscribe request.
In see no need to be able to unsubscribe or configure based on that opaque_id.
The only purpose would be to have an own id to match the streams from the updated event with the effective subscription in the internal logic.

Further complexity would come if i use switch on the larger streams, then i have absolutly no clue which stream in the updated belongs to what.

Any thoughts about this? Don´t think that making a PR for that should be such a big issue.
Actually only the subscribe needs to read it, put it into the internal store and on every updated we add it as parameter to the streams list.

**Comment by lminiero** [comment]
I'm not sure I understand the issue. For each subscribed stream you do have a unique ID, the `mid` in the subscription; if the problem is you want to know who that's from in a subscription update, you can couple that with the `feed_id` and `feed_mid` which uniquely identify the source. This way, even if you're subscribed twice to the same stream, those three identifiers together will tell you what's what.

I don't understand why it matters whether a change comes from subscribe or unsubscribe either, especially considering we now have a request called "update" where you can do both things at the same time. No matter the request, you always get an updated snapshot of all the subscribed streams in each event, meaning you can reconstruct your state out of that, and using the three IDs I mentioned as a way to figure out what's new and what went away.

An opaque_id wouldn't solve anything, since as we already discussed you have no guarantee that each subscribe/unsubscribe/update request will generate an event, since some of them may be grouped in a single one if we're still processing a previous update.

**Comment by JanFellner** [comment]
The issue is the asynchronity.

I do a subscribe or unsubscribe but the response tells me updating.

Later i get an updated event and i have no property in there that allows me to distinguish the two subscriptions on the same feed (one small, the other large one).

Let´s say i subscribe the same feed two times, one simulcast low, the other simulcast large. 
I get an updating event so the event comes async.

I get the updated event with the streams list. I see now two times the feedid.
Which one is which one?

The opaque id would allow me to distinguish the two subscriptions on the same feed.

**Comment by lminiero** [comment]
> Which one is which one? the feed, the mid, is the same, the subscription mid is announced with that updated event, so i have that here the first time.

Then I think the only additional info you need in that block is the specific simulcast substream you're subscribed to for that specific stream: otherwise, they _are_ the same source feed, and so it doesn't really matter which is which. Again, an opaque_id would solve nothing, because if you send

    subscribe(opaque=a)
    subscribe(opaque=b)
    subscribe(opaque=c)

you may get only two updates

    updated(opaque=a)
    updated(opaque=c)

because "b" and "c" were handled togerher, or even just one

    updated(opaque=c)

if even "a" had been kept on hold because we were processing a previous subscription change. Unless you mean a per-stream opaque ID of some sort, rather than a per-request one? Which I still think wouldn't work, because if you set that opaque ID in a request that will then not generate a notification itself, you'll never get it in any event.

**Comment by JanFellner** [comment]
I see the need for a per subscribed feed+mid opaque id, not per request.

If i place multiple subscribe operations after another and get update events (combined or separated) the feed id - mid is no sufficient from my point of view as i cannot map them to the original purpose of the subscribe request.

I think it makes more sense if i place a PR for that topic cause i think the changes are trivial but a big benefit.

**Comment by lminiero** [comment]
If you can submit a PR to better explain your purpose it will help, but I cannot guarantee it will be merged, since it may conflict with the way I think the API should work. Once I understand the exact issue and the implications on the API, I can maybe think of a cleaner way.

**Comment by JanFellner** [comment]
Here we are, the changes are rather simple but super helpful to be able to identify different subscribe operations on the same feed in the updated event.

From the transport perspective it looks like this:

`{
  "_": "2022-07-13T14:03:04.291Z - ws - out",
  "janus": "message",
  "transaction": "S_message_3_7",
  "handle_id": 6215227285994329,
  "session_id": 3763906688836544,
  "apisecret": "janus_4$estos",
  "timeout": 500,
  "body": {
    "request": "join",
    "ptype": "subscriber",
    "room": "R_3275a80504ff4211989552a8e69a888e",
    "streams": [
      {
        "feed": "268f956d-7224-4f67-8e37-50eaa28a7228",
        "mid": "0",
        "opaque_id": "S_6c6bf6d1275c4901915c4fb846f40ee5"
      },
      {
        "feed": "268f956d-7224-4f67-8e37-50eaa28a7228",
        "mid": "1",
        "opaque_id": "S_6c6bf6d1275c4901915c4fb846f40ee5",
        "substream": 2,
        "temporal": 1
      }
    ]
  }
}

{
  "_": "2022-07-13T14:03:04.928Z - ws - out",
  "janus": "message",
  "transaction": "S_message_3_8",
  "handle_id": 6215227285994329,
  "session_id": 3763906688836544,
  "apisecret": "janus_4$estos",
  "timeout": 500,
  "body": {
    "request": "join",
    "ptype": "subscriber",
    "room": "R_3275a80504ff4211989552a8e69a888e",
    "streams": [
      {
        "feed": "268f956d-7224-4f67-8e37-50eaa28a7228",
        "mid": "0",
        "opaque_id": "S_6c6bf6d1275c4901915c4fb846f40ee5"
      },
      {
        "feed": "268f956d-7224-4f67-8e37-50eaa28a7228",
        "mid": "1",
        "opaque_id": "S_6c6bf6d1275c4901915c4fb846f40ee5",
        "substream": 2,
        "temporal": 1
      }
    ]
  }
}

`

**Comment by JanFellner** [comment]
Changed the PR from my private janus fork to the estos fork...

**Comment by BrendanBall** [comment]
This feature would make things a lot simpler for us as well.
I don't believe that it's strictly necessary, since you can correlate the streams to the subscribe request if you take into account all the params, however we currently have a use case to subscribe to the exact same stream twice (mostly because of how the client implements subscriptions for different UI elements), which causes some issues with correlating it back to a subscribe request, although since the 2 streams are exactly the same, you can just randomly assign them back to the 2 subscribe requests.

**Comment by JanFellner** [comment]
I see it rather difficult to follow the stream using the parameters as things are (metioned initially) happening async. So I tell what I want. I may also do configure requests and I cannot predict when a change in the simulcast params will be part of the streams list or not. As we have two different streams I could try to follow but the effort to that is so much hier that to have a dedicated correlation id between the subscribe request and the streams list. This is simply the missing puzzle piece to us.
But I hope @lminiero  also now sees the improvement in it 😉

**Comment by JanFellner** [comment]
As we have merged 🤘👍https://github.com/meetecho/janus-gateway/pull/3027 we can now close it.
@BrendanBall check if it improves your side we definetly simplified the whole subscription implementation, especially the switching.

**Comment by BrendanBall** [comment]
Thanks @JanFellner. Based on this [comment](https://github.com/meetecho/janus-gateway/pull/3027#issuecomment-1186872434), you said
> It should not be possible to change it. If thats currently the case i need to check where on an update this is overwritten.

Our client is currently sending a new ID on every subscribe request, even if the track hasn't changed. 
What would happen in this case? Would it create duplicate streams for every new ID? Hopefully our client can be improved to reuse IDs for existing tracks.

**Comment by BrendanBall** [comment]
I was actually wrong about our client. This feature maps 1-1 to how we've implemented the ID on our side.
I've just refactored our app to use this new feature and it simplifies everything a lot. 
I was able to delete a whole bunch of code and basically just do simple transformations instead of having complicated matching logic.

Thanks @JanFellner for implementing this and thanks @lminiero for merging this :smile:
