### ISSUE TITLE
[1.x] Functionality regressions in PR #3003

### ISSUE THREAD

**Issue by agclark27** [meetecho/janus-gateway#3034]
Since PR #3003, we've observed two primary issues.

First, the consentDialog callback is no longer called (true or false) under any circumstance, and there are no longer any references to it in janus.js apart from some definitions of it. This was previously used to paint a modal over the page when the permission dialog is shown and remove the modal upon a success or error condition.

Second, there was previously a way with the media object to get the screenshare content with system audio using { video: 'screen', captureDesktopAudio: true }. With tracks, a track of [ type: 'screen', capture: { ... } ] has no way to get in a system audio constraint because the capture object is forced into the video constraint with: constraints.video = track.capture;

For the first issue, we would propose that either the consentDialog callback be called with a similar behavior to before or the callback be deprecated/removed entirely if it's no longer going to be called from anywhere.

For the second issue, we would propose being able to pass in a track like [ type: 'screen', capture: { video: { frameRate: 15 }, audio: true } } ] and then set constraints = track.capture instead of constraints.video = track.capture.

Open to ideas on both of these here.

**Comment by lminiero** [comment]
Good catch on the consent dialog, that was probably an oversight on my part while I was working on the refactoring, I'll add it back in shortly.

On desktop audio, that's going to be harder to do, due to how we now ask for audio and video separately. Grouping is supported, but at the moment only for getUserMedia, not getDisplayMedia. I'm about to go on my holiday break, so I won't work on this until I get back. If you care about this particularly, you can either capture the desktop audio externally and pass it as a track, or work on a PR that adds support for it that we can review when we're back.

**Comment by agclark27** [comment]
It's suitable for our purposes to invoke getDisplayMedia externally and then capture and pass in the external tracks, so we're good from our end. Here's what we're doing, in case it's helpful to others.

`
const stream = await navigator.mediaDevices.getDisplayMedia({ video: { frameRate: 15, height: 720, width: 1280 }, audio: true });
const tracks = [];
for (let track of stream.getVideoTracks()) tracks.push({ type: 'screen', capture: track });
for (let track of stream.getAudioTracks()) tracks.push({ type: 'audio', capture: track });
room.createOffer(
  {
    tracks: tracks,
    ...
`

Enjoy your holiday break!
