### ISSUE TITLE
Videroom multistream bug after unpublish/publlish

### ISSUE THREAD

**Issue by UserSense** [meetecho/janus-gateway#3055]
**What version of Janus is this happening on?**
const char *janus_build_git_sha = "bc8cc9c3f64f07fb73da21d034b6748a6b8165c4";
const char *janus_build_git_time = "Mon Feb 14 12:34:55 UTC 2022";
int janus_version = 1000;
const char *janus_version_string = "1.0.0";
const char *libnice_version_string = "0.1.18.1";

v1.0.4

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
No idea

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
Videroom multiroom.

Publisher A (video and audio)
Publisher B (video and audio)

Step 1: A and B join the room -> Both streams are visibile
Step 2: B Leaves the room/unpublish -> A can no longer see B (as expected)
Step 3: B joins the room again and can see its own feed and A. A can not see B (empty blank or black stream). onremotetrack gets fired for the new tracks of B on A. Stream gets added, but stays blank. Both these tracks have the same Id as previous tracks. Both tracks have readyState: "ended". This is problematic.

Even if B closes its browser between step 2 and 3 it fails. Even after cleaning all the cache. The only way to get it working again is to let A unpublish as well, before both join again.

Both my own implementation and the online videoroom multistream example have this issue.

Janus version 1.0.4

**When it works**
The odd thing is that it works in the following situation:

1. B unpublish
2. A receives multiple onremotetrack(track,mid,false)
3. Normally the code would stop the specific tracks associated with the specific stream. If we disable/remove `mst.stop()` in `onremotetrack `in `subscribeTo` everthing works. Removing the MediaStream from the remoteTrack array is not an issue.
4. B rejoins

Issue occures in Edge,Chrome,Firefox, Samsung Internet (Android)

I noticed that Janus is reusing track-ids. Especially after having closed browser as publisher, and having rejoined the room. One would expect fresh track-ids.

**Possible solution**
1. Do not reuse trackIds in the same videoroom. Gives issues with the readyState of the track.
2. remove mst.stop in onremotetrack (not ideal).

**Comment by lminiero** [comment]
The commit you linked is from 6 months ago. Have you tried the latest master too? We also refactored janus.js considerably, recently, so you may want to make sure that's up to date too.

**Comment by lminiero** [comment]
Nevermind, I managed to replicate this. It may indeed be a consequence of the recent janus.js refactoring, as I don't remember this happening before. I'll have a look.

**Comment by lminiero** [comment]
> I noticed that Janus is reusing track-ids. Especially after having closed browser as publisher, and having rejoined the room. One would expect fresh track-ids.

Nuking the publisher is irrelevant. In this case track IDs are re-used on the subscriber side, and that subscriber never left the room. We're currently using the mid as the (basis of the) track ID, which is why it ends up being reused, since when B rejoins they're re-assigned the same m-lines they were on before as far as the subscriber is concerned. I don't think forcing a fresh track ID in this scenario will be easy, since we don't have explicit mechanism to decide something's new or not.

**Comment by lminiero** [comment]
As a short-term fix I'll disable the .stop() as you suggested, while we think of a better fix.

**Comment by UserSense** [comment]
Finding a solution will be difficult. I did try multiple different possible solutions, but no luck.

**Comment by lminiero** [comment]
> Do not reuse trackIds in the same videoroom. Gives issues with the readyState of the track.

This doesn't seem to be working. I've made a tentative patch that generates random IDs for tracks and it causes the same problem. At this point, I have to assume it may indeed have something to do with stopping tracks. If I think about it, the fact we close remote tracks seems silly, since closing a track means closing its source, but that only makes sense if the track is local. The life cycle of a remote track is dictated by the SDP instead, and so we may want to avoid stopping remote tracks instead (which we do in a few other demos as well).

**Comment by lminiero** [comment]
We decided to just stop calling .stop(), for the reasons explained above. The PR is linked above.
