### ISSUE TITLE
[1.x] extra sdp offer being sent by Janus to participants when call is torn down

### ISSUE THREAD

**Issue by sowmyatv** [meetecho/janus-gateway#3083]
**What version of Janus is this happening on?**
v1.0.4

**Have you tested a more recent version of Janus too?**
No, there is v1.1.0 released 4 days back and this issue is not tested on that. 

**Was this working before?**
This issue is seen on the multistream version, previous versions are fine

**Is there a gdb or libasan trace of the issue?**
janus log file attached

**Additional context**
When a call that involves a videoroom is ended, the originator of the call sends a destroy request to Janus for the videoroom plugin. At this point Janus sends an extra SDP offer to all the remaining participants. The handle of the videoroom being destroyed is 707672427256870. Updated the attachment with highlighted sections for publisher SDP (blue), subscriber SDP (pink), extra SDP (yellow)

[janus-multistream-log.pdf](https://github.com/meetecho/janus-gateway/files/9734832/janus-multistream-log.pdf)

**Comment by lminiero** [comment]
That's probably because we automatically send SDP updates to subscribers when a participant leaves: since a "destroy" kicks all publishers and closes their PeerConnections, that automatic mechanism kicks in. I'll have to check if we're missing a check like "if the room has been destroyed, don't send anything", which in case we'll have to add.

**Comment by lminiero** [comment]
The above commit fixes it for me, or at least I can't replicate the problem anymore.
