### ISSUE TITLE
[1.1.0] When using TURN REST API client, parameters are not uri encoded.

### ISSUE THREAD

**Issue by croudet** [meetecho/janus-gateway#3112]
**What version of Janus is this happening on?**
v1.1.0

**Have you tested a more recent version of Janus too?**
Yes. latest code.

**Additional context**
When using the TURN REST API client, parameters ([api_key](https://github.com/meetecho/janus-gateway/blob/master/src/turnrest.c#L132), [user](https://github.com/meetecho/janus-gateway/blob/master/src/turnrest.c#L143))  are not uri encoded.

**Comment by lminiero** [comment]
Yes I guess that's likely, since we're just crafting the query string manually, and then passing it via `CURLOPT_POSTFIELDS` (which according to the documentation doesn't encode the data itself). I guess we'll have to use [curl_easy_escape](https://curl.se/libcurl/c/curl_easy_escape.html) on the parameters before writing them to the query string.

**Comment by lminiero** [comment]
Should be fixed now, thanks for spotting this!
