### ISSUE TITLE
[1.x] Resource leak in janus_recorder_free?

### ISSUE THREAD

**Issue by RSATom** [meetecho/janus-gateway#3128]
Hello.
It looks like mutex from `struct janus_recorder` doesn't destroying correctly.
I see initialization https://github.com/meetecho/janus-gateway/blob/e139a1c69ad0f9f7fc662e73ebcdfad675591e79/src/record.c#L252
but don't see `janus_mutex_destroy` in `janus_recorder_free`
https://github.com/meetecho/janus-gateway/blob/e139a1c69ad0f9f7fc662e73ebcdfad675591e79/src/record.c#L65-L83

**Comment by lminiero** [comment]
We're missing a `janus_mutex_destroy` in a ton of places, actually: we do make use of them in the core for more than just `record.c`, but we don't have a destroy anywhere. To be honest I'm not sure if or how much of a leak that is, considering we never allocate anything and. to my knowledge, neither do glib mutexes.

**Comment by lminiero** [comment]
I see we do have calls to the destroy in plugins, so I guess that, at the very least as a matter of consistency, we should probably ensure the core does too.

**Comment by RSATom** [comment]
I just worrying according to docs for  [g_mutex_clear](https://docs.gtk.org/glib/method.Mutex.clear.html) it's really do some cleanup: 
> Frees the resources allocated to a mutex with g_mutex_init().

so every `g_mutex_init` should be paired with `g_mutex_clear`...

**Comment by lminiero** [comment]
Yes, but if you look at the code, glib uses either futex or pthread internally, which means clear simply calls pthread_mutex_destroy which, IIRC, for "regular" mutexes (e.g., non recursive) is basically a non-action. That's why I was wondering if it's actually needed at all (especially since I've recently stumbled on a Janus instance that has been running for 9 months without stop with no apparent signs of leaks). That said, I agree that formally, since there's a clear function, it should probably be called.
