### ISSUE TITLE
Janus + libnice 0.1.4 + Coturn TURN server does not awknolegde turn session keep-alive

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#315]
When using Janus (GIT HEAD) with libnice 0.1.4 against GIT HEAD of Coturn server [https://github.com/coturn/coturn], streaming plugin sessions (and perhaps other plugin sessions as well) die after 10 minutes at the TURN server. Janus keeps sending data to the TURN server, but the TURN session is terminated by the TURN server because libnice 0.1.4 did not send a correct turn_session_keepalive. 

The 10 minute mark stems from RFC5766:
> The frequency of the Refresh transaction is determined by the
>    lifetime of the allocation.  The default lifetime of an allocation is
>    10 minutes -- this value was chosen to be long enough so that
>    refreshing is not typically a burden on the client, while expiring
>    allocations where the client has unexpectedly quit in a timely
>    manner.

https://tools.ietf.org/html/rfc5766 - section 2.2

Although technically not a problem of Janus (the problem is in the interplay between the ancient libnice 0.1.4 and coturn server, Janus cannot be compiled against a newer version of libnice because of issue #154 . We have verified that the 10 minute turn session expire problem is resolved by using a newer libnice version (e.g. GIT HEAD or libnice-0.1.13).

Ps. I was not sure if I should have opened a new topic or updated #154. At least I wanted to report the issue which hopefully helps out some other people running in this problem. Feel free to close this issue.

**Comment by lminiero** [comment]
Not sure if it's a matter of Coturn version, but the ubuntu14+libnice0.1.4 combo is one we have on several deployed server and I don't recall ever encountering this issue. IIRC though we make use of an older version of Coturn (4.3.3.1?), not sure as I don't usually handle the setup directly.

About the issue on #154 I still have to investigate it deeply: I recently updated my laptop to Fedora 22 which ships 0.1.13, and so far I haven't seen this problem. I never made an intensive usage of Janus on my own setup, though.

**Comment by lminiero** [comment]
Editing myself... are you trying to make Janus use TURN directly? If so, you don't really need to do that, unless the machine deploying Janus is behind restrictive components, which should almost never be the case (Janus is usually assumed to be on a public address, or in the worst case simply behind a NAT).

If you want your users to use TURN, that's something you need to configure on the client side, *NOT* within Janus. Quoting the FAQ:

```
22. I enabled TURN in the Janus configuration, but my clients behind a firewall can't connect

As explained in the janus.cfg documentation, the TURN settings you configure there refer to Janus itself, not the clients that make use of its services. This means that, whether you configure a static TURN server and the related credentials, or the REST API client stack to retrieve them dynamically, you're asking Janus to gather relay candidates for ITSELF. This is only useful if you know that your Janus instance will not be deployed on a public address (as it usually will) but will instead potentially sit behind a restrictive component like a firewall, or if you simply want to limit the number of open ports and so force all media traffic to go through the TURN server port alone.
```

Unless configuring Janus to use TURN was done on purpose?

**Comment by rayvbr** [comment]
We've deployed Janus on an Amazon EC2 instance. Since we had some connectivity issues, we configured a Janus TURN server address (the user devices are configured independently and may or may not have the same TURN server configured). 

In any case, Janus shouldn't use TURN unless absolutely necessary, right? Or does the fact that we configured a TURN server somehow force Janus in using it?

**Comment by rayvbr** [comment]
BTW: Regarding coturn, we currently use static authentication, without the REST API. Could this have something to do with the timeout issue?

**Comment by lminiero** [comment]
When you deploy on Amazon, the only thing you need to do usually is setting up a STUN server for Janus to use, because of the NATted, although 1-1, Amazon employs for its machines. Using the "public IP" setting, which seems like the best approach considering the 1-1 mapping, does _NOT_ work as expected and can lead to issues: STUN solves the issue.

Configuring TURN for Janus is useless if Janus is by itself reachable somehow. If you're not behind restrictive firewalls, it's wasted cycles, as you're gathering TURN addresses you'll never use. My guess is that in your case TURN is always being used because you didn't setup a STUN server for Janus: this means the only candidates Janus advertizes are a private address (the private EC2 instance address) and the relay candidates, and so the relay candidates (TURN) are used.

Just remove TURN from janus.cfg and set STUN instead.

**Comment by lminiero** [comment]
> BTW: Regarding coturn, we currently use static authentication, without the REST API. Could this have something to do with the timeout issue?

I don't think so, it's more likely to happen the other way around, e.g., if you have credentials that expire in the meanwhile.

**Comment by rayvbr** [comment]
Thanks for the hint. There seems to be an incompatibility between libnice 0.1.4 and a new coturn in general. With libnice 0.1.4, and the newest coturn release, STUN doesn't seem to work. Since STUN didn't work, Janus reverted to TURN (which resulted in the 10 minute issue). 

If we use the same version of libnice (0.1.4) with a public STUN server (e.g. stun.l.google.com), everything works fine. Applications that use a newer version of libnice also work with the newer version of coturn. But the combination of libnice 0.1.4 and a recent version of coturn presents issues with both STUN and TURN.

**Comment by lminiero** [comment]
Thanks for the heads up! We always use different servers for STUN and TURN, I guess that's why we never noticed.

**Comment by tgabi333** [comment]
Just for the record: RHEL 7.3 contains libnice version 1.0.3 which has the same bug, no keep-alive.
