### ISSUE TITLE
[1.x][0.x][Videoroom] It's possible to escape from rec_dir with "../"

### ISSUE THREAD

**Issue by RSATom** [meetecho/janus-gateway#3153]
With the latest `master` it's possible to write .mjr files to any folder not specified in `protected_folders`. I think it's not expected and not obvious behavior.

And I think the reason is here:
https://github.com/meetecho/janus-gateway/blob/a5c0c0b2154ae7db8d840791ccc85f12d440990c/src/record.c#L144-L146
i.e. Janus warns about problem, but allows to go further and creates file. I think it should return NULL at that point.

0.x has the same issue:
https://github.com/meetecho/janus-gateway/blob/6c0b257c2b00124b58a7593f1445155f86939c50/record.c#L143-L145

**Comment by lminiero** [comment]
> With the latest `master` it's possible to write .mjr files to any folder not specified in `protected_folders`. I think it's not expected and not obvious behavior.

Did you mean "any folder specified in..", rather than "not specified"? If the code as it is is already preventing writing to a protected folder, then it's doing its work. Can you elaborate on the issue you spotted, maybe with a practical example?

**Comment by RSATom** [comment]
Default `protected_folders` content is:
```
	protected_folders = [
		"/bin",
		"/boot",
		"/dev",
		"/etc",
		"/initrd",
		"/lib",
		"/lib32",
		"/lib64",
		"/proc",
		"/sbin",
		"/sys",
		"/usr",
		"/var",
			# We add what are usually the folders Janus is installed to
			# as well: we don't just put "/opt/janus" because that would
			# include folders like "/opt/janus/share" that is where
			# recordings might be saved to by some plugins
		"/opt/janus/bin",
		"/opt/janus/etc",
		"/opt/janus/include",
		"/opt/janus/lib",
		"/opt/janus/lib32",
		"/opt/janus/lib64",
		"/opt/janus/sbin"
	]
```
And it's really not possible to write to any of them. But it doesn't prevent write to other folders. For example, on my host I have `/mnt` and `/home` (obviously) and other dirs inside `/opt` except `/opt/janus`, and I would prefer to protect that folders too. So I've tried to set `rec_dir` to something like `/opt/janus/recordings`, but I was surprised I can pass something like `filename = "../recording"` to `publish` request, and file will be created in `/opt/janus`. The same way  I can access any other folder not specified in `protected_folders` and I think it's not right behavior.

**Comment by lminiero** [comment]
> And I would prefer to protect that folders too

To protect those folders too, you need to edit the protected folders list in `janus.jcfg` to add your own. I personally don't think what you described is broken behaviour, since the final target is outside of the protected folders list, whether you got there via an absolute link or a relative one. The protected folders isn't meant as a way to prevent Janus from thinking a folder exists, but only from writing to those folders.

**Comment by RSATom** [comment]
With that approach every specific host should be reviewed and every folder treated as "not safe" for Janus recordings should be added to `protected_folders` - I believe it's a big pain for admins. Especially if take into account recording path comes from client. I.e. it's user decides where file will be created - in my opinion it can be even treated as a security issue. And without ability to limit recording path to some specific folder - the only safe way to use Janus recordings is through some middleware.
Also different plugins could wish limit recordings output to different folders, but with `protected_folders` it's not possible.

But I've got your point and just will fix that issue in my fork. Thanks!

**Comment by lminiero** [comment]
Notice that nothing forces you to run Janus as root: I don't in my private instances, for instances, and that automatically rules out a ton of folders yuou can write to, and can give you more flexibility as the OS level. On the fact that paths are user provided, that's a feature of the Janus API, which needs to be flexible: most instances will not expose the Janus API directly to end users, but will have wrapper applications controlling Janus instances and limiting what they can do to what application servers want them to do, which is the right way to do it (it's what we do in all our deployments). The Janus API should be seen more like a media server API than a consumer oriented one (even though it can be used as such). Plugins providing their own limitations is not something that can be fixed with two lines of code, since it would require a completely different approach (the recordings C API is part of the core) which is not planned.

Thanks for the feedback, though, this are useful discussions!

**Comment by RSATom** [comment]
> Notice that nothing forces you to run Janus as root

yep, that's why I prefer to use Janus as snap package. It's limited by design...

> The Janus API should be seen more like a media server API than a consumer oriented one (even though it can be used as such).

I think that sort of decisions should be mentioned somewhere in docs... I mean fact that Janus API should not be treated as safe and it's not recommended to expose it to public...

**Comment by dekeonus** [comment]
> most instances will not expose the Janus API directly to end users, but will have wrapper applications controlling Janus instances

I wouldn't be trusting a third party to sanitise user input into the API.

I consider this approach ( protected_folders = [] ) to be inverse to modern security best practices (default deny, poke exception allow holes): 
- Currently the system is default write anywhere, except these locations.
- Whereas modern security approach would be write nowhere except these locations.

**Comment by lminiero** [comment]
I'm happy to revisit approaches, into account this would be a breaking chance, since the current approach has been around a while. As usual, a pull request is a quicker and more effective way of getting us to go anything about it, since we're busy on many fronts and I don't know when I'd have time for this.
