### ISSUE TITLE
[1.x] Replace gethostbyname with getaddrinfo

### ISSUE THREAD

**Issue by bkmgit** [meetecho/janus-gateway#3156]
**What version of Janus is this happening on?**
Commit 963c4b6, current head of repository

**Have you tested a more recent version of Janus too?**
No - issue affects future releases

**Was this working before?**
Not applicable

**Is there a gdb or libasan trace of the issue?**
Not applicable

**Additional context**
When building for inclusion in Fedora, warning to replace `gethostbyname` with `getaddrinfo` is raised.  This will allow use of IPv6 addresses. `gethostbyname` appears at:
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_nosip.c#L2310
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_nosip.c#L2321
-  https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_sip.c#L6878
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_sip.c#L6889
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_audiobridge.c#L6570

`getaddrinfo` is used at:
- https://github.com/meetecho/janus-gateway/blob/master/src/turnrest.c#L268
- https://github.com/meetecho/janus-gateway/blob/master/src/events/janus_gelfevh.c#L162
- https://github.com/meetecho/janus-gateway/blob/master/src/ice.c#L1183
- https://github.com/meetecho/janus-gateway/blob/master/src/ice.c#L1241
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_audiobridge.c#L2257
- https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_audiobridge.c#L4708

Can make a pull request if of interest.

**Comment by lminiero** [comment]
> When building for inclusion in Fedora, warning to replace `gethostbyname` with `getaddrinfo` is raised

Is this a new warning on Fedora 38? I don't seem to be getting those on my build system on Fedora 37. That said, I agree that a more consistent usage would be useful, and that switching to `getaddrinfo` everywhere helps. If you have a PR ready, that would be welcome, otherwise I can look into making the changes myself. Thanks for the feedback!

**Comment by bkmgit** [comment]
This warning arises from Fedora tooling for inclusion as a package, it is not a compiler warning.  Can make a pull request within the next few days as would like to understand this a little better, but if you want to make the changes before then, that is fine.

**Comment by lminiero** [comment]
Ack, I'll have a look later today, to make sure such a change won't cause issues in existing features. As a side note, not sure if you'll attend FOSDEM in Brussels in a few days, but I'll be there, so in case I'd love to be able to say hello!

**Comment by bkmgit** [comment]
Only online.

**Comment by lminiero** [comment]
I just created a PR, linked above. It required many more changes than I originally anticipated, due to some assumptions the plugins were making on the address family of RTP streams. I plan to make some further changes before this is merged, but you may want to test this already, to check if the warnings you mentioned are solved.

**Comment by renich** [comment]
Will do. Thank you! :D

**Comment by lminiero** [comment]
Any feedback on the current state of the PR?

**Comment by renich** [comment]
Hey @lminiero, sorry for the super dalayed response. I'm gonna try and test this tomorrow morning and give you some feedback. Sorry for the huge delay once again.

**Comment by renich** [comment]
Hey @lminiero, in my test, it seems to fix the issue. 

https://bugzilla.redhat.com/show_bug.cgi?id=2121585#c61

We will still go through Fedora's copr build system in order to see if it passes that test. copr will install all packages and carry out some additional tests and the report will be public. I'll share it once we're done.

**Comment by renich** [comment]
And it seems to work. No more warnings. 

https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2121585-janus/fedora-rawhide-x86_64/05580064-janus/fedora-review/review.txt
