### ISSUE TITLE
[1.x] memory usage growing without explain

### ISSUE THREAD

**Issue by michelepra** [meetecho/janus-gateway#3165]
**What version of Janus is this happening on?**
1.1.1
I've tested on old version 0.11.2 with more disappointing results

**Is there a gdb or libasan trace of the issue?**
no output from libasan 

**Additional context**
use only nosip plugin with one handle per session, after hangup handle destroy session. The average peak usage is about 150 sessions with duration from few seconds to more than hour.

I have custom application that collect every 15 minutes `ps` output to monitor memory usage (RSS, the non-swapped physical memory that a task has used)
I notice that when janus has 0 session (after one working day) RSS it doesn't go down.
With janus 0.11.2 memory usage was more high, about 2gb per day, so becoming unusable very quickly. With janus 1.1.1 is better but not freeing when in idle (0 session)

Here one gif that show trend of memory usage grow (about 30MB) in one week (the downfall at 8 feb is when i enabled admin of http transport)

![janus](https://user-images.githubusercontent.com/11311941/218522193-3c6ab138-53f1-4b7e-aa60-73101a88ee76.gif)

Just now with only 6 active sessions memory usage is 167MB

![image](https://user-images.githubusercontent.com/11311941/218517737-4f0e90c9-acea-4a27-b632-1fd2b3645ef7.png)

I also try libasan with no output of some sort of leak.

The workaround now is to restart janus but is very annoying doing this on daemon process like janus is

**Comment by lminiero** [comment]
There's no leak we're aware of, and if libasan doesn't find anything it confirms it. If you compiled the Janus executable you're using with libasan support, it's libasan that makes the memory grow, since it keeps track of every single pointer and thread that was allocated in the life cycle of the application, without ever getting rid of it (since it will be needed when you close the application). If you compile without libasan memory will stay in shape, as long as you clean sessions/handles when you're done with them, of course.

**Comment by michelepra** [comment]
yes, of course!! The trend that i described and the screenshot is about janus without libasan. I replaced janus compiled without libasan after one week of janus compiled with libasan (and no output about unfortunately).

Yes in order i call detach for handles and destroy for session every time i end with.

One logging example

```
2023-02-13 07:30:18.360 [debug] JanusClient - --> - [{"janus":"hangup","transaction":"czczf_13","session_id":8593447264815865,"handle_id":4992312256465459}]
2023-02-13 07:30:18.360 [debug] JanusClient - <-- - [{"janus":"success","session_id":8593447264815865,"transaction":"czczf_13"}]
2023-02-13 07:30:18.361 [debug] JanusClient - --> - [{"janus":"detach","transaction":"czczf_14","session_id":8593447264815865,"handle_id":4992312256465459}]
2023-02-13 07:30:18.361 [debug] JanusClient - <-- - [{"janus":"hangup","session_id":8593447264815865,"sender":4992312256465459,"reason":"Janus API"}]
2023-02-13 07:30:18.361 [debug] JanusClient - <-- - [{"janus":"success","session_id":8593447264815865,"transaction":"czczf_14"}]
2023-02-13 07:30:18.362 [debug] JanusClient - <-- - [{"janus":"detached","session_id":8593447264815865,"sender":4992312256465459}]
2023-02-13 07:30:18.863 [debug] JanusClient - --> - [{"janus":"destroy","transaction":"czczf_15","session_id":8593447264815865}]
2023-02-13 07:30:18.863 [debug] JanusClient - <-- - [{"janus":"success","session_id":8593447264815865,"transaction":"czczf_15"}]
```

**Comment by atoppi** [comment]
According to your data, `ps` is still showing a _reasonable_ amount of allocated RSS memory.
I would not exclude a side effect of a custom memory allocator here, since some libraries we use do that indeed, like e.g. glib and sip-sofia.

However if the RSS is growing to worrying amounts, to the point that you need to force restart the process, then a leak could explain that. 

In that case we will need more info to investigate.
- try to find a reproducible case
- provide a js snippet if possible
- compile janus with debug flags (without libasan) and use `valgrind` to detect memory leaks. Be careful since `valgrind` will **REALLY** slowdown the server and likely report false-positives along with potential leaks.

**Comment by atoppi** [comment]
Also you could enable refcount debug, stop  the server after a leak and see if janus reports dangling reference counts.

**Comment by lminiero** [comment]
Any update on the info Alessandro asked for?

**Comment by atoppi** [comment]
> * i tried valgrind but janus is unusable, only after about 5 minutes the memory grows unacceptably for production server

Unfortunately valgrind is not a viable solution in production, it's better to use it in a controlled environment where thee issue is reproducible.

> * i can try to make js snippet to simulate load, but will be so far from real usage. Before to open issue i tried to find reproducible case where memory growing, but without results

We don't care about "real usage", we just need a case that leaks memory.

> Today i tring something different, recompile janus with refcount debug and after one day (when session/handles is 0) killing to generate core dump. Do you think it would be a good way or i just waste time??

Please don't kill it nor force core dumps.
With refcount enabled just closing janus in a graceful way (r.g. CTRL-C or sending SIGTERM) is enough to make it output a report about dangling references.
Just be aware that refcount logs will be very verbose, so prepare for large log files.

**Comment by michelepra** [comment]
I've just now gracefully shutdown janus.


Server has 0 active session as shown at admin page
![image](https://user-images.githubusercontent.com/11311941/224552947-8dc581db-dc62-409c-bd0d-7ece384c7791.png)

Memory usage (retrieved with ps) at moment of shutdown was at 133316 as shown below

![image](https://user-images.githubusercontent.com/11311941/224553023-6ba54472-c0de-4627-9e9c-e7751cf5fcc7.png)

Reference counters report 0

```
Mar 12 15:48:17 tam01 systemd[1]: Stopping Janus WebRTC gateway...
Mar 12 15:48:17 tam01 janus[3557343]: Stopping server, please wait...
Mar 12 15:48:17 tam01 janus[3557343]: Ending sessions timeout watchdog...
Mar 12 15:48:17 tam01 janus[3557343]: Sessions watchdog stopped
Mar 12 15:48:17 tam01 janus[3557343]: Closing transport plugins:
Mar 12 15:48:17 tam01 janus[3557343]: Stopping webserver(s)...
Mar 12 15:48:17 tam01 janus[3557343]: JANUS REST (HTTP/HTTPS) transport plugin destroyed!
Mar 12 15:48:17 tam01 janus[3557343]: WebSockets thread ended
Mar 12 15:48:17 tam01 janus[3557343]: JANUS WebSockets transport plugin destroyed!
Mar 12 15:48:17 tam01 janus[3557343]: Ending requests thread...
Mar 12 15:48:17 tam01 janus[3557343]: Leaving Janus requests handler thread
Mar 12 15:48:17 tam01 janus[3557343]: Destroying sessions...
Mar 12 15:48:17 tam01 janus[3557343]: Freeing crypto resources...
Mar 12 15:48:17 tam01 janus[3557343]: De-initializing SCTP...
Mar 12 15:48:17 tam01 janus[3557343]: Closing plugins:
Mar 12 15:48:17 tam01 janus[3557343]: JANUS NoSIP plugin destroyed!
Mar 12 15:48:17 tam01 janus[3557343]: JANUS EchoTest plugin destroyed!
Mar 12 15:48:17 tam01 janus[3557343]: Closing event handlers:
Mar 12 15:48:17 tam01 janus[3557343]: JANUS SampleEventHandler plugin destroyed!
Mar 12 15:48:17 tam01 janus[3557343]: Debugging reference counters: 0 still allocated
Mar 12 15:48:17 tam01 janus[3557343]: Bye!
Mar 12 15:48:17 tam01 systemd[1]: janus.service: Succeeded.
```

With these result i think problem can be in some third party library (lws, libnice ecc) used by janus but in this case address sanitizer would be reporting some leak.

I don't know what to do, maybe restart will be only (horrible) solution?

**Comment by atoppi** [comment]
`Debugging reference counters: 0 still allocated`
means that every object managed through refcounting has been de-allocated.

However not every object is refcounted in Janus, since:
1) we still use malloc / free in some circumstances
2) some memory is handled by third-party libraries as you mentioned, so it might need specific methods to unref/free

First of all, double-check that you are correctly instrumenting the source code, e.g.
```
ASAN_FLAGS="-O0 -g -ggdb3 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -fsanitize-address-use-after-scope -fno-sanitize-recover=all"
./configure CFLAGS="$ASAN_FLAGS" LDFLAGS="$ASAN_FLAGS" 
make clean && make
```

_TIP_: using `clang` in place of `gcc` is worth a shot, just set `CC` when issuing `./configure`
```
./configure CC=clang CFLAGS="$ASAN_FLAGS" LDFLAGS="$ASAN_FLAGS" 
```

Then start janus by forcing leak checks
```
ASAN_OPTIONS=detect_leaks=1 /path/to/bin/janus
```

With ASan settled up every naive malloc/free leak _should be_ detected, while Janus refcounted object should be handled by refcount debug and graceful termination report.

As of third-party libraries, we suggest to:
1) install them from sources, using a recent tag or commit in order to rule out already fixed issues
2) if you suspect leaks coming from them, use ASan/debug flags for those too (expect some false positives though, since some libraries do fancy stuff with memory allocators)

In general if no tool is helping here (including `valgrind` in a controlled env) I am not aware of any other approach.
You need to find a leaking scenario by trial and error I guess.

Sometimes a leak might happen due to a missing free/unref in an error branch, can you spot errors or warnings in your logs?
