### ISSUE TITLE
[1.x] Contact line of the processed SDP does not respect sdp_ip option

### ISSUE THREAD

**Issue by Thaigun** [meetecho/janus-gateway#3166]
I'd expect Janus to put the public domain of the server in the SDP in response to `process`. However, the SDP contains the local IP instead. 

**What version of Janus is this happening on?**
1.0.1

**Have you tested a more recent version of Janus too?**
I haven't. I installed with `sudo apt install janus` to get started quickly and the NoSIP plugin does not seem to have received updates since this version.

**Was this working before?**
Don't know.

**Is there a gdb or libasan trace of the issue?**
Nope.

**Additional context**
Here's the config in `janus.plugin.nosip.jcfg`:
```
general: {
        local_ip = "10.166.0.4"
        sdp_ip = "35.228.16.144"
        rtp_port_range = "20000-30000"
}
```
And these are the original legacy SDP from the SIP device and what Janus outputs:
Original:
```
o=ab248994fa 5000 5000 IN IP4 37.219.252.203
s=Talk
c=IN IP4 37.219.252.104
b=AS:4000
t=0 0
m=audio 11916 RTP/AVP 0 8 9 18 101
a=ptime:20
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
m=video 11918 RTP/AVP 104
a=ptime:20
a=rtpmap:104 H264/90000
a=fmtp:104 profile-level-id=42e01e;packetization-mode=1;max-br=2048;max-mbps=40500
a=sendrecv
```
From Janus, I'd expect c-lines to have the public IP:
```
o=ab248994fa 5000 5000 IN IP4 10.166.0.4
s=Talk
t=0 0
a=group:BUNDLE 0 1
a=ice-options:trickle
a=fingerprint:sha-256 69:B9:75:A9:FD:E2:F8:73:EB:88:6F:CF:93:1B:27:5F:9D:97:84:2B:B9:39:FB:2A:2C:E5:82:D7:4D:20:D2:16
a=extmap-allow-mixed
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 0 8 9 18 101
c=IN IP4 10.166.0.4
a=sendrecv
a=mid:0
a=rtcp-mux
a=ice-ufrag:EZML
a=ice-pwd:EgW/eSe/zYureqWx71if7L
a=ice-options:trickle
a=setup:actpass
a=ptime:20
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=msid:janus janus0
a=ssrc:1621586854 cname:janus
a=candidate:1 1 udp 2013266431 10.166.0.4 36786 typ host
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 104
c=IN IP4 10.166.0.4
a=sendrecv
a=mid:1
a=rtcp-mux
a=ice-ufrag:EZML
a=ice-pwd:EgW/eSe/zYureqWx71if7L
a=ice-options:trickle
a=setup:actpass
a=ptime:20
a=rtpmap:104 H264/90000
a=fmtp:104 profile-level-id=42e01e;packetization-mode=1;max-br=2048;max-mbps=40500
a=ssrc-group:FID 434316239 2515409990
a=msid:janus janus1
a=ssrc:434316239 cname:janus
a=ssrc:2515409990 cname:janus
a=candidate:1 1 udp 2013266431 10.166.0.4 36786 typ host
a=end-of-candidates
```
It also does give me this warning, though this comes from the core so probably not related:
```
[WARN] Janus is deployed on a private address (10.166.0.4) but you didn't specify any STUN server! ...
```

**Comment by lminiero** [comment]
That's up to you to do in the configuration.

https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.sip.jcfg.sample#L10-L12

	# Specify which (public) IP address to advertise in the SDP.
	# If not set, the value above or anything autodetected will be used
	#sdp_ip = "1.2.3.4"

**Comment by lminiero** [comment]
> It also does give me this warning, though this comes from the core so probably not related:
> 
> ```
> [WARN] Janus is deployed on a private address (10.166.0.4) but you didn't specify any STUN server! ...
> ```

Yes, that's core related, not the plugin.

**Comment by lminiero** [comment]
Ah apologies, I think I got your problem in reverse: you meant the IP on the WebRTC side, not SIP. Then yes, `sdp_ip` is useless, it only says which IP to put in the SDP sent on the SIP side. For anything related to the core, you either set the STUN server (if you're behind a NAT) in `janus.jcfg`, or configure `nat_1_1_mapping` with the public IP (but only if you're on a server like AWS that has the same mapping for public/private ports). In that case, the warning you see is indeed relevant, since it talks about the WebRTC side of the SDP.

**Comment by Thaigun** [comment]
I was too scared to tweak that setting as it said "only if you know what you're doing" and I really was not. 😄 Now that I read it more carefully, it makes sense.

Setting `nat_1_1_mapping` to the public IP did solve this issue, thank you for the swift response!

**Comment by lminiero** [comment]
> I was too scared to tweak that setting as it said "only if you know what you're doing" and I really was not. smile

Yeah we had to write that as otherwise people can break things :grin:   They see STUN/TURN, think it's needed for WebRTC, and so set it for Janus too which in the 99% of cases is not needed and can actually cause problems. Same thing for nat-1-1, which is specifically conceived for AWS (or similar usage), since it will just replace the local IP with a public one, but that only works if the private port is exactly the same as the public port (which is not true for regular NATs, and is when you use something like AWS instead), and will otherwise just break WebRTC otherwise.
