### ISSUE TITLE
[1.x] host janus.js 

### ISSUE THREAD

**Issue by jp-bennett** [meetecho/janus-gateway#3229]
The janus.js file has to match the installed Janus gateway version, and on some installs, this can be fiddly to set up. Since Janus is already hosting an http server, could it also host the janus.js file that matches the server version?

**Comment by lminiero** [comment]
No, because the HTTP server is optional (it's a module), janus.js can work with websockets too (optional as well), and we only use those servers for API, not serving static files. Besides. janus.js is just an example of how to write a client side, but most definitely not THE way to talk to Janus: there's Janode as well, for instance, and countless third party stacks. It would be a very bad idea to hardcode it anywhere in Janus, IMHO.

**Comment by lminiero** [comment]
That said, not sure why you think janus.js has to match? The 0.x version of Janus works with the 1.x version too and viceversa: the 1.x version is simply more tailored towards using multiple streams.

**Comment by jp-bennett** [comment]
Really? I was under the impression that they needed to match up, and it was a required library. We might try dropping the js include, and replicating the needed code, then. Thanks for the information!

**Comment by lminiero** [comment]
No, the only thing to ensure is that you ship the version the application code (e.g., streamingtest.js) needs. If you use streamingtest.js from Janus 1.x it won't work with janus.js from 0.x for instance.

**Comment by lminiero** [comment]
> We might try dropping the js include, and replicating the needed code, then

You can have a look at Janode as a basis for that, which is a more modern Janus API stack we wrote mostly for the server side, but works in the browser too: https://github.com/meetecho/janode/
