### ISSUE TITLE
[1.x] Janus stops responding after few days of uptime

### ISSUE THREAD

**Issue by NabilHunt** [meetecho/janus-gateway#3240]
I am running Janus as a service, and using videoroom plugin in my application. But it would stop reponding after days of uptime, and restarting would fix the problem (although it’s not a real fix). Here is the last log I got after it stopped responding: [janus service logs](https://pastebin.pl/view/e6b042c6)

This isn't under heavy use, for the moment it's just running in test context

**Comment by lminiero** [comment]
Sorry for the late reply, looks like this issue flew under my radar and I missed it. This log doesn't give any indication on what's going wrong, but what I can see is that you're most definitely getting a lot of spam or requests that have very little to do with Janus. I'd encourage you to put a frontend like nginx or httpd in front of it to filter it out, so that Janus only gets Janus API requests.

**Comment by atoppi** [comment]
@NabilHunt since you are using the videoroom plugin, it's worth trying a recent version now that #3247 has been merged.

**Comment by lminiero** [comment]
@NabilHunt did you check the latest version as Alessandro suggested?

**Comment by lminiero** [comment]
Closing.
