### ISSUE TITLE
[1.x]

### ISSUE THREAD

**Issue by burakurer** [meetecho/janus-gateway#3264]
**What version of Janus is this happening on?**
v1.2.1

**Have you tested a more recent version of Janus too?**
No

**Was this working before?**
No

**Is there a gdb or libasan trace of the issue?**
https://pastebin.com/v2cJfAqz

**Additional context**
Hello,

Developing a project with janus for the first time and getting some errors.

I followed the GitHub documentation for Janus and completed the installation. After the installation, I couldn't find and modify the '/opt/janus/etc/janus/janus.transport.http.jcfg' file.

On the server where I installed it, the Janus service is active, but I cannot access the WebSocket, API, and Admin page via the port.

If you would like to provide paid support on this matter, it would be better for me. The urgency of the issue is high; please help. Thank you.

Operating System I'm using: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64)
Janus Version: v1.2.1
Janus Startup Log: https://pastebin.com/v2cJfAqz

**Comment by lminiero** [comment]
> After the installation, I couldn't find and modify the '/opt/janus/etc/janus/janus.transport.http.jcfg' file.

That's because the transport was not built. It's nowhere to be found in the startup logs. You likely didn't have the dependency installed when the configure script looked for it.

> If you would like to provide paid support on this matter, it would be better for me

Please use the contact form on https://www.meetecho.com for paid support.

Closing as a configuration issue, and so out of scope here. Please refer to the [group](https://janus.discourse.group/) for similar problems in the future.
