### ISSUE TITLE
Timeout and Trickle error: no audio stream

### ISSUE THREAD

**Issue by vbraun** [meetecho/janus-gateway#327]
I'm playing with the echo test plugin using my own code to call the janus rest API. It sends ice candidates and jsep offer asynchronously and as soon as the browser (crome 45) generates them.

Sometimes I get {code: 466, reason: "Trickle error: no audio stream"} back from the janus server. Generally it takes a few retries (first connect always works), and only if I have >=3 stun servers configured. It seems that the timeout for the trickle ice is too short:
~~~~
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP POST request on /janus/3894809613/1981012534...
Handle 1981012534 supports trickle even if it didn't negotiate it...
[1981012534] Trickle candidate (audio): candidate:3013953624 1 udp 2122260223 192.168.1.100 55449 typ host generation 0
[1981012534] No stream, wait a bit in case this trickle got here before the SDP...
Got a HTTP POST request on /janus/3894809613/1981012534...
[1981012534] Trickle candidate (audio): candidate:854413036 1 udp 1686052607 91.64.xxx.xxx 55449 typ srflx raddr 192.168.1.100 rport 55449 generation 0
[1981012534] No stream, wait a bit in case this trickle got here before the SDP...
Got a HTTP POST request on /janus/3894809613/1981012534...
Got a HTTP POST request on /janus/3894809613/1981012534...
[1981012534] Trickle candidate (video): candidate:3013953624 1 udp 2122260223 192.168.1.100 50652 typ host generation 0
[1981012534] No stream, wait a bit in case this trickle got here before the SDP...
[1981012534] Trickle candidate (audio): candidate:3013953624 2 udp 2122260222 192.168.1.100 38641 typ host generation 0
[1981012534] No stream, wait a bit in case this trickle got here before the SDP...
Got a HTTP OPTIONS request on /janus/3894809613/1981012534...
Got a HTTP POST request on /janus/3894809613/1981012534...
[1981012534] Trickle candidate (audio): candidate:854413036 2 udp 1686052606 91.64.xxx.xxx 38641 typ srflx raddr 192.168.1.100 rport 38641 generation 0
[1981012534] No stream, wait a bit in case this trickle got here before the SDP...
[1981012534]   -- Waited 3 seconds, that's enough!
[P6HvgbQYyOaa] Returning error 466 (Trickle error: no audio stream)
~~~~
According to the browser console the jsep offer is sent as well though apparently not early enough. If I configure <=2 stun servers then this never happens. 

I'm not sure if 3 seconds is a reasonable timeout, as far as I understand the trickle can arrive (potentially) a long time before the JSEP offer so that one could sort out the firewall issues before the call is initiated. So it would make more sense to me to wait for the entire lifetime of the janus handle? But I admittedly am not 100% sure.

**Comment by lminiero** [comment]
The three seconds timeout is not related to a trickle timeout, but the availability of a session to relate them to. In general, it's safe to assume trickle candidates will be sent before the offer is ready in the browser, due to the asynchronous nature of the JSEP API. As such, in the Janus core it's ok to receive them before we even know there's a session going to be negotiated, and that's why we wait for a few seconds. If those seconds pass, though, and no offer has been received or no streams were created, then we discard the trickle candidate because we assume it's related to something that doesn't exist.

I guess that's what happening in your case. You're sending the offer too late. Are you waiting for all the candidates to be ready before sending it? If so, that goes against the purpose of trickle: either you wait for all the candidates to be ready, and so they appear in the SDP itself, or you send the offer wth no candidates as soon as you have it, and leave the candidates to the trickle mechanism.

**Comment by vbraun** [comment]
I know, I'm sending ICE and SDP as soon as the browser generates them. But of course subject to chrome's 6 (or so) simultaneous connection limit per tab, so possibly not part of the initial 6 that are in the log snippet.

Since the connection remains open while janus is waiting for the SDP (the REST response with the "Trickle error: no audio stream" arrives after 3 seconds), isn't there a race if you saturate the simultaneous connection limit with ICE trickles. This would also explain why its triggered by repeated reloads as old HTTP connections might still be terminating and count against the limit.

If I ignore the error in the REST error response then I see the SDP further down the log and video starts, though presumably without taking all ICE candidates into account.

**Comment by lminiero** [comment]
The 6 simultaneous connection limit per tab applies to HTTP connections: in general there's never a risk of encurring in this, since browsers make use of pipelining for this. Some of our applications have a STUN server and 4 TURN servers configured in JavaScript (so many candidates) and it all works fine.

That said, I agree this can be a problem in some cases, considering we do indeed keep the request blocked until we know more. Not sure how we could handle this better, as one way could be to immediately return a success for each trickle message even when we're waiting, but in that case you'd be lacking feedback on a failed candidate; we might make the request asynchronous (send the trickle, immediate ack, event later on about success/error), but that would require some refactoring.

**Comment by vbraun** [comment]
POST cannot/should not be pipelined as it is not an idempotent request, I think. Also, chrome doesn't use pipelining afaik: https://www.chromium.org/developers/design-documents/network-stack/http-pipelining

As long as you actually send out the SDP first / early this is all fine. I'm using angular's $http service to make the request so I'm not 100% sure about the order (haven't tried to sniff the network packets). It works most of the time, I'm just trying to figure out why it sometimes fails.

The REST api could just always ack the ICE trickle immediately and return an error summary as part of the jsep offer response (e.g. There were X trickle candidates ignored as they arrived more than 3 seconds ago).

**Comment by lminiero** [comment]
> The REST api could just always ack the ICE trickle immediately and return an error summary as part of the jsep offer response (e.g. There were X trickle candidates ignored as they arrived more than 3 seconds ago).

That's basically the asynchronous mechanism I mentioned before, and as anticipated that would require some refactoring with respect to the operations we currently do when handling the request (e.g., who's responsible to check for trickle candidates, timeout if they're not related to anything, parse them when the time comes, etc.). I'd rather keep the trickle mechanism separated from the JSEP offer/answer, and notify successes/failures individually using the Janus transaction-based event mechanism. I'll try and work on a fix in the next few days.

**Comment by vbraun** [comment]
I see your point. Thanks for the help, I'll be happy to test!

**Comment by lminiero** [comment]
Can you let me know if #330 fixes it for you? Please let me know if this works as expected in all of your test scenarios: this is quite a disruptive change in a very delicate part of the core (trickle candidates are key to getting connectivity) and so I'd only merge if 100% sure we wouldn't be breaking something else.

**Comment by Firegarden** [comment]
Please consider this appears to be a very big change for a very small issue.  The issue only happens "Sometimes" and "Generally it takes a few retries" and "only if I have >=3 stun servers configured".

Maybe it's not worth c omitting until more people complain about this affecting production?

**Comment by lminiero** [comment]
It's still a potentially breaking problem: anything that causes a retry to work is a bug. Besides, the new version is definitely more optimized, as it doesn't keep resources open (i.e., the request thread, and HTTP requests when using the REST API). If this works I see this as a benefit.

If you're concerned about this, please give it a try and let us know if this breaks anything. We obviously need more than us and the reporter to test this...

**Comment by lminiero** [comment]
As a side note, what looks like a big change is not really that. We mostly moved code around, especially the trickle processing code which is now in a separate method other bits in the core can call. Before, the code was simply replicated a couple of times.

**Comment by lminiero** [comment]
Closing as it looks like this is fixed.
