### ISSUE TITLE
Defer onbeforeunload handling in janus.js

### ISSUE THREAD

**Issue by ndarilek** [meetecho/janus-gateway#333]
I'm attempting to use the `returnValue` property of the onbeforeunload event to prompt whether the user wants to leave a page when a call is in progress. Unfortunately, while clicking "Stay on page" does in fact prevent the user from navigating away, it doesn't prevent the call from dropping as I'd like.

Looking through the source, I see janus.js has its own onbeforeunload handling. I think this is great for most default cases, but I'd like it if I could opt out of it and call the function myself. Maybe move the functionality into a Janus.destroy() function and let me configure whether it is called automatically on tab close, with the current way being the default?

Thanks.

**Comment by lminiero** [comment]
That's a good point. We do indeed have such an handler in the code, to try and make sure that when you close a tab abruptly you also close the Janus session cleanly, rather than relying on the session timeout within Janus itself. I see now how this may be counter productive in scenarios like the one you depicted.

Since I'd like to keep this behaviour as the default, one way to fix this might be an additional parameter you can pass when creating a new Janus session in ```janus.js```, e.g., ```destroyOnUnload: true|false```, with ```true``` being the default. The ```onbeforeunload``` would still be in place, but only call ```destroy``` if the flag was not ```false```. This could allow you to override the default behaviour and handle it the way you want instead. What do you think about this?

**Comment by lminiero** [comment]
Just committed: https://github.com/meetecho/janus-gateway/commit/6c8c6eeed41eda272f14dfd54fab10bcf5f40e3b
Let me know if that's not working as expected for you.
