### ISSUE TITLE
Add support for Microsoft EDGE

### ISSUE THREAD

**Issue by simongymer-speakerbus** [meetecho/janus-gateway#337]
Very early days, but would be good to look into supporting Microsoft EDGE once it's moved from Insider Preview to mainstream.

**Comment by lminiero** [comment]
Of course we'd like to do that, but I don't use Windows and most definitely won't have access to a Windows 10. One of my colleagues might attempt to do that in the future but there's no plan on a date. It's not going to be super-easy, as we'll need some shim on the JavaScript side that translates whatever ORTC generates to SDP and viceversa, since Janus is based on SDP right now.

That said, if any of you guys happen play with this and feel like sharing a pull request, we'll be glad to look at that!

**Comment by lminiero** [comment]
First attempt here, #360

**Comment by lminiero** [comment]
PR merged.
