### ISSUE TITLE
[0.x] Update request failed when it has SDP answer

### ISSUE THREAD

**Issue by vspatel310** [meetecho/janus-gateway#3455]
**What version of Janus is this happening on?**
Tested 0.13.0 version

**Have you tested a more recent version of Janus too?**
I haven't tested with master branch but I went through the source code which has similar issue

**Additional context**
I have set autoaccept_reinvites=false in call and accept requests after that SIP gateway sends REINVITE with SDP offer to Janus which relay SDP offer to client using updatingcall event so when client sends a response with SDP answer it failed with "SDP type answer is incompatible with session status incall" log. It should work as per document

**Comment by lminiero** [comment]
That happens when you send an `update` to a session that has the `janus_sip_call_status_incall` status. When we get a re-INVITE we change the status to `janus_sip_call_status_incall_reinvited`:

https://github.com/meetecho/janus-gateway/blob/0.x/plugins/janus_sip.c#L5436-L5441

As such, my guess is that you're using the API incorrectly. You should definitely test with the latest `0.x` version, since 0.13.0 is two years old and there have been a ton of changes since.
