### ISSUE TITLE
streaming plugin should fail create rtp stream request when it can't bind to port

### ISSUE THREAD

**Issue by fpn** [meetecho/janus-gateway#365]
Currently when I send a "create" request to the streaming plugin to create a new stream of type rtp, I get a success state even if it fails to bind the audio port.

```
[plugins/janus_streaming.c:janus_streaming_create_fd:2413] [...] Bind failed for audio (port 36514)...
```

I wonder whether we should allocate the fd in janus_streaming_handle_message and hand it over to the janus_streaming_relay_thread, so we can return a negative reply to the client if the bind does not succeed.

**Comment by lminiero** [comment]
As far as I remembered, that was what I thought we were doing, as we call ```janus_streaming_create_rtp_source``` and then check the return value here,
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L1216

But checking the code I noticed that, as you pointed out, we only create the file descriptors when launching the thread, and that is out of the control of the method itself. I think this changed when we moved a bit of code around for new features. When I get back to the lab on Monday I'll move the socket creation part in ```janus_streaming_create_rtp_source``` itself, which should take care of that.

**Comment by lminiero** [comment]
Sorry for the delay, but in the meanwhile we've been abroad for work for more than 10 days. Just come back so I'll work on this in the next few hours/days.

**Comment by lminiero** [comment]
Apparently the problem was our use of ```SO_REUSEADDR``` for UDP sockets. Since we were telling the kernel it was ok to re-use the same address, binds for ports already taken wouldn't return an error. This is usually needed for TCP due to ```TIME_WAIT```, but is useless for UDP: actually in our case it's counterproductive, as it's preventing us to check when another mountpoint is already using the port. I'm fixing this in other parts of the code as well (e.g., SIP plugin) so I'll push a commit as soon as it's ready.

**Comment by lminiero** [comment]
Should have been fixed in https://github.com/meetecho/janus-gateway/commit/99c5a404b374e1216bbd3bacf1ac7c7854c0235a let me know if that's not the case.
