### ISSUE TITLE
Cannot connect with Firefox; "Still waiting for the answer..."

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#383]
I am unable to connect with local echo test demo using Firefox 42 on Ubuntu 14.04 LTS. 
Log is populated by:
`Still waiting for the answer, queueing this trickle to wait until we're done there...`

Chrome have no problems. Using `git bisect`, I figured, that the first bad commit is https://github.com/meetecho/janus-gateway/commit/b6c56a2c7ed085c4b31b29c27b3a835af8dedbe3.

**Comment by uxmaster** [comment]
I have checked tag v0.0.9 is working fine (don't you trust `git bisect`?).

There is nothing strange in the javascript console, see https://gist.github.com/uxmaster/d4e47d053b45b02c63e3

**Comment by lminiero** [comment]
@uxmaster can you try with the latest commit? https://github.com/meetecho/janus-gateway/commit/acb9e603507859762ee717be5dfc9677fde1e0d1
I encountered the same problem when doing some unrelated changes, and I think the cause was a typo we had I just fixed. Not sure what it always worked for me before, though.

**Comment by uxmaster** [comment]
It works fine with the latest commit.

**Comment by lminiero** [comment]
:+1:
