### ISSUE TITLE
can you guys add a parameter in the config or on the binary to generate a pid file?

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#395]
it would make life much easier when dealing with runscript startup files, right now i have to hack around it and when using makepid in the startup scrpts it wont generate run if i try to send it to the background

maybe -P /var/run/janus.pid and we can specify where to place the pid?

thank you

**Comment by lminiero** [comment]
That's something external scripts can (and usually) do.

**Comment by lminiero** [comment]
Closing as not an issue and can be handled externally.

**Comment by ploxiln** [comment]
Well, it's worth mentioning that if you were planning to add a --daemon(ize) option to janus, "pidfile" functionality usually goes along with that (because the top-level thing running `janus --daemonize` doesn't know the pid of the grand-child).

So maybe it's best not to offer a --daemon(ize) option, and point people to http://linux.die.net/man/1/daemonize (which does the pidfile, and other things)

**Comment by lminiero** [comment]
Fair point, I'll look into how to create the pidfile and remove it on exit.

**Comment by bhakimi** [comment]
thank you @lminiero, i also have a really nice startup script created that has a safe function to restart it and email us incase it does, let me know once this is fixed so i can publish it, this was the one thing that made it much harder to create, btw is it possible for us to define the full path and filename of the pid please?

**Comment by lminiero** [comment]
Implemented as a pull request here, feedback welcome: #399

**Comment by bhakimi** [comment]
will test tonight

**Comment by bhakimi** [comment]
tested and works perfectly, thank you so much

**Comment by lminiero** [comment]
:+1: merging then.
