### ISSUE TITLE
counter intuitive ice_ignore_list behavior

### ISSUE THREAD

**Issue by fpn** [meetecho/janus-gateway#397]
We run in aws and have

```
eth0: 10.1.2.3
eth0:0 52.1.2.5 (public address is also an alias)
```

What seemed logical to me was to have janus listen on interface = 0.0.0.0  (all interfaces)
and ice_ignore_list = 10. (exclude 10.* from advertised candidates)

But the result of that is that janus/libnice seems to bind itself to 52.1.2.5:54321 and when the ice requests come in via the amazon router to 10.1.2.3:54321 janus doesn't see them.

To make it work I had to:
```
ice_ignore_list = eth0:0 (exclude the public address 52.1.2.5)
nat_1_1_mapping=52.1.2.5
```
The documentation in the cfg file on ice_ignore_list says "... for the purpose of ICE candidates gathering.", it seem the implementation uses it for the purpose of which interfaces to bind or not.

**Comment by ploxiln** [comment]
"ice_ignore_list" is for ignoring interfaces, not ip addresses. the ip address option is just a convenient way to match some interfaces. Janus uses libnice for ICE and unfortunately it's just not as simple as listening on 0.0.0.0 :) It has to bind to specific interfaces to generate server-reflexive and peer-reflexive ICE candidates.

By the way ... you don't have to create an "alias" interface to get a second ip address on an interface:

```
vagrant@dockerdev:~$ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:62:76:11 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe62:7611/64 scope link 
       valid_lft forever preferred_lft forever
vagrant@dockerdev:~$ sudo ip addr add 10.20.1.1/24 dev eth0
vagrant@dockerdev:~$ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:62:76:11 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.20.1.1/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe62:7611/64 scope link 
       valid_lft forever preferred_lft forever
```

And doing so on EC2 is a bit odd because (as you're well familiar with I know) the addresses are translated to the internal address, you don't actually receive them with the external address in the ip header ...

**Comment by lminiero** [comment]
Pierce is right, that's how the stack behaves. Closing as not really an issue.
