### ISSUE TITLE
RTP Retransmission with EchoTest, VideoCall and VideoRoom plugins

### ISSUE THREAD

**Issue by rayvbr** [meetecho/janus-gateway#404]
(Not sure if this is a bug or intentional. Please close if it's the latter)

I noticed that since 6089eb4 (Sept 7), the EchoTest and VideoCall plugins explicitely remove the retransmission-related SDP lines (e.g. "a=rtpmap:96 rtx/90000, a=fmtp:96 apt=100") from incoming SDP offers, causing WebRTC clients to no longer respond to incoming NACKs. In earlier versions, this did seem to work. Is this intentional?

Similarly, the Videoroom plugin doesn't add the retransmission SDP lines to it's SDP offer, while it does seem to support RTP Retransmission packets if it receives them.

**Comment by lminiero** [comment]
We only remove the line to use a different payload type and SSRC, retransmission should still occur.

**Comment by rayvbr** [comment]
Thanks. 

The SDP returned from Janus does not contain the "a=fmtp:xxx apt=yyy" lines. The most recent Google WebRTC stack seems to interpret this as retransmission not being supported. But maybe I'm doing something else wrong.

Is there anything else I need to configure in Janus to enable retransmission in the various plugins (videoroom in particular)?

**Comment by lminiero** [comment]
If Chrome is really interpreting that as "disable retransmissions", then it's something we need to fix. Have you verified this looking at the webrtc-internals stuff?

As anticipated, the main aim here was to make sure retransmissions would re-use the same SSRC and not a different one, as a more or less recent in the Chrome implementation does. In fact, we retransmit packets as they are when needed, buffering them already encrypted, and changing SSRC would force us to re-encrypt everytime a retransmission is needed which, with several clients connected, can be a considerable burden.

If you did notice this happening and can replicate it easily, try just commenting out that rtx line in the videoroom code, so that the attribute stays there, and see what happens. If things work as expected and nothing weird happens, we can remove that in mainstream as well. I'm just wondering if this will lead to issues with the recordings, though (e.g., with the different payload types).

**Comment by ploxiln** [comment]
I'm surprised we keep packets for retransmission in encrypted form? The retransmit code inspects the sequence number from the rtp header in the data buffer of the janus_rtp_packet

**Comment by lminiero** [comment]
SRTP encrypts the payload but just hashes the header, which stays in clear exactly to allow for inspection (e.g., routing).

**Comment by ploxiln** [comment]
I see, thanks

**Comment by rayvbr** [comment]
I've done some more tests with webrtc-internals. It could be that the issue is related to a change in the webrtc.org stack as to when a retransmission occurs. In some of my test sessions, over 300 NACKs were received over the course of a couple of minutes, but only a single retransmissions was actually sent.

I'll do some further tests by enabling the RTX-related SDP lines and report back my findings.

**Comment by lminiero** [comment]
Hi, any update you can share on this?

**Comment by rayvbr** [comment]
Sorry, I dropped the ball on this one. 

I've just re-checked with the latest version of the webrtc.org stack and can confirm the percentage of retransmissions versus NACKs is still extremely low (less than 1%). The fact that some retransmissions do occur, however, seems to suggest that the problem is not in Janus, but in the webrtc.org stack. At the same time, there definitely does seem to be a correlation between the presence or absence of the retransmission-related SDP lines.

**Comment by lminiero** [comment]
Closing as a lot changed in the meanwhile, in both Janus and browsers. Feel free to reopen if still an issue.
