### ISSUE TITLE
Improvements for the daemonzing code

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#408]
I thought I'd first open an issue and discuss here before making a PR.

Currently the daemonizing code has the following issue: when Janus is started, if the process is daemonized, we return 0 almost immediately, even if Janus couldn't actually start.

The way to solve it involves the traditional double-fork plus a pipe over which the granchild would tell its grandparent that it succeeded to start (or not).

So, the initialization would be like:

- parse cmdline and read the config line
- if we have to fork, create a pipe and fork once
- parent wait on the read end of the pipe
- setsid
- fork again, and have the parent exit
- the granchild continues initialization
- after initializing the logger, stdin/out/err are replaced with /dev/null
- pid file is created
- ...
- when Janus is ready, the granchild writes a 0 on the pipe where the grandfather is waiting
- grandparent exits with the exit code received over the pipe

Thoughts?

**Comment by lminiero** [comment]
Sounds reasonable, and would solve the issue you mentioned: I tried moving the daemon code at the end of the setup process, but of course then nothing worked because killing the father I'd kill everything it created in the first place. I didn't know about this double-fork approach which apparently solves the issue.

I have just one doubt: if the initialization causes Janus to crash so that it never writes anything on the pipe, will it freeze the grandfather waiting forever?

**Comment by saghul** [comment]
> I have just one doubt: if the initialization causes Janus to crash so that it never writes anything on the pipe, will it freeze the grandfather waiting forever?

Yes. Note however, that while the grandfather waits for the grandchild to write on the pipe, it's blocked there, as in, the shell hasn't returned the prompt, so you can still ctrl-c it.

**Comment by lminiero** [comment]
> Yes. Note however, that while the grandfather waits for the grandchild to write on the pipe, it's blocked there, as in, the shell hasn't returned the prompt, so you can still ctrl-c it.

I guess we might also put a timed wait there (e.g., select/poll with a timeout) so that we can leave if it looks like it's taking too long.

**Comment by lminiero** [comment]
PR merged, closing.
