### ISSUE TITLE
Troubles shutting Janus down

### ISSUE THREAD

**Issue by nschoe** [meetecho/janus-gateway#42]
When trying to stop Janus with `CTRL + C`, it often gets stuck on this :

```
^CStopping gateway, please wait...
Sessions watchdog stopped
Closing webserver...
```

A second `CTRL + C` gives the `^CIn a hurry? I'm trying to free resources cleanly, here!` but still stays stuck, until a last `CTRL + C` gives `^COk, leaving immediately...`

I know signal is caught in the code, but there is obviously something preventing Janus from shutting down.

But sometimes it all happens just fine. I haven't been able to identify when that happens.

**Comment by MichaelB76** [comment]
@lminiero - Found this issue after debugging the hang on MHD_stop_daemon, would this be worth adding to the FAQ maybe? Running 'apachectl graceful' from a terminal kicks it back into life, we are using this as a work around at the moment.

**Comment by lminiero** [comment]
@MichaelB76 thanks for the tip, although I don't think it's always related to that as IIRC sometimes this can happen even when no proxy is involved.

**Comment by ploxiln** [comment]
I think Chrome tends to open connections pre-emptively, and sometimes never actually has enough requests to use them; I've seen odd (harmless) error messages related to that in other software which receives http requests from Chrome.

I never seem to have this problem with janus, and maybe it's because in my setup, the browser doesn't make http requests directly to janus, it goes through a separate "api" application, which makes the http requests to janus.

**Comment by MichaelB76** [comment]
Yes, I don't think the problem is related to use of Apache either, that's just a work-around we've found when using it as a proxy. It's interesting that it kicks the library back into life. Another thing I've seen in the past, although I can't seem to reproduce it now, is that attempting a new connection to Janus while it is shutting down causes MHD_stop_daemon() to unhang and return.

**Comment by lminiero** [comment]
I think that's what ```MHD_quiesce_daemon``` was supposed to prevent, but it caused much more frequent hangs at shutdown and so we removed those calls.
