### ISSUE TITLE
Re-publish not working

### ISSUE THREAD

**Issue by MagicIndustries** [meetecho/janus-gateway#452]
I'm using the videoroom plugin and have a working chat setup. Recently the unpublish / republish mechanism stopped working and I tracked it down to line 1533 of janus.js.

There's a check there to see if an offer has been sent before. If so, it refuses to do it again. If I comment this line out, re-publish works fine again.

Am I missing something? Is this an error or is there some better way to re-publish now that I'm not aware of?

**Comment by lminiero** [comment]
That check has always been there, and is a fence to avoid sending the multiple offer or answer more than once (e.g., because of a callback being invoked twice) as we don't support renegotiations yet and things would break.

That said, you usually need to wait a bit (1-2 seconds) after unpublishing, as the PeerConnection needs to be cleaned up, and this is triggered in Janus after a bit due to how things are garbage collected (will be fixed when reference counters are ready, so not yet). If that's still not helping you, as it appears is the case for @mbellezi, you can try to explicitly call the ```hangup``` method on the handle after sending the ```unpublish``` (e.g., ```sfutest.hangup()```) which should get rid of whatever resource has been prepared for WebRTC on the client side as well, before waiting for the same method to be called automatically in response to the server closing it.

**Comment by lminiero** [comment]
Anyway, a new publish still needs to wait a bit, as the 1-2 seconds part is a server thing, not a client one, and so you risk re-using the same context as before and things would break.

**Comment by mbellezi** [comment]
OK. Sorry for the dup. I've taught it was another issue because, after more than 2 secs, the resource was still been used. I will use than hangup and wait or try to create a new attachment and do a new publish while do a detach on the old handler. As I'm using the Websockets RESTFull API directly from my server app, I think it will not be a big issue.

**Comment by lminiero** [comment]
Ah ok, got it. Anyway, if you're not using janus.js in your app (since you're apparently wrapping the Janus API) and you're calling "unpublish", no further action should be required, as that automatically results in the plugin asking the core to tear down the PeerConnection:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2871

If that's not working for you, that is if that's not resulting in ```hangup_media``` being called (not sure if the ICE failure may be involved there), try adding this line before the ```close_pc``` one:

    janus_videoroom_hangup_media(session->handle);

This will definitely instruct the plugin about cleaning its own resources as needed. Let me know if that fixes it and I'll update the plugin code.

**Comment by mbellezi** [comment]
[log.txt](https://github.com/meetecho/janus-gateway/files/113898/log.txt)

Ok. I've made the patch to janus_videoroom.c and sometimes it work (the connection is cleared within 3 secs), sometimes not. I've attached the log from my library showing the Janus command sequence for better understanding. The acks and trickle ice messages were omitted  for a clean view.

I'm forcing a failing in the ICE on the client to force the republish for the testings.

After this issues, the detach, attach, join, publish again is looking more promising.

**Comment by lminiero** [comment]
Did you do a ```make install``` after the patch? I think you're still using the previous version, as unpublish will most definitely trigger hangup_media now, which will always result in the SDP variable being cleared, so there's no way you can get the "Already published" with the fix.

**Comment by mbellezi** [comment]
I'm sure (history):

  444  cd janus-gateway/
  445  ls
  446  cd plugins/
  447  ls
  448  vim janus_videoroom.c
  449  cd ..
  450  make
  451  make install
  452  /opt/janus/bin/janus


---
                                /* Tell the core to tear down the PeerConnection, hangup_media will do the rest */
                                janus_videoroom_hangup_media(session->handle);
                                gateway->close_pc(session->handle);
                                /* Done */
---

Strange...

**Comment by lminiero** [comment]
Try adding some JANUS_PRINT lines in ```janus_videoroom_hangup_media```

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2062

e.g., to make sure you're getting to where ```participant->sdp``` is cleared.

**Comment by mbellezi** [comment]
Ok. When the problem presents itself, it seens the sdp is not cleared. Here is the code:

```
void janus_videoroom_hangup_media(janus_plugin_session *handle) {
        JANUS_PRINT("STEP 1\n");
        JANUS_LOG(LOG_INFO, "No WebRTC media anymore\n");
        if(g_atomic_int_get(&stopping) || !g_atomic_int_get(&initialized))
                return;
        JANUS_PRINT("STEP 2\n");
        janus_videoroom_session *session = (janus_videoroom_session *)handle->plugin_handle;
        if(!session) {
                JANUS_LOG(LOG_ERR, "No session associated with this handle...\n");
                return;
        }
        JANUS_PRINT("STEP 3\n");
        session->started = FALSE;
        if(session->destroyed)
                return;
        JANUS_PRINT("STEP 4\n");
        if(g_atomic_int_add(&session->hangingup, 1))
                return;
        JANUS_PRINT("STEP 5\n");
        /* Send an event to the browser and tell the PeerConnection is over */
        if(session->participant_type == janus_videoroom_p_type_publisher) {
                /* This publisher just 'unpublished' */
                janus_videoroom_participant *participant = (janus_videoroom_participant *)session->participant;
                if(participant->sdp)
                        g_free(participant->sdp);
                participant->sdp = NULL;
                JANUS_PRINT("STEP 6\n");
```

And here is the janus log:

```
WebSocket (Janus API) thread started
Creating new session: 2512182900
Creating new handle in session 2512182900: 2649333726
Creating new session: 3789111364
Creating new handle in session 3789111364: 1278824132
[1278824132] Creating ICE agent (ICE Full mode, controlled)
STEP 1
No WebRTC media anymore
STEP 2
STEP 3
STEP 4
STEP 5
STEP 6
[1278824132] WebRTC resources freed
[1278824132] Creating ICE agent (ICE Full mode, controlled)
STEP 1
No WebRTC media anymore
STEP 2
STEP 3
STEP 4
[1278824132] WebRTC resources freed
[1278824132] Creating ICE agent (ICE Full mode, controlled)
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:2709] Can't publish, already published
Detaching handle from JANUS VideoRoom plugin
STEP 1
No WebRTC media anymore
STEP 2
STEP 3
STEP 4
Cleaning up handle 1278824132...
[1278824132] WebRTC resources freed
[1278824132] Handle and related resources freed
```

**Comment by lminiero** [comment]
Ok, in your case it's not getting further because ```hangingup``` is still set, and is only reset after a call to ```setup_media```, that is when WebRTC becomes available. So what's happening is this:

1. you publish, sdp=something
2. you unpublish, hangingup=0 so sdp=null and hangingup=1
3. you try a publish again, sdp=something
4. you unpublish again, but hangingup=1 still, because after the latest publish you never got a ```setup_media``` and so never resetted the flag (and hence the stuff is not cleaned up again).

Not exactly sure how we can properly handle this, as we do need the fence for some things. I guess one way to do that could be resetting the flag after you call "publish", that is adding this line:

    g_atomic_int_set(&session->hangingup, 0);

before this one:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2857

so that even if the media is not actually setup, you can still unpublish and try to clean resources. Not sure if this will break anything, but feel free to try and let me know if this works for you consistently.

**Comment by mbellezi** [comment]
Ok. Thank you.

Do you think the work on reference counters will make it better?

I think I will stick with the detach, attach, join, publish pattern for this cases of ICE Failure for now.

**Comment by lminiero** [comment]
This is unrelated to the RC patch. That will only improve the unpublish/publish time from a core/webRTC level.

**Comment by lminiero** [comment]
Can you check if the latest commit fixes it? https://github.com/meetecho/janus-gateway/commit/c1bd6f7a69b4abe825029edf8ee7398c8fb919cf
I've added some more checks that should help. The videoroom demo code has an update as well to automatically clean up the local resources when an ```unpublished``` event happens, so you may want to do the same in your web app.

**Comment by mbellezi** [comment]
Ok. I will test it later this week, as we are in the middle of the Carnaval Hollidays here in Brazil. ;)

**Comment by MagicIndustries** [comment]
I'll see if I can test this on our server tonight.

**Comment by lminiero** [comment]
Any update on this?

**Comment by mbellezi** [comment]
I'm unable to do the test the republish because after I updated my version to git Head I'm having problems to subscribe to a stream. After a join a room with ptype: listener, when I do "start", janus is returning error: Unknown request \'start\'. Very strange. I'm trying the near down the problem to, them do the republish test.

**Comment by mbellezi** [comment]
Ok. Problem solved with the start. I was messing with the handler.

Back to the republish, after your update, here is the situation:

After I send the unpublish request to the plugin handler, it immediately hangup the connection, before even the Ack and, after the Ack, it returns an event with the error: 'Can\'t unpublish, not published'

**Comment by mbellezi** [comment]
This last problem may be due the the sending of ICE candidates of the client new webrtc conn shortly after send the unpublish event as you can see in my logs:

```
Thu, 18 Feb 2016 11:47:41 GMT libjanus Sent:  {"body":{"request":"unpublish"},"janus":"message","transaction":"ed80b2","apisecret":"xxx","session_id":3942974593,"handle_id":4227831737}
Thu, 18 Feb 2016 11:47:41 GMT libjanus Sent:  {"candidate":{"candidate":"candidate:4033732497 1 udp 2122260223 192.168.0.104 58258 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0},"janus":"trickle","transaction":"03406e","apisecret":"xxx","session_id":3942974593,"handle_id":4227831737}
Thu, 18 Feb 2016 11:47:41 GMT libjanus Sent:  {"candidate":{"candidate":"candidate:4033732497 2 udp 2122260222 192.168.0.104 63882 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0},"janus":"trickle","transaction":"1d6150","apisecret":"xxx","session_id":3942974593,"handle_id":4227831737}
Thu, 18 Feb 2016 11:47:41 GMT libjanus Received:  { janus: 'hangup',
  session_id: 3942974593,
  sender: 4227831737,
  reason: 'DTLS alert' }
Thu, 18 Feb 2016 11:47:41 GMT libjanus Sent:  {"candidate":{"candidate":"candidate:1898305829 2 udp 1686052606 201.26.216.52 35649 typ srflx raddr 192.168.0.104 rport 59039 generation 0","sdpMid":"video","sdpMLineIndex":1},"janus":"trickle","transaction":"83e79f","apisecret":"xxx","session_id":3942974593,"handle_id":4227831737}
Thu, 18 Feb 2016 11:47:41 GMT libjanus Sent:  {"candidate":{"candidate":"candidate:1898305829 1 udp 1686052607 201.26.216.52 35617 typ srflx raddr 192.168.0.104 rport 62847 generation 0","sdpMid":"video","sdpMLineIndex":1},"janus":"trickle","transaction":"957bca","apisecret":"xxx","session_id":3942974593,"handle_id":4227831737}
Thu, 18 Feb 2016 11:47:41 GMT libjanus Received:  { janus: 'ack', session_id: 3942974593, transaction: 'ed80b2' }
Thu, 18 Feb 2016 11:47:41 GMT libjanus Received:  { janus: 'event',
  session_id: 3942974593,
  sender: 4227831737,
  transaction: 'ed80b2',
  plugindata: 
   { plugin: 'janus.plugin.videoroom',
     data: 
      { videoroom: 'event',
        error_code: 435,
        error: 'Can\'t unpublish, not published' } } }
```
Maybe this is race condition that nulls the participant->sdp during the unpublish process.
I will try to do a complete unpublish before start the new webrtc connection on my side.

**Comment by mbellezi** [comment]
Some good news:
After waiting for the unpublish to completely finish, and waiting around 3 seconds, I can publish again consistently. The new stream is published without the need to detach/attach again.

However, there is still an issue. The streams that were subscribed to that published stream freezes and does not come back alive after the new publish. Is this expected? The webRTC connections for this subscribed streams remain active but without any bandwidth. Any thoughts?

**Comment by lminiero** [comment]
New publish means the old subscribers are done: a new publisher, even with the same id, is different from the publisher that went away, once you unpublish subscribers need to unsubscribe and, in case, subscribe again (which is what we do in the videoroom demo, for instance).

**Comment by mbellezi** [comment]
Ok Lorenzo, thank you for the help. 
Do you know if the 'switch' request from videoroom plugin is working? Or I have to unsubscribe/subscribe to other published stream?

**Comment by lminiero** [comment]
Yep, switch works so you can use that at any time for existing subscribers (assuming the same media/same codecs are being used, of course, since no renegotiation is taking place).

**Comment by mbellezi** [comment]
Great! I will try it soon.

**Comment by lminiero** [comment]
Closing as not an issue, but the way the core works right now (already explained how the reference counters branch will improve this).

**Comment by s-ol** [comment]
Still having this issue in `v0.3.1` and `master`, my code does the following:

* start with running PeerConnection
* send `handle.send({ message: { request: 'unpublish' } })`
* when receiving `msg.videoroom == 'event' && msg.unpublished == 'ok'`
  * (optional delay)
  * `handle.createOffer({ ..., success: jsep => handle.send({ message: { request: 'publish' } }, jsep) })`

my receivers close their listener handle as soon as they receive the `unpublished` event and would open a new listener , but in some cases the new stream doesn't arrive there:

| build | delay | result |
|:----- |------|-------|
| `v0.3.1` | no delay    | `createOffer` fails **silently** (neither success nor error called!)
| `v0.3.1` | 100ms       | `createOffer` succeeds but stream doesn't show up for listeners
| `v0.3.1` | 1000+ms  | reconnection succeeds
| `master` | no delay  | `createOffer` succeeds but stream doesn't show up for listeners
| `master` | 100ms     | `createOffer` succeeds but stream doesn't show up for listeners
| `master` | 400+ms  | reconnection succeeds

in the cases were the stream fails, it doesn't even become a valid connection to janus, I am also not getting a `onlocalstream` callback.

Since it seems like the refcounting *did* kick in with an improvement, the question remains whether this is a client side (`janus.js`) problem or serverside now? It would be very nice if I could get rid of the forced timeout there.
