### ISSUE TITLE
Maybe not depend on doxygen and dot

### ISSUE THREAD

**Issue by oej** [meetecho/janus-gateway#474]
The standard auto configure depends on dot and doxygen. These are documentation tools, normally strictly not needed for building a software. Maybe these should be optional.

**Comment by oej** [comment]
Found --disable-docs in Configure - but configure doesn't tell me about this option. If I don't have libwebsockets it tells me about how to disable it...

**Comment by lminiero** [comment]
Good point, thanks, I'll fix this when I get back on Monday (currently
abroad without my laptop)
Il 26/feb/2016 20:24, "Olle E. Johansson" <notifications@github.com> ha
scritto:

**Comment by lminiero** [comment]
Just changed the way we look for the docs. By default the documentation is disabled, so now it's ```--enable-docs``` for turning it on, rather than ```--disable-docs``` to turn it off.

That said, the ```--disable-docs``` should have appeared already in the configure options before this change, at least when you did a ```./configure --help```: in my case, it appeared in the optional features. Was it missing in your setup?

Closing, let me know if this works as expected for you and if not feel free to reopen.
