### ISSUE TITLE
Refactor janus code

### ISSUE THREAD

**Issue by arec** [meetecho/janus-gateway#500]
Janus is a great project. We use it extensively for our e-classroom app. 
We would very much like to contribute with our bug fixes and enhancements. But we do concern about the overall code readability. There are lots of duplicate code and long methods in the project. Is there any plan to refactor the code?

**Comment by lminiero** [comment]
Already addressed in #476, which is waiting for feedback before I can merge it. If you care about that, please test that branch (nd the new demo it adds) and let us know if that improves things.

**Comment by lminiero** [comment]
No plan to do such refactoring in the near future. We're already doing some heavy refactoring to the code (see reference counters) and will do more (async admin notifications, multistream, renegotiation) in the next few months, which I believe have much higher priority than methods being too long :wink: 

Some repetitions, related to parsing of requests, are already being addressed by @andreasg123 in #494. I don't think we need to do much more than that. Which parts are you mostly concerned about?

**Comment by andreasg123** [comment]
I agree that duplicate code makes maintenance more difficult because a bug discovered in one of the copies likely won't get fixed in the other copies. Long functions are an issue for code readability but in my opinion there is less potential danger.

I have further ideas to reduce code duplication after working on parameter validation. I ran [Simian](http://www.harukizaemon.com/simian/) on some of the code and noticed some obvious candidates.  For example, in the videoroom plugin, leaving a room and unpublishing a stream uses almost the same code. Accessing a room with a pin or a secret also is almost identical.

Each plugin defines the same type struct janus_<plugin>_message with its corresponding free function. That could be put into plugin.h/.c, maybe together with a function to allocate and initialize a message object.

**Comment by lminiero** [comment]
Good points, but don't look too much at the free stuff, as the reference counters pull request, #403, changes that completely.

**Comment by lminiero** [comment]
Closing as being addressed by @andreasg123 in separate PRs.
