### ISSUE TITLE
Request to TURN REST API should be GET

### ISSUE THREAD

**Issue by vivaldi-va** [meetecho/janus-gateway#532]
After some testing using the TURN REST API configuration options, I noticed that janus sends a POST request to the specified API end point. [TURN API draft](https://tools.ietf.org/html/draft-uberti-behave-turn-rest-00#section-2) specifies a GET request should be used instead.

**Comment by lminiero** [comment]
I don't remember why we used POST there. I see we even have a `Some servers don't like a POST with no data` note in there, which means it was not a typo. Possibly tested with a service that only exposed POST itself? That draft, in fact, is just a recommendation on how you COULD do something like this, and not a strict protocol: it only tells you what should be there, in general, in terms of data.

Anyway, a good idea is to probably make this configurable, so that you can use either. I'll have a look at this next week, when I'm back to the office.

**Comment by vivaldi-va** [comment]
Making it configurable makes sense. And yeah, it's not strict, but it threw me off for quite a while trying to make my GET endpoint working. Reading off of the draft I just assumed the GET method.

Plus, using GET may negate the issues of `Some servers don't like a POST with no data`

**Comment by lminiero** [comment]
Implemented in https://github.com/meetecho/janus-gateway/commit/e3ec34043067ed88902da546784f0b47192bff5b.
Feel free to reopen if this doesn't seem to be working for you.
