### ISSUE TITLE
Chrome (or libWebRTC) <-> Janus SIP plugin <-> Chrome (or libWebRTC)

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#574]
I'm facing basically the same as #509 I think.

Basically I'm using the SIP plugin on both sides of a call. Using Firefox on both sides or a mix of Firefox and Chrome works, but when Chrome is used on both sides it fails to set the remote SDP with a (sadly useless) error.

I ran into this when using [this](https://github.com/eface2face/cordova-plugin-iosrtc) plugin.

[Here](https://gist.github.com/saghul/8514bae95803178593ef35420a97e0f5) is a Gist with local and remote SDPs, before and after Janus mangling.

The only weird thing I see is that Chrome itself leaves some fmtp lines behind when generating the answer SDP with a single codecs.

Any ideas @lminiero?

**Comment by lminiero** [comment]
If those fmtp lines are the cause, they're left behind by Sofia SIP for some reason. Have you tried munging the SDP before passing it to setRemoteDescription, to remove those extra fmtp you see? A possibly quicker way to do a dirty check is modifying the check [here](https://github.com/meetecho/janus-gateway/blob/master/sdp.c#L1142) by turning it into a `if(rm->rm_fmtp && rm->rm_pt == 100) {` (so that only VP8 is left).

**Comment by saghul** [comment]
I'll do that in JS to see if it fixes it.

**Comment by saghul** [comment]
Success! Removing those made Chrome happy!

Here is some code sample using [sdp-transform](https://github.com/clux/sdp-transform) which should do the job:

~~~~
function mungeSdp(sdp) {
    let parsedSdp = transform.parse(sdp);

    // remove bogus rtcp-fb elements
    for (let media of parsedSdp.media) {
        let payloads = String(media.payloads).split(' ');
        if (media.rtcpFb) {
            media.rtcpFb = media.rtcpFb.filter((item) => {
                if (payloads.indexOf(String(item.payload)) === -1) {
                    return false;
                } else {
                    return true;
                }
            });
        }
    }

    return transform.write(parsedSdp);
}
~~~~

**Comment by lminiero** [comment]
But this means I'll have to fix that in Janus too... so messing with the SDP and trying to figure out why Sofia leaves them there :sob: 
Remind me to do that if I forget!

**Comment by saghul** [comment]
Wait, is that so? Doesn't Sofia "blindly" just use the SDP we feed it? I can get some more logs if need be I guess.

**Comment by lminiero** [comment]
In the SIP plugin, Sofia SIP does handle SDP internally when it parses it and produces answers. One example is the fact that in answers it negotiates a single payload type no matter how many you had, unless you specify otherwise (if you recall we talked about this). The problem here is that, when it removes those extra payload types to only leave one in, it leaves the attributes related to removed payload types in, which is what you experienced. In the core we then produce our own SDP to add all the extra stuff, but we obviously still rely on the Sofia SIP SDP object to know what we should add, in terms of media lines, attributes, etc. The check I suggested to play with is an example: we iterate on all formats that are in the struct, and add those to the SDP we render. The fact that they're still there means Sofia SIP didn't remove them when pruning payload types, which means this is something we'll have to do in the core ourselves.

One way to do that, I guess, is using the `audio_payload_types` and `video_payload_types` list we compile when merging the SDP. When adding those fmtp attributes, we check those lists, and if the pt is not in there we skip the fmtp. Should be easy enough, and should work. I'll let prepare a PR you can test to see if it fixes the issue for you, hopefully today.

**Comment by lminiero** [comment]
Sorry, by fmtp I meant rtcp-fb...

**Comment by lminiero** [comment]
Can you let me know if that works for you? I replicated the issue messing with the EchoTest plugin and it seems to do the job, but I want to make sure it works for you too...

**Comment by saghul** [comment]
It's a bit hard for me to test right now, but I'll let you know once I do. At any rate, if you managed to reproduce it, I trust you! 😺

**Comment by saghul** [comment]
Also, thanks for the explanation about the Sofia SDP dance, I had forgotten 😝

**Comment by lminiero** [comment]
> At any rate, if you managed to reproduce it, I trust you!

Better not trust me on anything, I'm messy! :smile:
