### ISSUE TITLE
Janus.isWebrtcSupported() failing

### ISSUE THREAD

**Issue by revmischa** [meetecho/janus-gateway#598]
I'm using Chrome viewing a page served from localhost (not file:///) which should be considered a secure origin. `Janus.isWebrtcSupported()` returns false, because window.getUserMedia isn't set. It should be checking `navigator.mediaDevices.getUserMedia` instead. This got renamed.

**Comment by revmischa** [comment]
in janus.js it varies between getUserMedia(), window.getUserMedia(), navigator.mediaDevices.getUserMedia(), and navigator.mozGetUserMedia().

**Comment by lminiero** [comment]
"Chrome" doesn't say much. Which version? I use it on localhost all the time and no problem here.

**Comment by revmischa** [comment]
Chromium Version 51.0.2704.79 Ubuntu 15.10 (64-bit)
Are you

**Comment by lminiero** [comment]
Port 8000.

**Comment by revmischa** [comment]
Well window.getUserMedia is undef for me, navigator.mediaDevices.getUserMedia is not.

**Comment by serdardurbaris** [comment]
I also had problem with Chrome. I take time out warning at server side.  I can't send video by chrome. But it works on yandex seamless. My chrome version on my computer 52.0.2743.116m (64bit)

**Comment by karth295** [comment]
The `isWebrtcSupport()` check fails for me in Chrome version "52.0.2743.116 m" on Windows. If I ignore that check, I get an error in the console: "janus.js:197 WebRTC not supported by this browser", but I can send/receive video just fine.

**Comment by lminiero** [comment]
@revmischa @karth295 @serdardurbaris please check the PR I referenced.

**Comment by karth295** [comment]
@lminiero that PR didn't solve the issue for me--I just realized that I have a different issue than @revmischa . For me, the issue is that `window.RTCPeerConnection` is not set when I call `Janus.isWebrtcSupported()`.

It does get set later (I guess when `adapter.js` runs?), and `isWebrtcSupported()` returns true.

I'm calling `isWebrtcSupported` in the `Janus.init` callback, which is in the same place as `videoroomtest.js` (https://github.com/meetecho/janus-gateway/blob/master/html/videoroomtest.js#L73). The difference is that I'm calling it immediately, while videoroomtest waits for user input.

```
Janus.init
  callback: () ->
    if not Janus.isWebrtcSupported()
      alert("You must use Chrome, Firefox or Edge")
```

**Comment by lminiero** [comment]
@karth295 got it, probably a "race condition" where even if we wait to include the libraries before invoking the `init` callback, te library still doesn't load fast enough when you use it. I remember a similar problem with jQuery. This is never an issue for me because I already have both adapter and jquery in the `<src>` of the HTML, and so they're already loaded when the method is called.

Any suggestion on how to make sure we confirm the success of `init` only when the libraries have been completely loaded?

**Comment by karth295** [comment]
@lminiero Looking at `janus.js` it looks like your loading your scripts correctly. I think the issue is that you're invoking the callback multiple times. In fact, I get that `alert` message 3 or more times.

**Comment by lminiero** [comment]
Then please report on the PR I mentioned as that's where I'll update the code to then merge it. If you have suggestions on fixes even better :smile:

**Comment by revmischa** [comment]
I believe this solved my issue, thank you

**Comment by ShettyRakshith** [comment]
I just tried to setup janus in chrome.Adapter Not defined in isVideoSendEnabled(). please assist.

Thanks in advance

**Comment by lminiero** [comment]
Make sure you're using the latest `janus.js` from master, we fixed something in this just a couple of days ago.

**Comment by ShettyRakshith** [comment]
Helo Meetecho,

Thank you for concerned reply, can you please let me know the latest
version or just pass me the link.

waiting for reply

Thanks and regards
Rakshith

**Comment by ShettyRakshith** [comment]
@lminiero which is latest version ? can you just pass me the link?
Thank you

**Comment by lminiero** [comment]
You're on a github repo, it should be pretty obvious which one is the latest... just do your homework.
