### ISSUE TITLE
heap-use-after-free (event-handler branch)

### ISSUE THREAD

**Issue by cacheworks** [meetecho/janus-gateway#609]
Hello,

I've been using the event-handler functionality extensively (thanks again for the great feature!) but I've been getting some crashes (once a day or every 2 days).

I recompiled with libasan to get some meaningful logs, it seems like this made it worse (hourly crashing) so I'm not sure if it's the same crash as before

I got the following trace pointing to [ice.c:3350](https://github.com/meetecho/janus-gateway/blob/event-handlers/ice.c#L3350) on most of these crashes;
https://gist.github.com/cacheworks/e844e22099110ac0fa9d9ea0d6d342ae

and once it pointed to [ice.c:3325](https://github.com/meetecho/janus-gateway/blob/event-handlers/ice.c#L3325);
https://gist.github.com/cacheworks/27b4e8132e3fea636fa27e6f8293e937

They both seem to be caused by session being used after being freed in [janus.c:550](https://github.com/meetecho/janus-gateway/blob/event-handlers/janus.c#L550)

This was compiled using the latest commit ( ff455ccef040b5eac64e085fc36df888319d50a2 )

Unfortunately I had the ulimits for the core dump not set properly in that session, I hope AddressSanitizer is sufficient, otherwise I'll go back to get a gdb trace too

Thanks for your help in advance, I can't quite make sense of the code enough to see how to fix this in a PR yet but am getting more familiar with it using your debugging instructions

**Comment by lminiero** [comment]
libasan feedback is actually preferred, as sometimes it tells us why something has crashed and not only where. This seems to be the case here, as in both the logs it crashes when generating a new event. More specifically, in both cases it crashes because we access the `session->session_id` in the ICE send thread, but libasan says the session was already freed. This should never happen, as before closing sessions, all its handles are closed as well, which includes their threads. Besides, we destroy sessions lazily after a few seconds, and not right away. Apparently, in this case some race condition causes the ICE send thread to outlive the session lazy destruction, which causes your crash.

If you can confirm this is only happening in the event handlers PR and not master, then something in there is causing this possibly slower cleanup of resources. One quick fix might be only reading the `session->session_id` property once when the thread is created and accessing a local variable when it's needed, but that's only half of the solution. I should check why that thread keeps on living, and if the same issue might be happening for the handle pointer too, and only hidden by the fact that the invalid session pointer makes it crash first.

**Comment by cacheworks** [comment]
Thank you for the quick detailed response :+1: 

I haven't compiled the master branch with libasan yet, I'll do that first to confirm whether this is related to changes in this branch.

**Comment by lminiero** [comment]
Any update on this? The event handler branch is something I'd like to merge soon, possibly after I come back from the IETF meeting, so if the issue is still there we'd better fix it soon.

**Comment by cacheworks** [comment]
I tried the master branch right after this and ran into another issue;
https://github.com/meetecho/janus-gateway/issues/613 and https://github.com/meetecho/janus-gateway/issues/615

Then I moved on to the refcount branch and ran into some other things which we just discussed there

Since most of these issues only seem to appear when I actually use the server in production for a while it's hard to keep testing multiple

**Comment by cacheworks** [comment]
Closing this due to the amount of changes since this was opened. 👍 
I just got 15 days uptime with the main branch (from before events got merged.)

Since the event-handler got merged with the reference counter branch I'll start using that now to see if there are any race conditions left there
