### ISSUE TITLE
heap-use-after-free (utils.c:117 janus_flags_is_set)

### ISSUE THREAD

**Issue by cacheworks** [meetecho/janus-gateway#613]
Hello!

After running into the heap-use-after free on the event handler branch I gave the main branch a go and got some new AddressSanitizer output (After running for 5 days)

I'm creating a new issue for this as it doesn't seem to be related to #609

Here's the AddressSanitizer output;
https://gist.github.com/cacheworks/c70f8aee3a504b75931bc978568b46e8

It seems to mainly be caused by janus_flags_is_set being invoked on [ice.c:2187](https://github.com/meetecho/janus-gateway/blob/0d537c71e94c603c650a89740b7d7ae89c20e47b/ice.c#L2187)

This was compiled from commit 0d537c71e94c603c650a89740b7d7ae89c20e47b 

Any insight on how this can be solved is much appreciated. (Or is it better in your opinion to focus efforts on debugging the refcount branch at this point?, Looks like the refcount branch changed this thread [refcount/ice.c:2113](https://github.com/meetecho/janus-gateway/blob/refcount/ice.c#L2113))

Thanks!

**Comment by lminiero** [comment]
Sounds like a corrupt stack or something like that. It says it can't access the handle because the memory was freed, but the line it refers to is related to a packet data and has nothing to do with that.

Anyway yes, the more you test and debug the refcount branch the better, as at least in theory it's a much more robust mechanism for managing the memory in Janus. It's been around a long time and no one has played with it much yet: I'd very much like to get rid of any bug there and verify whether it's stable enough, so that we can merge it.

**Comment by cacheworks** [comment]
Thanks for having a look and explaining once again.
I will start using the refcount in production for a while and see what results or debug info I get

Closing this as the refcount branch will hopefully fix this then
