### ISSUE TITLE
Image changes every 30 seconds in Chromium

### ISSUE THREAD

**Issue by lukasz-zaroda** [meetecho/janus-gateway#624]
Chromium version: 53.0.2785.116

1. In Firefox everything works perfectly.
2. In `chrome://webrtc-internals/` in `Conn-video-1-0 (googCandidatePair)` I can see `bytesReceived` constantly increasing, so I think the data is there, but for some reason is not being turned into a video.

How can I debug it further?

Also, I'm using h264 codec. I tested it with a different profiles.

**Comment by alexamirante** [comment]
Some context may help...
I suspect you're using the streaming plugin, right? If so, how are you encoding and sending the stream? From which operating system?

**Comment by lukasz-zaroda** [comment]
I'm streaming video from the camera attached to the Raspberry Pi with the command:

`raspivid --nopreview -hf -vf --width 800 --height 600 --framerate 15 --bitrate 2000000 --profile baseline --timeout 0 -g 4 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=8004`

The `Janus` is of course installed there. In `janus.plugin.streaming.cfg` I have this:

```
[gst-rpwc]
type = rtp
id = 1
description = RPWC H264 test streaming
audio = no
video = yes
videoport = 8004
videopt = 96
videortpmap = H264/90000
videofmtp = profile-level-id=42e028\;packetization-mode=1
```

**Comment by alexamirante** [comment]
Yeah, I figured that out since I've been playing with the raspicam and raspivid in the last few days.

Tomorrow I'll write a post about this on the [meetecho-janus](https://groups.google.com/d/forum/meetecho-janus
) discussion forum, sharing my findings.

Long story short: if you add the `do-timestamp` option to `fdsrc`, your decoded framerate should improve in Chrome. Anyway, I was still experiencing some glitches in decoding the h264 stream, and the quality was not that good.

I managed to achieve good quality in both Chrome and Firefox by piping raspivid into ffmpeg rather than gstreamer, and also passing a further parameter to raspivid itself. I'll be more precise tomorrow when I'm back at my laptop.

Closing this as we use github only for code issues. Stay tuned on the meetecho-janus forum!

**Comment by lukasz-zaroda** [comment]
I don't think this is a problem with a slow decoding framerate, the frame changes exactly every 30 seconds, with every long poll. So I guess this is not a matter of speed, but something else blocks the video here.

**Comment by ploxiln** [comment]
It sounds like only keyframes are being decoded. Just a guess.

**Comment by lminiero** [comment]
Alex mentioned that some timestamps related option in gstreamer fixed that, so it may very well be related to weird timestamps being set at the source that mess up the presentation info in the browser. Anyway, nothing that is related to a bug in Janus, so best discussing this on discuss-webrtc.

**Comment by alexamirante** [comment]
@lukasz-zaroda it's a matter of how Chrome decodes frames, and it should have something to do with how gstreamer handles timestamps I guess. If you open the webrtc-internals, under `Stats graphs for ssrc_xxxxxxx_recv (video)` you can check the `googFrameRateDecoded` graph.

Anyway, did you try to add the `do-timestamp=true` option to `fdsrc`?

**Comment by lukasz-zaroda** [comment]
@alexamirante I was too busy last time to get into this, but thanks for reminding me. I tried it just now and indeed it worked! :D Thank you very much for help!
