### ISSUE TITLE
Track media stream ID from round-trip

### ISSUE THREAD

**Issue by revmischa** [meetecho/janus-gateway#627]
My problem is that I would like to keep track of a request for a stream by ID and the response.

Right now if I request a stream using the streaming plugin with `{ "request": "watch", "id": id }`, when I get the `onremotestream` the resulting media stream has the fixed ID `"janus"`, instead of `id`.
Without the server returning the matching ID, I don't see how I can keep track of responding to the appropriate request with the appropriate media stream.

**Comment by lminiero** [comment]
Not sure I understand the question. The media stream you see in the SDP has nothing to do with the Streaming plugin-level stream identifier, which is specific to its application logic. You map incoming asynchronous responses to a request by the transaction identifier of the Janus API.

If your problem is in mapping an `onremotestream` to some transaction, we only support a single PeerConnection per-handle anyway, so whenever `onremotestream` is invoked on a handle you know  it's related to the WebRTC setup you started on that handle.

Closing as not an issue.
