### ISSUE TITLE
H.264 gap robustness

### ISSUE THREAD

**Issue by superdump** [meetecho/janus-gateway#635]
A colleague is currently looking into robustness of recording H.264 streams and the playability of the resulting post-processed mp4 files in Quicktime and Windows Media Player.

The test he is doing is basically as follows:
- set up a recording session (using videoroom I think) and configure h.264 to be used when creating the room
- while the recording is in progress, use iptables rules to drop all traffic for a few seconds and then enable traffic again
- use `janus-pp-rec` to convert the video mjr to an mp4
- try playing that file back with Quicktime or WMP and observe simply black video
- re-post-process the mp4 video using `ffmpeg -fflags +genpts -i video.mp4 -codec copy video_fixed.mp4`
- try playing back the resulting file in Quicktime and WMP and observe that the video plays, freezing on a single frame for the duration of the gap and then continuing

Given that the ffmpeg genpts option works around the problem I suspect some issue with the timestamp handling in janus-pp-rec.c or pp-h264.c. Any ideas?

**Comment by lminiero** [comment]
The place where the ffmpeg stuff is used for h264/mp4 is `pp-h264.c`, and it's very likely that there are pts/dts inconsistencies there that may cause the issue. Not an expert on this stuff, though, so any feedback (and why not, fix!) is welcome!

**Comment by superdump** [comment]
It seems I was wrong, the test done was actually with no packet loss. Post-processing with janus-pp-rec produces a file playable with VLC but not Quicktime (black) nor WMP (black.) Running the post-processed file through `ffmpeg -fflags +genpts ...` makes the file playable on Quicktime and WMP. So it seems that rather there is always something wrong with the timestamping for MP4 files produced with janus-pp-rec. I'll try to look into to see if I can make some headway.

**Comment by superdump** [comment]
I've tested some more myself now and it seems that not even `-fflags +genpts` is needed. Simply `ffmpeg -i video.mp4 -codec copy video-fixed.mp4` produces a file playable by QuickTime.

FFmpeg does spit out this message: `[mp4 @ 0x18b2440] Codec for stream 0 does not use global headers but container format requires global headers`.

I suspect that this is the real issue - something to do with the SPS/PPS not being handled properly when writing the data into an MP4 container in janus-pp-rec... perhaps. 😄 The plot thickens.

**Comment by superdump** [comment]
MP4 apparently requires 'AVCC' format headers globally and not local, in-stream SPS/PPS as per Annex B.

This could be a problem for streams that change resolution for example in that if we write the initial SPS/PPS into the MP4 headers, the resulting file could be perhaps initially playable but have non-playable parts. But that is perhaps a later problem to address.

Initially if we take the probably more common case that resolution remains constant, if we take the first SPS/PPS seen and copy it with the appropriate FFmpeg padding to `vFrame->codec->extradata` then it may solve the basic case.

**Comment by lminiero** [comment]
Resolution can change, though, browsers don't stick to one if network conditions change (at least that's true for VP8/VP9, don't know if they do that on H.264 too). If that can really result in broken media files, that may be an issue.

Anyway, if you can provide a patch to address the SPS/PPS thing that would help! Otherwise, we can just add a final line to the post-processing that notifies about the potential issue you addressed, and refer to this issue and/or to the ffmpeg command to regenerate the PTS stuff.

**Comment by superdump** [comment]
I think libvpx does the resolution adjustment internally. I don't think OpenH264 (Chrome and Firefox at least both use OpenH264 for encoding) has any such logic and sticks with the resolution of the input. It would have to be H.264 from a 'smarter' WebRTC stack I guess.

I don't think the PTS needs regenerating, just the SPS and PPS writing into the extradata.

**Comment by lminiero** [comment]
Any more feedback on this?

**Comment by superdump** [comment]
Not currently, no.

**Comment by khatribharat** [comment]
Facing the same issue here.

**Comment by lminiero** [comment]
As I said, I have no expertise on H.264 and it's a codec I really don't care about, being proprietary. Any contribution is more than welcome: if you expect me to fix this (whatever this is) it will take more than a while as it's pretty low on my priority list...

**Comment by lminiero** [comment]
@superdump any hint on how to access the SPS/PPS data you mentioned? We don't decode the video when post-processing, so if that's needed we can't do it. We do have some code to process a SPS in order to extract width/height, but no idea if it can be reused.

**Comment by superdump** [comment]
Off the top of my head, you need to identify the appropriate NALU for SPS and PPS, concatenate them in some way and give them to libavformat. You don't need to be able to parse the SPS/PPS necessarily, just jam them into the extradata. I don't recall anymore what was done around this. Maybe @peffis knows?

**Comment by peffis** [comment]
Yes, you need to extract each SPS/PPS and put them in the MP4 header if you want to create an MP4 that is not in the bitstream format. An overview of writing such an MP4 with libav could look something like this: 

```c
AVFormatContext *fctx = avformat_alloc_context();
fctx->oformat = av_guess_format("mp4", NULL, NULL);

AVStream *vStream = avformat_new_stream(fctx, 0);
vStream->codecpar->extradata = build_extradata(...);

AVStream *aStream = avformat_new_stream(fctx, 0);
aStream->codecpar->codec_id = AV_CODEC_ID_AAC;

fctx->pb = avio_alloc_context(..., &my_write_packet, &my_seek);
fctx->flags = AVFMT_FLAG_CUSTOM_IO;

avformat_write_header(fctx, NULL); /* Writes MP4 header */

av_write_frame(fctx, &packet);     /* write incoming packet */
...
av_write_frame(fctx, &packet);     /* write incoming packet */
...
av_write_trailer(fctx);            /* write moov atom       */ 
av_free(fctx);
```

The problem here is the "build_extradata" part which involves putting all the found SPS and PPS frames together according to the extradata field (which is partially explained at for instance http://aviadr1.blogspot.se/2010/05/h264-extradata-partially-explained-for.html). 

One issue is apparent from the code above - you need to find all the SPS/PPS:es first with a scan through the file and then start writing the header. Otherwise, if you want to do this in real time before the whole stream is recorded, you need to find a way to make libav rewriting the extradata which I don't think is currently supported by libav. 

Another thing: If you also just naively collect and assemble all the SPS/PPS NALU:s into your extradata field you will run out of space, because the size of the extradata field is finite (and small -
 see the link above - it supports 32 SPS frames and 256 PPS frames) and the number of SPS/PPS in a stream could be (not infinite but at least) much larger as a stream has no global memory - the SPS:es can be overridden by just sending a new SPS with the same ID. In the past it was also very different how Chrome and Firefox reused SPS id's in the stream (chrome kept reusing and overriding id 0 but firefox stepped up the id for each i-frame).  So supporting storing an H264 stream to a MP4/AAC in general you need to apply first some heuristics but also, in the general case, some transcoding in order to fit all the SPS/PPS frames. What I noticed though in this work is that it is rare that you can create more than 32 unique resolution changes in a WebRTC session so it is likely possible to reusing SPS:es but rewrite the PPS to point to the existing SPS:es for that resolution. 

But, to come back to the question, finding the SPS:es and PPS:es is not the problem here. They have their own NALU type (which is already in the janus post-processing code to extract the width and height) so they can in theory be a NALU by themselves. In practice though they are usually sent bundled together inside the STAP-A type of NALU so you need to look into those also. The problem here, if you want to create an MP4 that is not in the bitstream format, is more to decide what you do when you receive SPS number 32 in the stream.

**Comment by lminiero** [comment]
I recently found out that, when you have an `AVCodecContext` associated with an `AVStream` belonging to an MP4 `AVFormatContext`, then the Annex-B to AVCC translation is done by the codec internals, and the extradata field is filled in automatically. This is definitely true when encoding directly with the library. Not sure if we can "fool" the library by creating an `AVCodecContext` we'll never really use just for having the SPS/PPS written in the extradata part for us: we might create a context with the info we know we have (resolution and FPS for sure), and then never use it and just write the packets we extract directly to the format. I realize it's a hack, but extracting the SPS/PPS from the traffic and writing them manually to the extradata sounds like a lot of work (did a bit of research on that and didn't find anything easy to integrate), work that I honestly have no will to do for a codec I don't really care that much about. Of course, I'd be glad to accept contributions that solve this properly.

**Comment by lminiero** [comment]
@superdump @khatribharat @peffis please let me know if this fixes the issue: https://github.com/meetecho/janus-gateway/commit/37d1005677cc2601506f8b9e6c9cda334b6c62cb

**Comment by lminiero** [comment]
Closing as we didn't get any update after my latest commit. Please let us know if it's still an issue.
