### ISSUE TITLE
Clarification on How Non-Permanent Dynamic Rooms are Cleaned Up

### ISSUE THREAD

**Issue by joshdickson40** [meetecho/janus-gateway#638]
Ran into this issue when trying out the events PR and can't find any existing docs.

Say that I have a user who has dynamically created and joined an audio room. Their connection suddenly goes bad. Janus will notice that something is wrong and eventually clean up the handle.

What happens to the room? My expected behavior was that the room would be cleaned up as soon as it was empty for a few seconds, but it looks like it sticks around.

Is there something I am missing that would tell Janus to discard empty rooms (& presumably send me room destroyed events! :) )

**Comment by lminiero** [comment]
Rooms stay there until you explicitly destroy them. The `permanent` flag is only to decide whether or not a create/destroy should be reflected in the static configuration as well.

**Comment by lminiero** [comment]
PS: closing as not an issue.

**Comment by joshdickson40** [comment]
What is the recommendation here, use the Admin API to monitor for empty rooms and delete them that way?

I know that the real recommendation is to have the client trigger room close on leave, but that's obviously not reliable.

**Comment by lminiero** [comment]
You can't use the Admin API for that, as the Admin API currently only allows you to query handles, so something associated with users. It cannot poll the internals of a specific plugin out of context. What you can do, though, is using a "ghost" handle that acts as a manager for the plugin: that is, a handle you create yourself towards the AudioBridge/VideoRoom plugin, so that from there you can create/destroy/list and nothing else (no PeerConnection). That's what we do in our own server-side wrapper, for instance.

**Comment by joshdickson40** [comment]
Well... this is more complicated than expected.

Have you thought about making rooms auto-close at least by room configuration? Am I missing something that makes that a poor design choice? Seeing as handles are cleaned up, I would expect other things would be as well?

**Comment by lminiero** [comment]
It's not that complicated, really, and we use this a lot. Besides, I'm not a fan of automated behaviour, especially on something like this. Autodestroying a room when the last user leaves can lead to undesired outcomes, and having to recreate rooms/resources again and again in case of occasional issues. Janus should be seen as a server that allocates resources according to your needs: every logic associated to the management of these resources (rooms included, in this case) is left to the application.

**Comment by joshdickson40** [comment]
I implemented this over the weekend in the AudioBridge plugin as a test. It's behind a 'persistent' flag for dynamically generated rooms. I didn't realize that all plugin events necessitated a valid `handle_id` and `session_id`, so I had to create a new method to be able to push an event through that did not have either of those. Regardless of this issue in particular, I do think it's an issue that a plugin (even a third-party plugin, which is essentially what my version of the AudioBridge is at this point) cannot send events with its own logic and it's forced that every one has a valid handle and session associated.

It's not that your suggestion is majorly complicated (and thank you very much for sharing), it's just a lot more complex than the plugin taking care of it, given the fact that there's already a plugin watchdog thread that's best positioned to know this information and take action. Also, the underlying number here, i.e. the number of active connections, is *already* automated in the sense that Janus purges inactive connections even if those connections are not explicitly closed by the front-end client.

I don't think the recreating rooms/resources concern is all that valid because you'd only want to do this for dynamically generated rooms anyway, and presumably there is already logic to essentially partition a new room if one does not exist on when joining. At least this was our design pattern.

I would love to merge it in (or at least have a discussion about it via PR) if possible, but I also very much understand your point of view and if that's a waste of time and not a direction you'd like to go, I won't waste time on that. Thank you for your replies and insight on this.

**Comment by lminiero** [comment]
I don't see any harm in having a new option called something like "autodestroy" or something like that when creating rooms. Of course that would have to be mutually exclusive with persistent: that is, you can't have a persistent room that autodestroys, it makes no sense. You CAN, though, have a non persistent room that does NOT autodestroy, which is the current default behaviour and should stay like that I guess.

Implementing the feature is probably as easy as removing the room from the list and setting the `destroyed` property when the last user leaves, so that the mixer thread automatically adds to to the list of rooms to free, something I can try to add myself as soon as I have some time to do that. Anyway, if you have a PR ready feeel free to share it, so that we can check if it's easily mergeable. That said, if it tries to go around/behind the "standard" communication mechanism plugins expose by adding a separate control channel, not sure we can incorporate that, as once you go down that road it starts to become hacks and backdoors, something we'd rather avoid.

**Comment by joshdickson40** [comment]
Yeah, that's pretty much [what I have the process as](https://github.com/joshdickson40/janus-gateway/tree/segmented) - there are a bunch of unassociated/experimental changes here too but I'm not sure of the best way to show the diff. The only issue with PR'ing this now is some of it has to do with the events PR, so maybe we want to wait until that is merged.

Your autodestroy/persistent logic is exactly right where this only affects rooms that have nothing to do with the configuration file (i.e. read from it or saved to it), and setting the `destroyed` property is exactly what I implemented. There is a short timeout (~3 seconds) so the room is not cleaned up immediately upon creation before anyone can join.

> Implementing the feature is probably as easy as removing the room from the list and setting the destroyed property when the last user leaves, so that the mixer thread automatically adds it to the list of rooms to free, something I can try to add myself as soon as I have some time to do that.

This is what I thought when I got started - unfortunately, the events PR has complicated this. My desire here was to very much *not* try to introduce some sort of new, ad-hoc messaging system and if what I did is not right from your perspective, I'm obviously more than open to re-implenting this in a better way.

The bottleneck here is in the call to [`janus_plugin_notify_event`](https://github.com/meetecho/janus-gateway/blob/event-handlers/janus.c#L2982) and the eventual call to `janus_events_notify_handlers`. What we want to do is send a plugin-originated message, but as the room is empty, the message is by definition not originating from a valid handle or session. 

To do this I wrote a separate routine [`janus_plugin_notify_system_event`](https://github.com/joshdickson40/janus-gateway/blob/segmented/janus.c#L3012) (this probably needs to be renamed) that only requires knowledge of the originating plugin and the message and ignored the validity checks, and then calls `janus_events_notify_handlers` with only the information it has (i.e. no `session_id` and no `handle_id`). I then changed the logic of [`janus_events_notify_handlers`](https://github.com/joshdickson40/janus-gateway/blob/segmented/events.c#L55) to accept that it's possible that a plugin-originated events does not have session or handle related fields. I implemented this by not sending those fields entirely in the JSON message, but have no real opinion on if it's better to do that or better to send them with some sort of marker to show that the field is invalid. 

My guess is you might think of a better way to handle the logic here, this is just what worked for me while I was experimenting with this. The only real key is that the watchdog in each plugin has got to be able to call `janus_plugin_notify_event` without a valid session, and I am not particular to any method of doing that.

Maybe the right course of action here is to:
1. Let me know what you think the logic flow ought to be for managing the event send issue / you making a change in the events PR to allow this to occur
2. Wait for your events PR to be merged
3. I can submit a PR that adds the "autodestroy" field to the room plugins

**Comment by lminiero** [comment]
AAh ok I think I get your point now. You're right, the Events PR doesn't currently allow you to send events not related to a specific handle, and we're kind of highjacking the feature when, for instance, we send "room destroyed" events from a specific handle rather than another. It definitely makes sense to allow plugins to send out-of-context events to the core as well. I'll change the callback mechanism there to allow for that.

**Comment by joshdickson40** [comment]
> It definitely makes sense to allow plugins to send out-of-context events to the core as well.

Exactly. Okay, agreement here. Thanks Lorenzo.

**Comment by lminiero** [comment]
Just implemented that in https://github.com/meetecho/janus-gateway/pull/536/commits/c734a91a851ee31bb1d34e6462139cc06d637d33
Rather than adding a new method, this simply extends the existing one to have the plugin sending the event as part of the parameters. Before, this was implicit, as we extracted this from the plugin session: since that may be missing, we need an explicit way to address the source plugin.

**Comment by lminiero** [comment]
I haven't modified any plugin to send out-of-context events yet, though.

**Comment by joshdickson40** [comment]
Great. That change looks much better and more consistent than what I did. I will follow up in the events PR after testing out the changes.

As always, thank you very much Lorenzo.
