### ISSUE TITLE
Make simple functions inline

### ISSUE THREAD

**Issue by andreasg123** [meetecho/janus-gateway#648]
Now that there are more small functions, it would be nice if they would be expanded inline automatically.  I would suggest adding one of the following early in `configure.ac`:

```
CFLAGS=" -g -O3"
CFLAGS=" -g -O2 -finline-functions"
```

**Comment by andreasg123** [comment]
Maybe using `-O3` [isn't always the best](http://stackoverflow.com/questions/11546075/is-optimisation-level-o3-dangerous-in-g).

**Comment by lminiero** [comment]
Can't those be set before configuring by the user, if that's what they want for Janus? I wouldn't optimize too much by default.

**Comment by saghul** [comment]
Do you have any numbers on how much turning `-finline-functions` improves performance? For Janus that is, not a microbenchmark.

**Comment by andreasg123** [comment]
No, I don't have any numbers.  I only noticed the many functions that are one to five lines long.  One could experiment with a small `-finline-limit` to only cover those functions.

It can easily be configured by the user but most people may not know that:

	./configure CFLAGS='-g -O3'

**Comment by andreasg123** [comment]
Just out of curiosity I determined the sizes of the generated code for different flags (total size of all *.o files).

| Flags | KB |
| --- | --- |
| -g -Os | 7384 |
| -g -O2 | 8128 |
| -g -O3 | 8392 |
| -g -O2 -finline-functions | 8392 |
| -g -O2 -finline-functions -finline-limit=100 | 8404 |
| -g -O2 -finline-functions -finline-limit=50 | 8284 |
| -g -O2 -finline-functions -finline-limit=20 | 8096 |

Inlining functions doesn't add that much in size.  Still, it may not be worth it.

**Comment by lminiero** [comment]
Not sure what a safe default would be (I seem to remember I had some issues in a PR that was contributed with plugins failing to use some core functions when they were inline, but in that case they were explicitly marked as inline, and might have been my compiler), so I'm a bit hesitant to change that. But something I can definitely do is adding some comment lines in Makefile.am to reference the suggested values, so that people can adapt to their needs. As an alternative, we might expose some additional configuration lines to override that (not sure a simple CFLAGS prefix to the configure would do that with how our Makefile works right now).

**Comment by lminiero** [comment]
Closing.
