### ISSUE TITLE
is gateway down ? janus.transport.pfunix.cfg

### ISSUE THREAD

**Issue by korb3n70** [meetecho/janus-gateway#667]
hi i'm running Janus Gw on a raspberry pi i'm stuck on this error , seems the HTTPS is sending invalid data during is it an installation issue i see a missing file on the janus.log .

![januserror](https://cloud.githubusercontent.com/assets/13883493/19539638/bcc41df6-965a-11e6-99c7-c9f1aff7e927.jpeg)

**Comment by uxmaster** [comment]
GitHub is only for code issues. You are probably better off using the mailing list: https://groups.google.com/forum/#!forum/meetecho-janus for questions.
 
That being said, you probably forgot to do `make configs`, that's why Janus is complaining.
On the other hand the browser is complaining, that you do not have a valid SSL certificate.

**Comment by lminiero** [comment]
You open the :8889 address in the url bar first, to accept the self-signed certificate, otherwise AJAX requests fail (they don't prompt the user, they just fail). All that's extensively explained here: https://janus.conf.meetecho.com/docs/deploy
Closing since, as @uxmaster said, this is not a code issue.
