### ISSUE TITLE
Contrib: debian docker image for CI and testing...

### ISSUE THREAD

**Issue by krull** [meetecho/janus-gateway#671]
Greetings meetecho!

Let me direct your attention to a debian based docker build I have done here:

https://github.com/krull/docker-janus

Since I have build janus-gateway successfully in jessie before, I thought the idea of having docker images involved would make for a good fast way to have a janus setup up and running.

I mostly use this to do some Continuous Integration Testing on our application stack as well as to see if my Autonomous Build at hub.docker.com would build successfully.

Feel free to use, fork, PR, contibute, etc... all you want. Just want to contribute in a healthy manner back to meetecho's good work.

Great work guys. Keep it up.

B

**Comment by lminiero** [comment]
Cool effort, thanks for sharing! We do use docker ourselves a lot for our Janus-based deployments, so it's nice to know other people do the same.

If you want I can add a reference to this project to the [resources](https://janus.conf.meetecho.com/docs/resources) page of our documentation, so that interested users can find info about that more easily. Make sure you also talk about it on the Google group, as that's where discussion on Janus usage happens.

**Comment by krull** [comment]
Hi Iminiero,

That would be awesome!

If you have a look at the `Dockerfile`, you will see that I wanted to see whether `sh` in docker would be flexible enough to provide the build conditions correctly. Seem like so. I am considering adding more `ARG` arguments that would make the build flexible.

I will join the Google group and spread the word.

**Comment by lminiero** [comment]
Closing as not an issue, we can keep the discussion on the group.
