### ISSUE TITLE
Mixed malloc and g_free may leading to memory corruption

### ISSUE THREAD

**Issue by jing3018** [meetecho/janus-gateway#679]
jansson use malloc ,but we use g_free to release the memory.
new glib use system malloc to alloc memory, so I think we need to update glib to avoid this problem. now I use glib-2.48.2.

**Comment by lminiero** [comment]
We don't use g_free on jansson stuff so I don't see any problem.

Il 09/nov/2016 04:18, "Ging" <notifications@github.com> ha scritto:

**Comment by jing3018** [comment]
see `json_dumps` related code 
eg 
transports/janus_rabbitmq.c:639
```
char *payload_text = json_dumps(response->payload, json_format);
...
g_free(payload_text);
```

**Comment by lminiero** [comment]
Good point, I hadn't thought about those. I guess they're the only occurrences where that may happen, though. I never experienced issues but it might be because on my Fedora glib has always been new "enough" (I have 2.44 right now). Probably the easiest way to avoid issues no matter the version is to simply use `free` instead of `g_free` for all the `json_dumps` we use.
