### ISSUE TITLE
Not working on OSX?

### ISSUE THREAD

**Issue by IvRRimum** [meetecho/janus-gateway#680]
Tried to install all deps. Stuck at libnice. using https://github.com/Homebrew/homebrew-boneyard

says:

```
Error: libnice was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

**Comment by lminiero** [comment]
Refer to #666, I don't own a Mac, never used it, never will and didn't
write the original instructions, sorry.

Il 10/nov/2016 22:37, "Ivrrimum" <notifications@github.com> ha scritto:

Tried to install all deps. Stuck at libnice. using
https://github.com/Homebrew/homebrew-boneyard

says:

Error: libnice was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetecho/janus-gateway/issues/680>, or mute the thread

**Comment by IvRRimum** [comment]
Yeah, trying to figure out how to pull his pull request localy now. Will update on the status.

**Comment by IvRRimum** [comment]
Yeah, i think it's not possible to build on OSX. Trying Virtualbox linux mint now.

**Comment by lminiero** [comment]
Closing as not related to Janus itself, but to libnice availability.
