### ISSUE TITLE
Crash on deleting room(videoroom plugin)[refcount branch]

### ISSUE THREAD

**Issue by gabriel-munteanu** [meetecho/janus-gateway#736]
I found this bug and also found this fix that works for me :D

Remove code from line 1497
`
g_hash_table_remove(rooms, GUINT_TO_POINTER(room_id));
`

and add it modified before `janus_mutex_unlock(&rooms_mutex);` at line 1527
`
g_hash_table_remove(rooms, &room_id);`

**Comment by lminiero** [comment]
The `GUINT_TO_POINTER` is a good catch, as since it's a 64 bit integer we do indeed need the value of the ID now (probably a leftover). Moving the code should not be needed, as that `g_hash_table_remove` only decreases the reference counter for the room, which is still kept by the users still in there. Anyway, after that we have a loop to kick them all out, which means a race condition might occur that destroys the room before we get to the `janus_mutex_unlock(&videoroom->mutex);` part after the loop.

I'll make a few checks myself and in case apply the fix, thanks for noticing us about this! I'll probably have to check if a similar thing exists in other plugins too.

Mentioning #403 as well so that folks there are aware of this.

**Comment by lminiero** [comment]
This commit should handle this more gracefully: it fixes the `GUINT_TO_POINTER` stuff, and simply adds a reference to the room before marking it as destroyed, so that we can loop on users before decreasing it again. This way we should avoid race conditions or potential locks that could have happened by moving the unlock (e.g., if any of the `end_session` ended up locking it too in the same thread and cause a deadlock).

**Comment by lminiero** [comment]
Let me know if that fixes it for you or not.

**Comment by gabriel-munteanu** [comment]
It is OK now. Thank you!
