### ISSUE TITLE
New to add setting to AJAX requests

### ISSUE THREAD

**Issue by dmancini** [meetecho/janus-gateway#742]
I'd like to add a product enhancement request so we can avoid having to merge in our enhancements every time we upgrade. Hopefully this is the right place. We needed to add the xhrFields setting to all the AJAX requests in janus.js 

	xhrFields: { withCredentials: loadBalanceEnabled }

because we needed this property when putting our application behind a load balancer. We passed a boolean in as an extra parameter to the Janus constructor:

	var loadBalanceEnabled;
	function Janus(gatewayCallbacks, loadBalEnabled) 
		loadBalanceEnabled = loadBalEnabled;

**Comment by lminiero** [comment]
I don't like adding new parameters unless really required. Properties like these belong to the `gatewayCallbacks` argument instead, which unlike what the name suggests, is not only a collection of callbacks but also properties you can specify (e.g., server, iceServers, iceTransportPolicy and so on).

That said, in this case it would make much more sense to provide an optional custom `xhrFields` object property to `gatewayCallbacks`, rather than just `loadBalanceEnabled`, so that users can possibly add even others in a configurable way without needing new properties all the time. Anyway, I'm a bit hesitant in this case, as I'd like to keep the jquery and non-jquery versions aligned, and I'm not sure how this can achieved in janus.nojquery.js

**Comment by lminiero** [comment]
Any info on how this can be used without jquery?

**Comment by lminiero** [comment]
I guess this is it:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

I'll add this to the TODO list.
