### ISSUE TITLE
janus.js: eventHandler() - timeout: 60000 // FIXME

### ISSUE THREAD

**Issue by logidelic** [meetecho/janus-gateway#746]
Hey all,

Would just like to know what the "fixme" is about for the timeout in janus.js's errorHandler()... I have tried reducing this timeout, but this results in some false failures, which I guess is why it was placed at such a large value. However, I don't understand why the timeout should trigger so easily (under good network conditions)...

Any insight would be appreciated.

**Comment by lminiero** [comment]
The FIXME is a reminder to possibly negotiate session timeouts with the server, instead of assuming 60 seconds, which would as a coonsequence result in different timeouts on ajax as well. The errors you see are probably because, when you use HTTP, there is a 30 seconds long poll: if you use a timeout shorter than that, the long poll request will be considered as failed.

Closing as not an issue, which is what we use Github for. For discussions like this please post on the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
