### ISSUE TITLE
websocket interface ips when set are ignored, it still binds to all

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#772]
both of these when set are ignored, it always binds to all ips
ws_ip
wss_ip

using the latest git checkout

**Comment by lminiero** [comment]
Which version of libwebsocket are you using?

**Comment by bhakimi** [comment]
2.0.2

**Comment by bhakimi** [comment]
should i be using a different version or is this a bug?

**Comment by lminiero** [comment]
I didn't have time to verify yet, I'll try to do that tomorrow.

**Comment by bhakimi** [comment]
thank you

**Comment by lminiero** [comment]
Sorry for the lack of feedback, but I've been (and still am) abroad for a WebRTC event. I'll investigate on Monday as soon as I get back to the office (please remind me if I don't).

**Comment by bhakimi** [comment]
will do, thank you

**Comment by lminiero** [comment]
Tried with `ws_interface` and it works as expected for me, only binding to the interface I specify. `ws_ip` doesn't seem to work instead, you're right. The way we're doing it is to basically pass the dotted IP address as the `iface` property when you set the IP, which should work as explaining in https://github.com/warmcat/libwebsockets/issues/538. The [documentation](https://libwebsockets.org/libwebsockets-api-doc.html) though only mentions interface names. I guess we'll have to crawl the interfaces when an IP is provided, so that we can get the interface name out of that.

For the time being, if you need to limit what websockets bind to, use the interface name instead.

**Comment by bhakimi** [comment]
I run multiple instances so I can't use the interface name

**Comment by lminiero** [comment]
Fixed and works for me, let me know if that's not the case.

**Comment by bhakimi** [comment]
Thank you
