### ISSUE TITLE
Multiple "joined" events from single "join" message in audiobrige module

### ISSUE THREAD

**Issue by thehunmonkgroup** [meetecho/janus-gateway#795]
Under a 'high join load' (meaning many users joining at exactly the same time), the audiobridge module is sending spurious "joined" events to users connected to an audiobridge room. This bug does not seem to happen unless a lot of users are joining at exactly the same time.

I've tested carefully, and verified through event monitoring that the Janus server is receiving only one audiobridge "join" message from my application.

I've been able to reproduce this problem many times on latest master, although it is intermittent, so I suspect some kind of race condition.

Here's an example of what the multiple messages look like...

The first is a normal join event:
```javascript
{
  audiobridge: "joined",
  id: 1668574437004109,
  room: 705163598413955100,
  participants: Array[6]
}
```
While the second is missing the ```id``` parameter:
```javascript
{
  audiobridge: "joined",
  room: 705163598413955100,
  participants: Array[1]
}
```

And this particular test involved the user connecting to an audiobridge room with 7 other participants. It looks to me like that second event should have ```audiobridge: "event"``` instead of ```audiobridge: "joined"``` for the audiobridge key, in the form of that normally arrives when a new user joins an audiobridge room you've already joined.

**Comment by lminiero** [comment]
I don't see why that should happen only on high loads, as from what I can see in the code, there's nothing weird and that's the expected behaviour. It's all explained in detail in the documentation we have online, which is automatically generated from the code itself (you'll see the same text at the beginning of the module code):

https://janus.conf.meetecho.com/docs/janus__audiobridge_8c.html

Quoting:

```
About the syntax of all the above mentioned requests, join has to be formatted as
follows:
[..]
A successful request will produce a joined event:
[..]
The other participants in the room will be notified about the new participant by means
of a different joined event, which will only include the room and the new participant
as the only object in a participants array.
```

This is the part of the code where we prepare a `"joined"` event to notify other users about your new availability:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L2657

Notice how we don't add the ID to the root, but as a property of the only participant in the list. Here, instead, is where we do prepare the event to return to you instead:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L2700

In this case, you ID is added to the root, while the participants list contains a list of everybody currently in the room. The same logis is followed for the `changeroom` request, as it's basically a leave(old)+join(new):

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L3082
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L3126

The `"audiobridge":"event"` is only used to notify about people leaving and changes triggered by a configure:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_audiobridge.c#L2782

and is not meant by itself to advertise presence about users.  In that case, the participants list you get is not the complete list of participants, but only a way to convey the new info on the participant that has changed his configuration (e.g., muted->unmuted or, when it will be merged, the new display name as you implemented it), and so does not have to be seen as a complete overview of the currently available users. If everybody in the room also configures, then yes, others get info about that user with that event too, but their ID and display have already been notified before with the `joined` event.

Closing as not an issue.

**Comment by thehunmonkgroup** [comment]
Ok, thanks for clearing that up, I'll adjust my code accordingly.
