### ISSUE TITLE
uses static paths below /tmp

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#814]
Janus uses static paths below /tmp.

Since /tmp is world writable, using static (or easily guessable) paths is security-flawed antipattern.

Default configuration uses these problematic paths:
/tmp/janus.log
/tmp/janus.pid
/tmp/janus-audioroom-1234.wav
/tmp/janus-videoroom
/tmp/voicemail/
/tmp/ux-janusapi
/tmp/ux-janusadmin

Code contains these problematic paths:
/tmp/janus-audioroom-%"SCNu64".wav
/tmp/sctp
/tmp/ux-janusapi
/tmp/ux-janusadmin

Documentation (manpages) mention these problematic paths:
/tmp/januslog

Please instead use appropriate autotools-expanded paths instead - e.g. runstatedir for janus.pid.

**Comment by lminiero** [comment]
None of those values are static or hardcoded, AFAIK. They're all configuration values one can change in the cfg files.

**Comment by jonassmedegaard** [comment]
Not intuitive:

Leave log_to_file commented out and /tmp will not be used, but comment out pfunix path and /tmp will be used.

**Comment by lminiero** [comment]
What would be a reasonable replacement? We don't force Janus to start as root, meaning it's definitely allowed to start Janus as your default user, and as such those directories should be writable. While the user's home might be an idea, not all users do have a home folder, and besides there's no way to have the home be part of the sample configuration files.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-15 11:53:01)
> What would be a reasonable replacement? We don't force Janus to start as root, meaning it's definitely allowed to start Janus as your default user, and as such those directories should be writable. While the user's home might be an idea, not all users do have a home folder, and besides there's no way to have the home be part of the sample configuration files.

I see 4 scenarios:

 a) System-wide service (use FHS paths)
 b) Personal service (use XDG paths)
 c) Critical service on locked-down system (use special paths)
 d) Relaxed service on trusted system (use e.g. /tmp)

My issue here is that you seem to aim for d) which is a bad default.

You use autotools, which by default offers paths for scenario a) but can 
be overridden for other scenarios.

If you want by default to cover another scenario then you can do that 
with autotools (with some work), or you can switch to another build 
framework which is more "modern" (which might also be "superior" but 
possible not) and support another scenario by default.  E.g. npm.

I recommend to make it hard for your users to shoot themselves in the 
foot, not easy.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by lminiero** [comment]
autotools wouldn't help, as you don't know which user will be used to start Janus, at compile time. The only solution I see is to get rid of defaults entirely, and put commented stuff like `/path/to/` in config file placeholders that will force people to set what they want there.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-15 12:17:37)
> autotools wouldn't help, as you don't know which user will be used to start Janus, at compile time. The only solution I see is to get rid of defaults entirely, and put commented stuff like `/path/to/` in config file placeholders that will force people to set what they want there.

Since autotools is used not only to configure and build, but also to 
install (make install), I believe it is appropriate to rely on 
autotools.

But, as I already mentioned, you are free to not rely on autotools for 
install.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by cmacq2** [comment]
@jonassmedegaard I agree with your core point that the default is not particularly nice and vulnerable. However it is not entirely clear which cases Janus ought to support here, or alternatively how the default selection should work. I see broadly two alternatives:

1. Make such default paths configurable at `./configure` time. Redo the default config templates to interpolate the configured defaults: i.e. make the default configuration be explicit, but do not touch the vulnerable defaults in other parts of the code. This leaves the issue: what if the user does not pass these paths during `./configure`?
 2. Improve the C code to guess better defaults. This is may be complex because of the various scenario's you outlined: how do you detect when to use XDG dirs, for example? Should XDG dirs take precedence based on some environment variable for example? Is it sufficient to use `mkstemp()` or `tmpfile()`?

**Comment by jonassmedegaard** [comment]
Quoting cmacq2 (2017-03-15 20:27:53)
> @jonassmedegaard I agree with your core point that the default is not particularly nice and vulnerable. However it is not entirely clear which cases Janus ought to support here, or alternatively how the default selection should work. I see broadly two alternatives:
> 
> 1. Make such default paths configurable at `./configure` time. Redo the default config templates to interpolate the configured defaults: i.e. make the default configuration be explicit, but do not touch the vulnerable defaults in other parts of the code.

Autotools _already_ makes paths configurable at configure time - all you 
need to do is identify the variables offered by autotools and make use 
of them instead.


This leaves the issue: what if the user does not pass these paths during `./configure`?

Path variables can be overridden at the "make install" call.

Configuration files can be adjusted after install.


>  2. Improve the C code to guess better defaults. This is may be complex because of the various scenario's you outlined: how do you detect when to use XDG dirs, for example? Should XDG dirs take precedence based on some environment variable for example? Is it sufficient to use `mkstemp()` or `tmpfile()`?

I strongly recommend against implementing variability into the code: 
Either hardcode something safe, or have the code fail loudly if not fed 
needed configuration.

I consider it "safe" to hardcode paths for system-wide use (i.e. follow 
the FHS - File Hierarchy Standard): On Unix-like systems such paths can 
be expected to work for the appropriate user only, and fail due to lack 
of access for any other user.

Arguably it can be considered "safe" to hardcode paths for any-user 
(i.e. store within $HOME) but in my subjective opinion that is a more 
modern pattern which is expected mostly by desktop-ish daemons (and 
daemons written by Daniel Bernstein).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by cmacq2** [comment]
> Autotools _already_ makes paths configurable at configure time - all you
need to do is identify the variables offered by autotools and make use
of them instead.

Yes: I was referring to adding the necessary knobs in `configure.ac` and then use those prefs as defines during compile time to specify the defaults assumed by the C code if no explicit config is provided at run time. These would be Janus specific variables and not standard variables like `--prefix`.

Which is why I think...

> Path variables can be overridden at the "make install" call.

... Is not likely to work. Unless `autotools` has built in handling of Janus log output directories, any such variables would probably become `-DSOME_PATH_VAR=/your-choice-here`.

**Comment by lminiero** [comment]
Implemented a fix my own way, by changing a couple of defaults and for the rest using commented placeholders (e.g., `/path/to`) that will need users to modify/set them (notice that this means the Unix Sockets plugin will not work until you set a path, as there's no sensible default for that). If you're ok with this, I'll close the issue, otherwise please provide a PR with whatever you'd be more comfortable with.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-17 12:29:34)
> Implemented a fix my own way, by changing a couple of defaults and for the rest using commented placeholders (e.g., `/path/to`) that will need users to modify/set them (notice that this means the Unix Sockets plugin will not work until you set a path, as there's no sensible default for that). If you're ok with this, I'll close the issue, otherwise please provide a PR with whatever you'd be more comfortable with.

I'm good. Thanks!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by lminiero** [comment]
Closing then :+1:
