### ISSUE TITLE
Failing HTTP API requests, and a large number of libmicrohttpd threads

### ISSUE THREAD

**Issue by Sean-Der** [meetecho/janus-gateway#829]
Hi!

For background I use the textroom and videoroom plugin only, and I create those rooms at runtime via the HTTP API. That is pretty much the full usage of my Janus usage.

One of our Janus servers out of nowhere stopped responding to requests, and after logging in saw that it had allocated about 10GB of memory and it had way more threads then I expected.

I did a `thread apply all bt` to the box after a few days of uptime and noticed a large amount of libmicrohttpd threads, is this normal? It seems that the amount of threads grow as time goes on (and I am make requests against the service) I will try investigating more, but I definitely can't use valgrind here and I would be worried to use AddressSanitizer and have it exiting while users are on it.

[libmicrohttpd threads in Janus](https://gist.github.com/Sean-Der/14d4586f187c207c572f751dd2b20297)

**Comment by lminiero** [comment]
Please use services like gist or pastebin when providing such huge bunches of text.

I don't know how libmicrohttpd handles its thread internally, but you can configure a limited pool in the configuration file: https://github.com/meetecho/janus-gateway/blob/master/conf/janus.transport.http.cfg.sample.in#L14
Due to the way the plugin works and long polls, the size of the pool will limit the number of sessions you can handle at the same time (as a long poll request may keep a thread busy for while, until a response is provided). One of the things I'm planning to do in the near future is revisit this (ideally to make MHD work single threaded, or possibly to use libwebsockets for HTTP as well), but for the time being this is what I can suggest. No idea on why that should fill the memory: are you creating sessions that you never destroy?

If you're doing this in the background (from a server?), you may want to consider another transport you can use as a control channel, e.g., websockets or any of the others.

**Comment by Sean-Der** [comment]
Thanks for the feedback!
I switched from libmicrohttpd -> libwebsockets as well for an internal project and I was very happy I did, the libwebsockets API is way more intuitive.

I will try out the limited thread pool and that way I can rule out libmicrohttpd causing problems.

This is all I am doing right now
```
curl -XPOST http://localhost:8088/janus -d '{'janus': 'create', 'transaction': 'ABC123'}'
curl -XPOST http://localhost:8088/janus/GlobalId -d '{'janus': 'attach', 'plugin': 'janus.plugin.videoroom', 'transaction': 'ABC123'}'
curl -XPOST http://localhost:8088/janus/GlobalId/VideoRoomId -d '{'janus': 'message', 'body': {'request': 'create', ......}, 'transaction': 'ABC123'}'
```

Am I leaking any resources by just doing this for videoroom/textroom? I thought the timeout was cleaning up for me.

thanks!

**Comment by lminiero** [comment]
The libmicrohttpd is very flexible too, making it work with a limited number of threads (or even a single one) simply needs [more effort](https://www.gnu.org/software/libmicrohttpd/manual/html_node/microhttpd_002dflow.html). Using this is what I'd like to work on in the near future. The fact we use `MHD_USE_THREAD_PER_CONNECTION` right now makes things much easier but also spawns more threads: coupling this with a thread pool should limit it for the time being.

As to how you use it, yes, timeouts should kick in and clean things up. Sending a destroy when you've done your thing would simply be a cleaner way of wrapping up.

**Comment by Sean-Der** [comment]
Thanks @lminiero I am going to limit things and close for now, if I get something concrete I will reopen with more data.

thanks
