### ISSUE TITLE
RTSP restarts

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#845]
The problem: when the RTSP session gets interrupted for any reason, Janus just hangs there thinking that the session is still active. This is somehow similar to #753, but obviously on a different level because here we're talking server <--> janus and not janus <--> client.
Would be nice if the streaming plugin could detect that the stream died and automatically try to restart it.
This feature is quite important for me, so I can work on it if nobody is going to take it in charge, but probably I would need some hint on how to implement it.

**Comment by lminiero** [comment]
Good point and definitely a valid use case.

I'll have to review how we setup the RTSP stuff in this case, but I guess one way to do that would be decoupling the RTSP setup from the creation process, so that it can be done in a separate context as well. A failure/disconnection in the RTSP stream should result in the stream to be disabled (and we have properties for that), so that attempts to subscribe make it clear it's impossible for the moment. When the stream becomes up again, it can be re-enabled.

I think there's another problem to consider, though, that is what should be considered an interruption we can recover from, and when we should give up. For instance, if an RTSP server was working, then dies and never comes back, do we retry forever? How often?

I'll give this some more thought and try to come back to you with more helpful information. I can also work on this myself, but this probably won't happen before next week.

**Comment by fbertone** [comment]
For my use case, retry indefinitely would be nice.
How often? Don't have an opinion right now, maybe using the timeout parameter from the SETUP and a default if not indicated? Or a parameter in the cfg file?
If you can work on it that would be great, I need to solve it but it's not super urgent.

**Comment by lminiero** [comment]
I've added it to the TODO list, will try to look into this as soon as I can.

**Comment by lminiero** [comment]
Something we didn't discuss: how do you detect an RTSP session is over? Are we talking about something libcurl tells us about, or something else?

**Comment by fbertone** [comment]
I was thinking of something like periodically checking when was the last RTP packet received, if it's older than a threshold I presume that the session is dead.
I don't know if libcurl can automatically do that or it must be done manually (I think manually?)

**Comment by lminiero** [comment]
We do have `last_received_audio` and `last_received_video` we can use for the purpose. I'll keep that in mind.

**Comment by lminiero** [comment]
Implemented in the PR above, please test.
