### ISSUE TITLE
Feature Request: also support G.711 ulaw/alaw for audio bridge plugin

### ISSUE THREAD

**Issue by mscdex** [meetecho/janus-gateway#877]
As the title says, it would be nice to have G.711 ulaw/alaw support for the audio bridge plugin. This would be incredibly helpful for interoperating with other audio sources that do not support the opus codec.

**Comment by mirkobrankovic** [comment]
+1 but re-transcoding is a bit tricky i guess

**Comment by lminiero** [comment]
Transcoding would not be that hard, we already mix raw frames, and encoding/decoding G.711 is trivial (there are tables that can be used). Anyway, I fail to understand the need for it. The AudioBridge plugin only mixes WebRTC users, and Opus is mandatory to implement: which WebRTC clients that only talk G.711 are we talking about here?

**Comment by mscdex** [comment]
This wouldn't be for WebRTC users but external audio sources/sinks. Perhaps the audio bridge plugin isn't what I'm looking for. I need to be able to do audio *only* between a WebRTC user and an external RTP stream (mostly WebRTC->External but will also want WebRTC<->External at some point).

**Comment by mscdex** [comment]
I saw that `rtp_forward` has a payload type option but I wasn't sure if actual transcoding would take place if it was set to a G.711 payload type or if that value is just what's passed on in the RTP packet (causing a potential data mismatch).

**Comment by mirkobrankovic** [comment]
Indeed, is there a reason why non-webrtc client that could send sdp with one ice cand   wouldn't get into mix?

**Comment by mscdex** [comment]
I'm not sure I understand your question. The external/non-webrtc RTP stream never deals with SDP at all, it's just a raw (G.711 -- typically ulaw in my case) RTP stream.

**Comment by mirkobrankovic** [comment]
@mscdex , but i think you need to advertise source ip/port at least, otherwise where would you receive mixed audio. Not sure is srtp is mandatory for audiobridge plugin

**Comment by mscdex** [comment]
@mirkobrankovic I haven't really dived into Janus much yet, so I'm not very familiar on the various flows, but I guess I'd need a way to generate an SDP with the RTP stream info in it to be able to use the stream in Janus?

I saw the NoSIP plugin PR, but as I started to read some of the use cases later in that thread I'm not sure it'd work for my use case or not...?

**Comment by lminiero** [comment]
The RTP forwarding feature in the AudioBridge is not for what you think. It's only used when you want the mix to be forwarded to an external component via plain RTP, no signalling involved: a use case may be forwarding this to a Streaming mountpoint on a Janus instance somewhere else, so that people can listen to the mix without needing to contribute anything (useful if you want a selected set of people to actively contribute to the discussion, and many more to just listen); other use cases may be external recording or processing (e.g., an FFmpeg sitting there and receiving the RTP/Opus packets to do interesting stuff).

As such, it's NOT meant as a way to inject media from non-WebRTC participants. The AudioBridge is ONLY for mixing WebRTC participants via Janus. A way to allow people to use G.711 instead of Opus wouldn't be complicated, but I'm just wondering if it's actually useful: e.g., it might be for WebRTC endpoints that don't ship Opus, but in this case we're either thinking of custom applications, or possibly a choice to reduce the mixing+encoding computation load; definitely not providing PSTN access or the like, as they'd have no way to join the WebRTC bridge AudioBridge provides.

**Comment by lminiero** [comment]
Closing as not planned for now.

**Comment by huchunnuan** [comment]
also request for supporting g711
