### ISSUE TITLE
Janus API through datachannel

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#890]
Hello,

I'm writing a plugin that uses only datachannels (something very similar to textroom).

I have the special requirement that once the session is instantiated, **all** communication should go through the datachannel.

This is in conflict with the long-poll used to keep alive the session. If I disable the ajax calls, the session dies.

* It would be possible to implement the janus API in datachannels? (I guess that would be a *transport*?) [feature request]

If that's not possible, or as a quick workaround in the meantime:

* do you think that could be implemented as a plugin? (I send the messages through the datachannel and the plugin makes a local request to the http API or whatever)

**Comment by lminiero** [comment]
That's not possible, since as you noticed the Janus API would need to be implemented as a transport plugin, and that cannot be done by an application plugin.

One way would be do as you suggest, that is the plugin simply acting as a "proxy" between datachannels and any of the transports available on the box (websockets would be a better choice than http, here). As an alternative, you could even think of writing your own transport plugin that doesn't really expose anything to the outside (e.g., no webserver, no rabbit queue, etc.) but only talks in the background with your own application plugin somehow. Probably more efficient, but not that different than just connecting to any of the existing transports and so not worth the pain I guess.

Anyway, you'd need to create a new session over datachannels, then: the session you create to spawn the datachannel cannot be "migrated" to another transport.

Closing as not a code issue. Feel free to bring this to the group if you'd like to discuss this with the community.
