### ISSUE TITLE
Detect the audio level change from speaking to not speaking 

### ISSUE THREAD

**Issue by atyenoria** [meetecho/janus-gateway#900]
https://github.com/meetecho/janus-gateway/pull/760
The functionality of audiolevel detection works well. I'm very thankful for this.
I have a question. Is it possible to detect the change from the state of speaking to the state of not speaking?
At now, I can get only the the change from the state of not speaking to the state of speaking.
This is very similar to https://github.com/otalk/hark .
Btw, for mobile app development, react-native-webrtc can't get the audio level ( oney/react-native-webrtc#276 ). So, There is no possible solution for this ( only for react-native developer? )
So, This feature is very good solution for detecting the speaker for both web and mobile at now.
How do you feel that?

**Comment by lminiero** [comment]
Not sure exactly when we'll be able to work on this, but added to the TODO list :+1:

**Comment by lminiero** [comment]
Sorry if this is taking a while, but we're quite busy these days... Just to clarify, are you talking of AudioBridge or VideoRoom for this events? I guess both, considering the mechanism is actually very similar?

Anyway, I've been thinking about how this could be done and I have a few doubts. Right now, we're sending several "talking" events in sequence, depending on the amount of packets we need to process before we can decide somebody's speaking. Following a new "talking"/"not talking" event, this would need to change, as we would only send a "talking" event the first time we detect the user started speaking, while we would not send others if our calculation still detects the user as speaking: we'd remain in the same state. On the other hand, if the calculation detects the user is not speaking, while he was speaking before, we should send something like "not talking".

The issue I see here with this new state-based notification mechanism, is in how we should handle new users joining: to make an example, what happens when you a new user joins *after* you send a "talking" event. In fact, this new user would not receive the "talking" event (we're not sending them on a regular basis anymore), but may only receive the "not talking" one later. We'll probably have to keep track of this talking state as part of the participant's properties, so that when somebody new joins we can notify about the talking status of all talking participants just as if the user started talking only now. The same would apply to both plugins, I guess, possibly with slightly different semantics.

Does this sound reasonable? Pinging @mirkobrankovic as he implemented the feature originally for additional feedback.

**Comment by lminiero** [comment]
Another alternative, which would not change the way the notifications work right now, is to simply add a "not talking" event for the first time we detect the user is not speaking anymore. This means you'd still get the sequence of "talking" events, and at a certain point you get a "not talking" which you handle accordingly. The "not talking" would not be repeated, as it would be the default, even for new joins. Probably easier to implement, but I don't like the event repetition, so the new approach might be better.

**Comment by lminiero** [comment]
Created a PR that implements the first approach I described. Please test and let me know if that works.

**Comment by mirkobrankovic** [comment]
Indeed keeping the state will lower the amount of events sent to users which is always a benefit, plus having a non talking event is also good.

**Comment by atyenoria** [comment]
Perfect! Thank you very much!

**Comment by jadbox** [comment]
Is the an example of this? Do I need to configure the server to enable this feature or does it work out of the box?

**Comment by jadbox** [comment]
Also, is this using similar method of Hark to try to detect actual speech versus picking up background noise?
