### ISSUE TITLE
Sort the received RTP packets in ICE module

### ISSUE THREAD

**Issue by ridgeback1982** [meetecho/janus-gateway#901]
If I am right, the RX RTP packet is pushed to the end of the queue currently. I think the right way is to insert the packet to queue according to its seq number, to eliminate the NACKs which may happen at relay side.

**Comment by lminiero** [comment]
Not sure what you're asking: the title talks of received RTP packets, but then you mention retransmissions for the send queue. Incoming packets, retransmitted or not, don't get in any queue, they're decrypted and passed to the plugin immediately. For outgoing traffic, there wouldn't be any point in ordering by sequence number, as being a retransmission it's definitely later than any packet that may be in queue anyway.

The best we can do is push some packets ahead of the queue, instead of the tail as we do for them all. This could apply for retransmitted packets, but also for RTCP we generate ourselves (e.g., RR/SR). Again, not sure if this is what you meant, so if not please elaborate.

**Comment by ridgeback1982** [comment]
Thank you for your quick response. I am sorry for the misunderstanding.
Let's assume A --> Janus --> B:
Currently when Janus received a NACKed packet from A, it is pushed to the tail of the queue. I think "push to tail" is not right. The packet should be inserted to where it should be, according to its sequence number. That makes sense when relaying the head of the queue to B.  The disordered packet will be sent to B in order. B will generate less NACKs.

**Comment by lminiero** [comment]
As I said, there's a wrong assumption here of there being a queue between A and Janus. When you get a packet, `janus_ice_cb_nice_recv` fires which then passes it right away to the plugin via `plugin->incoming_rtp`. Incoming packets are never queued, and plugins never see the distinction between a regular packet and a retransmitted one: if reordering should be done, it should be within the plugin, but most don't buffer anything either and relay right away so there would be no point. The NACK logic you see in `janus_ice_cb_nice_recv` (in case that's what confused you) is related to something different, that is detecting if we're missing incoming packets from A and so whether we have to send a NACK for them. We only queue outgoing packets (Janus --> B in your example), because plugins don't have to block and so we have a dedicated thread per PeerConnection.

**Comment by ridgeback1982** [comment]
Actually, in my case, B is another WebRTC client. B will generate NACKs if B received disordered packets. 
I understand that the NACK processing in Janus is for client A, to make sure Janus doesn't miss A's packet. If there is one packet "P1" retransmitted, the packet is push to tail of `queued_packets` like other packets. Looking at the `queued_packets`, it is not ordered because of "P1". Then we send every packet of `queued_packets` in a thread, and P1 is sent without order. B is probably to find a disorder of "P1", and B generate a NACK for "P1". 
We can avoid B's NACK of "P1" if we send "P1" in its order.

**Comment by lminiero** [comment]
Yeah, but since we also fire packets right away, packets before P1 have already been sent, so there's nothing to reorder. As I explained in my first response, the best we can do is put retransmitted packets (and/or RTCP packets) ahead of the queue instead of the end (as I'm not even sure you can do sorting on Glib queues), as it's definitely "older" than every other packet we're going to send.

**Comment by lminiero** [comment]
This also means we'd have to put a cap on the queue, though... if we always privilege retransmissions, and the link is bad, this means you'll never get "fresh" packets, or anyway too late for them to be meaningful.

**Comment by ridgeback1982** [comment]
Yes, I ignored one thing: queue is nearly empty at most of time, no room for reorder. It is also not a good idea to bring a limitation of minimal size of queue. 
It make sense to put the retransmitted packet ahead of queue.

**Comment by lminiero** [comment]
> It make sense to put the retransmitted packet ahead of queue.

It will probably not be as simple as that, as putting in front will reverse the order of some packets: e.g., you get 3 nacks, for seqs 4, 7 and 8, so you put in front 4, 7, and 8, which means the order in the queue will be 8, 7 and 4 now, and then whatever existed already. We'd have the same issue for RTCP feedback. I'll have to think if there's an easy way to handle that (and another queue is probably not the answer, as we can't wait on both as we do now for the only one we have).
