### ISSUE TITLE
release a new bower version

### ISSUE THREAD

**Issue by Fuzzyma** [meetecho/janus-gateway#920]
I installed janus with bower and tested the echo example.
It seems to work fine until I got the error message `windows.navigator.match`.

Well - the error message is right. And the error seems to be fixed in this repo.
So please add a new tag so we can fix that new version from bower.
Otherwise all people which are not Safari or Chrome user will get this error message

**Comment by lminiero** [comment]
We'll add a new tag when we'll ready to release a new tagged version. If you can get bower to get master instead of a tag, then I see no issue. Apart from that, as I've said numerous times, I don't use bower and I know nothing about it, so I'm not going to chase it to make things working there any time we make a change, sorry.

**Comment by lminiero** [comment]
We tagged 0.2.3 just a few days ago, BTW.
