### ISSUE TITLE
Update pin for videoroom/streaming after creation

### ISSUE THREAD

**Issue by Sean-Der** [meetecho/janus-gateway#939]
Hey!

So I have a situation where I want to update the pin while publishers/participants are in the room. I have n people chatting/viewing a video and then a person is kicked/leaves. Would you accept a PR that allows the pin to be changed?

I was thinking of adding another request 'update' maybe, and for now if the admin_key is present allowing the pin to be set/updated. I will just do an atomic swap on the current pin and making sure all readers copy before comparing. Then in the future others can add things to modify the room if they want.

**Comment by lminiero** [comment]
Definitely sounds like a useful feature, so a pull request would be very
welcome, thanks!

Il 29 giu 2017 9:35 PM, "Sean DuBois" <notifications@github.com> ha scritto:

**Comment by lminiero** [comment]
@Sean-Der I ended up implementing a framework for doing this in AudioBridge, VideoRoom and TextRoom myself. It currently allows you to configure some (but not all) of the properties of an existing room, and to decide whether the changes should be permanent or not. One thing to highlight is that if you make a non-permanent change, and a permanent change later, then the non-permanent change from before is also saved to file, because we simply dump whatever the current configuration of the room is.

All the new properties one wants to modify need to be prefixed by `new_`, so for your use case, you'd need to do something like this:

```
sfutest.send({
	message: {
		request: "edit",
		room: 9000,
		secret: "pippo",
		new_pin: "newpinhere"
	}
});
```

Notice the `secret` there is the current secret. If you wanted to change the room secret as well, you'd set it via `new_secret`. A `permanent: true` saves to file.

Hope this helps and addresses what was your requirement in an effective way. I made some quick tests on all plugins, and they seemed to work as expected, but some feedback would of course be welcome. Closing this issue as solved, just ping in case you want it reopened.
