### ISSUE TITLE
Reconnect and resume transport

### ISSUE THREAD

**Issue by iclems** [meetecho/janus-gateway#979]
Today, whenever the connection is lost for some time, the Janus instance error is called and the session becomes disconnected. 

At this stage, there's no clean way to resume a session, but it's not killed and cleaned up automatically either. 

We could consider implementing directly at janus.js level a reconnect logic and monitoring of the network status. It feels complicated to implement that outside of janus.js and too much to recreate a complete Janus instance every time the connection comes back online.

**Comment by lminiero** [comment]
Sessions are cleaned up after about 60s: that's what the timeout mechanism is for. That said, reclaiming a session might be an interesting feature: I thought about this some time ago, but never worked on it as I remember finding some issues in the logic I wanted to follow. We can definitely discuss how this could be implemented in upcoming versions.

**Comment by iclems** [comment]
Sure that'd be interesting. On my side, I implemented a logic similar to what Firebase does with its realtime database: watch for network status and API disconnects, and automatically schedule reconnects if the network is up with randomized increasing times or instantly at the time the network comes back up. It's pretty efficient and helps with scalability. I'm wondering if this wouldn't be better placed directly within Janus rather than outside. As an app using Janus, you'd expect it to manage reconnecting automatically I suspect?

**Comment by iclems** [comment]
More importantly, there's no easy way to clean up sessions locally today from what I understand. Right now, my auto reconnect mechanism checks if there's any connected session and if not, automatically reconnects. But since the previous sessions have failed and set their connected = false, at this stage, calling session.destroy doesn't work so you're stuck with ghost disconnected sessions locally.

**Comment by lminiero** [comment]
Have you checked the Admin API already? https://janus.conf.meetecho.com/docs/admin
If you query a session, it will tell you if it exists, when it was last refreshed, etc.

**Comment by iclems** [comment]
Sure, but that's not meant to be used directly by end users right? My point is that sessions on the client side are a mess if you keep the window running and have to face network disconnects and reconnect automatically.

**Comment by lminiero** [comment]
Apparently missed this issue after the summer break, sorry about that... was the problem just reclaiming ownership of a session after a disconnection? If so, this is something that you cannot currently do with Janus, as each session is tightly coupled with the transport instance that originated it. It *may* work if you were using HTTP, the timeout didn't fire yet (session still alive) and when reconnecting you're aware of the session and handle(s) IDs you were using before so that you can do a new long poll hoping you didn't miss any state, but I wouldn't rely on this too much. If you really need this feature, it's best to wrap the Janus API on the server side, so that the server keeps the connection going even when the client leaves, and any session refresh can be done by a custom API of your choice. Does this make sense?

**Comment by lminiero** [comment]
Closing as implemented in #1199.
