### ISSUE TITLE
Janus videoroom plugin should offer inactive for offered recvonly

### ISSUE THREAD

**Issue by zdila** [meetecho/janus-gateway#985]
In 2.2, if client sent offer to Janus with video `a=recvonly` then Janus sent offer to other clients (room members) with `a=inactive`.
In 2.4 Janus sends offer to other clients with `a=sendonly` and so client waits for a video stream that will never come (only audio). We consider it as a bug.

We can work it around by not setting `offerToReceiveVideo: true` when creating the offer, but as the client is already distributed and will take time to deply a new version it is not a solution for us.

**Comment by lminiero** [comment]
I think we removed that `a=inactive` line in the offer because it broke I don't remember what. The proper way of doing that would be to remove the m-line entirely, I guess, considering we don't even allow a renegotiation later on. Not sure if we "solved" that by setting `sendonly`, though, it doesn't look like something I'd do.

That said, as another short term fix for subscriptions you can just pass `offer_video:false` when subscribing and you'll only get an audio m-line.

**Comment by lminiero** [comment]
Ok, I think I understand what's happening. Since 0.2.2, we started using the SDP utils, so here's where we create the offer for viewers: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L4219
This sets the audio and video direction to `JANUS_SDP_SENDONLY` (only used if an audio or video m-line exist, of course), so that's why it's `sendonly` even if you sent `inactive` (which you shouldn't). I guess that one way to fix it might be checking the direction in the original offer: if it was `inactive`, then we set the video property to `false` in general (we'll treat the publisher as audio only), which means viewers will only get an audio m-line.

**Comment by artmatsak** [comment]
Thank you, @zdila's colleague here. The sender doesn't send `inactive` but `recvonly` for video. In that case, the video property should also be set to `false`, with the receivers only getting an audio m-line. In 0.2.4, this doesn't happen and receivers get the video m-line with a `sendonly`, which is wrong.

**Comment by lminiero** [comment]
Yep, got it, see my second answer above and the proposed solution: you still shouldn't send a `recvonly` for a publisher anyway, is what I meant :slightly_smiling_face:

**Comment by artmatsak** [comment]
Unfortunately, we already have the publisher sending `recvonly` in shipped production code in our mobile apps and we can't roll those back.

Isn't it a bug in Janus though? Logically, if there's no video track coming from the publisher (`recvonly`), the receivers should not get a `sendonly` video m-line, which makes them expect video.

**Comment by lminiero** [comment]
Yep, it is a bug, that I'll fix later today :+1:

**Comment by artmatsak** [comment]
Great, thanks!

**Comment by lminiero** [comment]
This fixes it in my tests, please let me know if that's not the case.
