### ISSUE TITLE
Websocket: PING/PONG

### ISSUE THREAD

**Issue by uasan** [meetecho/janus-gateway#986]
Hello.

There is a way to use an internal `libwebsocket` PING/PONG, instead of send `keepalive`?

Thanks.

**Comment by lminiero** [comment]
Not sure what this ping/pong thing is? A transport level keepalive mechanism of some sort? If you're familiar with it, is there any chance you could prepare a PR? About `keepalive`, since it's an API request it is an application level thing, so you're free to ignore it (which would mean "yes" to your answer above, once this ping/pong thing is available).

**Comment by uasan** [comment]
> Not sure what this ping/pong thing is? A transport level keepalive mechanism of some sort?

Yes, this is part of Websocket protocol specification, here is comment by LWS
https://github.com/warmcat/libwebsockets/issues/729#issuecomment-269084233

> is there any chance you could prepare a PR?

I not C developer, but do something in client JavaScript :)

> About keepalive, since it's an API request it is an application level thing, so you're free to ignore it (which would mean "yes" to your answer above, once this ping/pong thing is available).

Yes, this is an extra noise in the network and it does not work well in mobile browsers, when the page is in the background, browsers suspend timeinterval callbacks.

**Comment by lminiero** [comment]
So it should just be a matter of adding

```
info.ws_ping_pong_interval = 5;
info.timeout_secs = 5;
```

to the WS stuff initialization, where maybe we can make that `5` configurable in the settings. If so, it sounds like an easy fix. I'll see if I have time to add that later.

**Comment by lminiero** [comment]
As a side note, I'm incorrect in saying that you don't need `keepalive`. You still need to send one every now and then, otherwise from an application layer the `session_timeout` will kick in (i.e., no API message received in the last 60 seconds) and the connection will be dropped anyway. So yes, ping/pong will make it more efficient for websockets to keep connections alive, but for a session timeout of 60s I'd still send a `keepalive` every 50s or so.

**Comment by uasan** [comment]
> but for a session timeout of 60s I'd still send a keepalive every 50s or so.

Why, if websocket connection is not closed, the session should not be closed, I can not guarantee sending messages every 60s to mobile browsers.

`session_timeout = 0` - do not cause memory leak after closing connection websocket?

**Comment by lminiero** [comment]
The application level timeout is needed, because we cannot safely rely on transports for that, as they're modular and have different characteristics. Websockets have a way to tell us that, HTTP doesn't for instance, and we need to handle all cases (even transport modules that haven't been written yet).

As it is now, yes, `session_timeout = 0` will cause a leak if you just close the connection (or if the ping/pong tells us it's closed), becuse that event simply sets `last_activity = 0`, which should trigger a timeout that, with `session_timeout = 0`, will never be handled. Thinking about it, a similar thing happens when sending a "destroy", as the cleanup stuff never activates if session timeouts are disabled. I'll have to think of a better way of allowing transports going away to force a session destruction while at the same time allowing application level timeouts to be disabled.

**Comment by uasan** [comment]
>  I'll have to think of a better way of allowing transports going away to force a session destruction while at the same time allowing application level timeouts to be disabled.

I think for keepalive transport (websocket, unixsocket, etc) do not need keepalive messages.
Event `close` in keepalive transport (websocket, unixsocket, etc), should cause session destruction.

Thanks.

**Comment by lminiero** [comment]
Again, that's not something the core can decide. It has no notion whatsoever of what transports are, how they work and what they do. I have to do something that will work for ALL of them, even those I don't even know exist.

I'll try to fix the leaks for `session_timeout=0` so that you can use that plus the new ping/pong stuff, but this will always be something users will need to activate manually like that.

**Comment by uasan** [comment]
> Again, that's not something the core can decide. It has no notion whatsoever of what transports are, how they work and what they do. I have to do something that will work for ALL of them, even those I don't even know exist.

The most correct way, when websocket server accepts PONG from the client, it send keepalive signal to core Janus, then everything will good :)

Then e.g. mobile network offline (closing websocket), then network online, then reconnect to the existing session Janus, is real?

**Comment by lminiero** [comment]
This commit implements support for the ping/pong mechanism in the WebSockets transport: it needs to be manually enabled, setting both `pingpong_trigger` (when to send a PING) and `pingpong_timeout` (how long to wait for a PONG) in the configuration file.

This still does NOT address the sessions timeout stuff. I'll keep this issue open to track that part too, hopefully soon.

**Comment by uasan** [comment]
> This commit implements support for the ping/pong mechanism in the WebSockets transport

Yes, it works, thanks.

**Comment by uasan** [comment]
Maybe you will be interested, there is a mechanism for TCP Keepalive, that can be used for unixsocket connections
http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/

**Comment by lminiero** [comment]
We don't use TCP for the Unix Sockets.

**Comment by uasan** [comment]
Yes, you use `SOCK_SEQPACKET`  or `SOCK_DGRAM`, if used `SOCK_STREAM` can be TCP Keepalive, without send `keepalive` text message.

**Comment by lminiero** [comment]
This new commit takes care of what we discussed. Now, if you set `session_timeout=0` and enable ping/pongs in WebSocket, you shouldn't worry about leaks anymore. Please test and let me know if it works as expected (tested briefly and seems to be working fine for me).

Closing, will reopen if you find an issue.

**Comment by uasan** [comment]
Tested `session_timeout=0` and `ping/pong`, HTTP 2 client -> Nginx -> WS server
Is ok, WSS connect and Janus session living, thanks!

The memory leak has not yet been noticed...

**Comment by tgabi333** [comment]
Ping-pong feature of libwebsockets came with 2.1.0. So this change breaks builds with pre 2.1.0.

**Comment by lminiero** [comment]
Thanks for the heads up, I'm on a newer version and it worked for me. I'll add a check for this in the code.

**Comment by lminiero** [comment]
This commit should fix it: https://github.com/meetecho/janus-gateway/commit/f4781e8afcb474fb293fd2a251e896744693f5aa

**Comment by uasan** [comment]
In latest master version Janus, websocket server does not send to client Ping, the Nginx proxy closes connection by timeout.

Something broke in latest commits?

**Comment by lminiero** [comment]
Mh, we only changed from context to vhost, the ping pong stuff should not be affected. Please remind me to check this tomorrow, when I'm back at the office.

**Comment by uasan** [comment]
Ping

**Comment by lminiero** [comment]
The ping pong stuff is there, but maybe vhosts ignore it (I don't know the library in detail, sorry). Try setting it on the master context, that is, after this line here: https://github.com/meetecho/janus-gateway/blob/master/transports/janus_websockets.c#L317

```
#if LWS_LIBRARY_VERSION_MAJOR >= 2 && LWS_LIBRARY_VERSION_MINOR >= 1
	if(pingpong_trigger > 0 && pingpong_timeout > 0) {
		wscinfo.ws_ping_pong_interval = pingpong_trigger;
		wscinfo.timeout_secs = pingpong_timeout;
	}
#endif
```

to see if they start working again.

**Comment by lminiero** [comment]
Yeah, it looks like it can be set for contexts only: https://libwebsockets.org/lws-api-doc-master/html/structlws__context__creation__info.html#a33a1a25a7df3793f59047e20dd580078
Let me know if the proposed change I posted fixes it for you, and I'll push a commit.

**Comment by uasan** [comment]
Compile error, after my patch :(

`
transports/janus_websockets.c: In function ‘janus_websockets_init’:
transports/janus_websockets.c:320:9: error: ‘pingpong_trigger’ undeclared (first use in this function)
      if(pingpong_trigger > 0 && pingpong_timeout > 0) {
         ^~~~~~~~~~~~~~~~
transports/janus_websockets.c:320:9: note: each undeclared identifier is reported only once for each function it appears in
transports/janus_websockets.c:320:33: error: ‘pingpong_timeout’ undeclared (first use in this function); did you mean ‘pending_timeout’?
      if(pingpong_trigger > 0 && pingpong_timeout > 0) {
                                 ^~~~~~~~~~~~~~~~
                                 pending_timeout
]\'/09
`

**Comment by lminiero** [comment]
Yeah, that's because we create the context before reading the config file. Try moving the original 315-322 lines (the code to create the context) to line 440 (after the ping pong stuff has been parsed) and adding the new lines I mentioned there.

**Comment by uasan** [comment]
Yes, it PING/PONG works, thanks!

**Comment by uasan** [comment]
No, still, after 60 seconds, the session timeout.

**Comment by lminiero** [comment]
Do you see the ping/pong or not, when looking at the packets? I received two different mail notifications about this. Anyway, unfortunately I won't be able to look into this until next week, as I'll be abroad for a conference. If you can collect more data and make some more experiments with the code, please let me know and I'll try to incorporate whatever works.

**Comment by uasan** [comment]
Not ping :(

**Comment by uasan** [comment]
Is there progress on this issue?

**Comment by lminiero** [comment]
I only returned to the office today, so no. As I anticipated, I was abroad last week. I'll try to make some tests but the only thing I can try is moving some code to put it in the context instead of vhost as I already suggested you: if this doesn't work as you say, I don't know what else to do.

You may want to open an issue on the libwebsockets github page, as they may know more, e.g., if ping/pong is supposed to work on vhosts in general: feel free to reference this issue there.

**Comment by lminiero** [comment]
With this commit here: https://github.com/meetecho/janus-gateway/commit/c136fc550b7b0b80d51973bfc814252fa576aeee
ping/pong works as expected for me.

**Comment by uasan** [comment]
Works great, thanks!
